#!/bin/bash

#########################
#  FILTERS
#########################

apply_filters()
{
where_flag=0
if [ "X$WHERE" = "X" ];then
  where_flag=1
  WHERE="WHERE $NEWLINE "
fi

if [ "X$OBJ_RECORD_TABLE" = "X" ];then
  OBJ_RECORD_TABLE=svcrecord_$TRNUM
fi

if [ "X$STARTTIME" != "X" ];then
  WHERE="$WHERE $NEWLINE  AND $OBJ_RECORD_TABLE.SvcNSRelTime >= $STARTTIME"
fi

if [ "X$ENDTIME" != "X" ];then
  WHERE="$WHERE $NEWLINE  AND $OBJ_RECORD_TABLE.SvcNSRelTime+$OBJ_RECORD_TABLE.SvcTotalTime<=$ENDTIME"
fi

#Response time filter
if [ "X$RESPTIMEQMODE" != "X" ];then
  if [ $RESPTIMEQMODE -eq 1 ];then
    WHERE="$WHERE $NEWLINE  AND svcrecord_$TRNUM.svcsortime <= $RESPONSETIME"
  elif [ $RESPTIMEQMODE -eq 2 ];then
    WHERE="$WHERE $NEWLINE  AND svcrecord_$TRNUM.svcsortime >= $RESPONSETIME"
  elif [ $RESPTIMEQMODE -eq 3 ];then
    WHERE="$WHERE $NEWLINE  AND svcrecord_$TRNUM.svcsortime >= $RESPONSETIME"
    WHERE="$WHERE $NEWLINE  AND svcrecord_$TRNUM.svcsortime <= $RESPONSETIME2"
  fi
fi

if [ "X$STATUS" != "X" ];then
  NOF=`echo $STATUS |awk -F ',' '{print NF}'`
  if [ $NOF -gt 1 ];then
    WHERE="$WHERE $NEWLINE  AND $OBJ_RECORD_TABLE.svcstatusindex in ($STATUS)"
  else
    if [ "X$STATUS" = "X-1" ];then
      WHERE="$WHERE $NEWLINE  AND $OBJ_RECORD_TABLE.svcstatusindex > 0"
    elif [ "X$STATUS" != "X-2" ];then
      WHERE="$WHERE $NEWLINE  AND $OBJ_RECORD_TABLE.svcstatusindex = $STATUS"
    fi
  fi
fi

if [ "X$INSTANCENAME" != "X" ];then

  FROM="$FROM $NEWLINE  , SvcInstanceTable_$TRNUM"
  WHERE="$WHERE $NEWLINE  AND SvcInstanceTable_$TRNUM.instanceid  = $OBJ_RECORD_TABLE.instanceid"
  WHERE="$WHERE $NEWLINE  AND SvcInstanceTable_$TRNUM.instancename  = '$INSTANCENAME'"
fi

if [ "X$INSTANCEID" != "X" ];then
  WHERE="$WHERE $NEWLINE  AND $OBJ_RECORD_TABLE.instanceid  = $INSTANCEID"
fi

if [ "X$WHERE" != "XWHERE $NEWLINE " -a $where_flag -eq 1 ];then
  WHERE=`echo "$WHERE"|sed '4s/^\([[:blank:]]*\)AND /\1/'`
elif [ "X$WHERE" = "XWHERE $NEWLINE " ];then
  WHERE=""
fi

}
