#!/bin/sh
#######################################################################################################
# Name   : nsi_db_svc_get_id_name_metadata
# Syntax : nsi_db_svc_get_id_name_metadata --testrun <value>
#
#   Author  : Ambuj Singh
#   Date    : 22/05/2013
#   Purpose : This shell will display the result in the following format based on the test run number given
#             
#             instanceid:instancename 
#           
# Example   :  ./nsi_db_svc_get_id_name_metadata --testrun 3253
#
#
#########################################################################################################

######################################################################
#                     Variables and init settings
#####################################################################


TRNUM=""
OBJECT=""
SELECT="SELECT"
FROM="FROM"
ORDER="ORDER BY"
FILE_TYPE=""
#Including nsi_db_utils
. $NS_WDIR/bin/nsi_db_utils

########################################################################
#                       Functions's Definitions
#######################################################################

#Function for displaying usage
usage()
{
 echo "$*"
 echo "Usage:"
 echo "$0 --testrun <value> "
 echo ""
 echo "Where"
 echo "  --testrun is test run number, which is mandatory argument."
 exit 1
}

#Function for checking mandatory argument
chk_args()
{
 
  if [ "X$TRNUM" == "X" ]; then
    usage "Test run argument is missing"
  fi
}



#################################################################
#                      Calling functions
#################################################################

#Parsing the arguments
if [ "X$*" = "X" ];then
usage
fi
init $*
RUNNING=$?

#Checking Mandatory arguments
chk_args

# Setting query files
set_query_files $TRNUM

#Check if SVC table exists
psql test cavisson <<+ >/tmp/tmp_svc_$$
  SELECT 
    count (*) 
  FROM 
    INFORMATION_SCHEMA.TABLES 
  WHERE 
    TABLE_TYPE='BASE TABLE' 
    AND TABLE_NAME='svcinstancetable_$TRNUM'
+

FLAG_SVC_TABLE_EXISTS=`tail -3 /tmp/tmp_svc_$$|head -1| sed 's/ //g'`
rm -f /tmp/tmp_svc_$$

if [ "X$FLAG_SVC_TABLE_EXISTS" = "X0" ]; then
  exit 0
fi


SELECT="$SELECT instanceid,instancename"
FROM="$FROM svcinstancetable_$TRNUM"
ORDER="$ORDER instanceid"
FILE_TYPE="instance_ids.dat"

#RET value 0 -if file already cached and test is not running, 
#          1- if file not cached and test is not running ,              
#          2- if test is running
if [ $RUNNING -ne 2 ];then
  check_cached $FILE_TYPE
  RET=$?
else
  RET=2
fi

if [ $RET -eq 2 -o $RET -eq 1 ];then
  ns_run_query
  show_query_result_colon_sep > $DBQ_CACHE_DIR/$FILE_TYPE
fi

cat $DBQ_CACHE_DIR/$FILE_TYPE 

exit 0
