#!/bin/bash

HEADERLINE=1

# Including nsi_db_utils
. $NS_WDIR/bin/nsi_db_utils

#Clean cache directory
clean_cache_dir $1

BASE_DIR=""
CSV_ARRAY="SvcErrorCode.csv SvcRecord.csv SvcCompRecord.csv SvcSignatureTable.csv SvcTable.csv"
MISSING_FILE=""
LC_FLAG=0

#Checking Test number is valid or not
if [ -d $PWD/TR$1 ]; then
  BASE_DIR=$PWD
elif [ -d $NS_WDIR/logs/TR$1 ]; then
  BASE_DIR=$NS_WDIR/logs
else
  echo "Error: Test run number $1 is not a valid test run number"
  exit -1
fi


#count the total lines in csv files
echo
INSTANCE_CSV_DIR=(`cd $BASE_DIR/TR$1; ls -Frt svc/csv | grep '/' | cut -d '/' -f 1 |  tr '\n' ' '`)
NUM_INSTANCE_DIR=${#INSTANCE_CSV_DIR[@]}
echo "TOTAL Number of Instances are : " $NUM_INSTANCE_DIR
echo 
echo 
echo "nsu_svc_import: Counting number of lines in individual csv files ..."
echo "-------------------------------------------------------------------"
printf "%30s  %13s\n" "csv file" "num of lines"
echo "-------------------------------------------------------------------"


 for csv in $CSV_ARRAY
 do
  FLG=0
  T_LC=0
  FILE_FOUND=0
  for (( i = 0; i<$NUM_INSTANCE_DIR; i++ ))
    do  
    if [  -f $BASE_DIR/TR$1/svc/csv/${INSTANCE_CSV_DIR[$i]}/$csv  ]; then
      LC=`wc -l $BASE_DIR/TR$1/svc/csv/${INSTANCE_CSV_DIR[$i]}/$csv|awk '{print $1}'`
      FILE_FOUND=1
      T_LC=`expr $T_LC + $LC`
      LC=0
      FLG=1
    fi
    done
    if [ "$FLG" -eq 1 ]  
      then
        #echo "Total lines in file $csv = $T_LC."
        printf "%30s  %10d\n" $csv $T_LC
    
    else
          MISSING_FILE=$csv
          #echo "Error: $MISSING_FILE file not found in the test run directory."
          printf "%30s  %25s\n" $csv "*** FILE NOT FOUND ***"

    fi
  done
 echo "-------------------------------------------------------------------"
  if [ "X$MISSING_FILE" != "X" ]; then
    echo "nsu_svc_import: Exiting because mandatory file $MISSING_FILE not present in the test run directory."
    exit -1
  fi
 echo "nsu_svc_import: ... Done counting number of lines in individual csv files ..."

 echo
 echo "nsu_svc_import: Creating transaction components tables ..."
 . nsu_svc_create_table $1
 echo "ndu_import: ... Done creating transaction component tables."


####################################################################################################
####               
####                        Copying records from csv files to the database
####

#____________________________________________________________________________
#
#     if there are headers in the csv file then we can ignore it.
#     by default it is being ignored
#     to enable it we pass the second argument to the shell
#           0----->not needed(default)
#           1----->ignore the header in the csv file
#
#____________________________________________________________________________

if [ $HEADERLINE -eq 1 ]; then
 for (( i = 0; i<$NUM_INSTANCE_DIR; i++ ))
    do
    psql test cavisson <<+
      \copy SvcRecord_$1 FROM '$BASE_DIR/TR$1/svc/csv/${INSTANCE_CSV_DIR[$i]}/SvcRecord.csv' WITH CSV HEADER DELIMITER ',' NULL AS ''
      \copy SvcCompRecord_$1 FROM '$BASE_DIR/TR$1/svc/csv/${INSTANCE_CSV_DIR[$i]}/SvcCompRecord.csv' WITH CSV HEADER DELIMITER ',' NULL AS ''
      \copy SvcTable_$1 FROM '$BASE_DIR/TR$1/svc/csv/${INSTANCE_CSV_DIR[$i]}/SvcTable.csv' WITH CSV HEADER DELIMITER ',' NULL AS ''
      \copy SvcSignatureTable_$1 FROM '$BASE_DIR/TR$1/svc/csv/${INSTANCE_CSV_DIR[$i]}/SvcSignatureTable.csv' WITH CSV HEADER DELIMITER ',' NULL AS ''
      \copy SvcErrorCode_$1 FROM '$BASE_DIR/TR$1/svc/csv/${INSTANCE_CSV_DIR[$i]}/SvcErrorCode.csv' WITH CSV HEADER DELIMITER ',' NULL AS ''
+
 done
    psql test cavisson <<+
      \copy SvcInstanceTable_$1 FROM '$BASE_DIR/TR$1/svc/csv/SvcInstanceTable.csv' WITH CSV HEADER DELIMITER ',' NULL AS ''
+

elif [ $HEADERLINE -eq 0 ]; then
 for (( i = 0; i<$NUM_INSTANCE_DIR; i++ ))
    do
    psql test cavisson <<+
      \copy SvcRecord_$1 FROM '$BASE_DIR/TR$1/svc/csv/${INSTANCE_CSV_DIR[$i]}/SvcRecord.csv' WITH DELIMITER ',' NULL AS ''
      \copy SvcRecord_$1 FROM '$BASE_DIR/TR$1/svc/csv/${INSTANCE_CSV_DIR[$i]}/SvcCompRecord.csv' WITH DELIMITER ',' NULL AS ''
      \copy SvcTable_$1 FROM '$BASE_DIR/TR$1/svc/csv/${INSTANCE_CSV_DIR[$i]}/SvcTable.csv' WITH DELIMITER ',' NULL AS ''
      \copy SvcSignatureTable_$1 FROM '$BASE_DIR/TR$1/svc/csv/${INSTANCE_CSV_DIR[$i]}/SvcSignatureTable.csv' WITH DELIMITER ',' NULL AS ''
      \copy SvcErrorCode_$1 FROM '$BASE_DIR/TR$1/svc/csv/${INSTANCE_CSV_DIR[$i]}/SvcErrorCode.csv' WITH DELIMITER ',' NULL AS ''
+
   done

else
  echo "ERROR: Ambiguous Header Line mode"
  exit 1 #exit shell script

fi

sleep 2

##################################################################################################
####
####                       Showing the number of records in each table of tx component 

echo

echo
echo "nsu_svc_import: Checking number of records in all tables ..."
psql test cavisson <<+
    SELECT count(*) AS SvcTable_$1               FROM SvcTable_$1;
    SELECT count(*) AS SvcSignatureTable_$1      FROM SvcSignatureTable_$1;
    SELECT count(*) AS SvcErrorCode_$1           FROM SvcErrorCode_$1;
    SELECT count(*) AS SvcRecord_$1              FROM SvcRecord_$1;
    SELECT count(*) AS SvcCompRecord_$1          FROM SvcCompRecord_$1;
+
