#!/bin/bash


# Author: Shalu
# Purpose: This shell will check for all the generator testrun are extracted and and call the shell nii_generate_compare_report shell, In case all 
# test runs are not extracted , it will wait for 5 minutes and after that it will call shell nii_generate_compare_report

TR_NUM=0
COUNT=0
TIME_COUNT=0
CALL_NORM_ID=0
DYNAMIC_URL_TABLE_SIZE=0
MAX_STATIC_URL_IDS=0
CTRL_WORK_DIR=/home/cavisson/work
MERGE_PG_DUMP_FILES=0

do_processing()
{
  if [ -f $NS_WDIR/logs/TR$TR_NUM/NetCloud/NetCloud.data ]; then 
    TR_ARRAY=(`cat $NS_WDIR/logs/TR$TR_NUM/NetCloud/NetCloud.data |cut -d " " -f2 | cut -d "|" -f1`)
    GEN_NAME_ARRAY=(`cat $NS_WDIR/logs/TR$TR_NUM/NetCloud/NetCloud.data |cut -d "|" -f2`)
    TR_COUNT=${#TR_ARRAY[@]}
 
    while [[ $TIME_COUNT -lt 60 ]]
    do
      COUNT=0;
      for (( i=0; i<$TR_COUNT; i++ ))
      do
        if [ -f $NS_WDIR/logs/TR$TR_NUM/NetCloud/${GEN_NAME_ARRAY[$i]}/TR${TR_ARRAY[$i]}/ready_reports/status ]; then 
          #echo " Test run ${TR_ARRAY[$i]} is extracted " 
          #COUNT=`expr $COUNT+1`
          let COUNT=COUNT+1
        fi
      done
      if [[ $COUNT == $TR_COUNT ]]; then
        break;
      else 
        sleep 5
        TIME_COUNT=`expr $TIME_COUNT + 1`
      fi 
    done 
    nii_generate_compare_report $TR_NUM 
    if [ $CALL_NORM_ID == 1 ];then
      #bin/nii_norm_gen_url_id -t 3969 -Z 8192 -i 1 -W /home/cavisson/Achint
      nii_norm_gen_url_id -t $TR_NUM -Z $DYNAMIC_URL_TABLE_SIZE -i $MAX_STATIC_URL_IDS -W $CTRL_WORK_DIR
      nii_cat_gen_csv_files $TR_NUM
    fi

    for (( i=0; i<$TR_COUNT; i++ ))
    do
      if [ -d $NS_WDIR/logs/TR$TR_NUM/NetCloud/${GEN_NAME_ARRAY[$i]}/TR${TR_ARRAY[$i]}/harp_files ];then
        cp $NS_WDIR/logs/TR$TR_NUM/NetCloud/${GEN_NAME_ARRAY[$i]}/TR${TR_ARRAY[$i]}/harp_files/* $NS_WDIR/logs/TR$TR_NUM/harp_files 2>/dev/null
      fi
    done

    if [ $MERGE_PG_DUMP_FILES == 1 ];then
      nii_cat_page_dump_files $TR_NUM
    fi
    nii_get_pct_data -t $TR_NUM
  fi
}

while getopts t:Z:i:nW:p c
do
  case $c in
  t) TR_NUM="$OPTARG";;
  Z) DYNAMIC_URL_TABLE_SIZE="$OPTARG";;
  i) MAX_STATIC_URL_IDS="$OPTARG";;
  W) CTRL_WORK_DIR="$OPTARG";;
  n) CALL_NORM_ID=1;;
  p) MERGE_PG_DUMP_FILES=1;;
  ?) usage;;
  esac
done

do_processing
