#!/bin/sh

. $CAV_MON_HOME/bin/ns_check_monitor_func.sh

MY_PID=$$

add_pid_in_excp_list $MY_PID >/dev/null 2>&1

#************************************************************************************************
NS_TA_DIR=""
PROJ=""
SUB_PROJ=""
SCENARIO_NAME=""
ADDITIONAL_KW=""

set_proj_subproj()
{  
   PROJ=`echo ${1} | egrep "/" | cut -d'/' -f1`
   SUB_PROJ=`echo ${1} | egrep "/" | cut -d'/' -f2`
}

#i/p would be <prj>/<subproj>/<scenario_name>
set_proj_subproj_scenario()
{
   set_proj_subproj $1
   SCENARIO_NAME=`echo ${1} | egrep "/" | cut -d'/' -f3`
}
#************************************************************************************************

SCENARIO=""
ONLY_SCENARIO_NAME_WITH_PRO_SUBPR=""
MASTER_IP=""
CAV_EPOCH_DIFF=""
while getopts w:n:m:d:u:t:e:g:C:? c
do
    case $c in
    w)NS_WDIR_LOCAL="$OPTARG";;
    n)ONLY_SCENARIO_NAME_WITH_PRO_SUBPRO="$OPTARG";; 
    m)MASTER_IP="-m $OPTARG";;
    d)CONTROLLER_WDIR="$OPTARG";;
    u)CONTROLLER_USR_GRP_NAME="$OPTARG";;
    t)CONTROLLER_TEST_RUN="$OPTARG";;
    e)CAV_EPOCH_DIFF="$OPTARG";;
    g)DISABLE_USE_OF_GEN_SPEC_KWD="$OPTARG";;
    C)ADDITIONAL_KW="-C $OPTARG";;
    esac
done

ulimit -s 16384

#************************************************************************************************
#set absolute test assets path
#NS_TA_DIR=`$NS_WDIR_LOCAL/bin/nsi_get_work_space_path.sh $WORK_PROFILE`
#************************************************************************************************

#Added the -d option to provide the controller work directory
export NS_WDIR=$NS_WDIR_LOCAL
export NS_CONTROLLER_WDIR=$CONTROLLER_WDIR
#Added -u option to provide controller's user name and group name
export NS_CONTROLLER_USR_GRP_NAME=$CONTROLLER_USR_GRP_NAME
#Added -t option to provide controller's test run number
export NS_CONTROLLER_TEST_RUN=$CONTROLLER_TEST_RUN
export NS_CAV_EPOCH_DIFF=$CAV_EPOCH_DIFF
export CHROME_DEVEL_SANDBOX=/usr/local/sbin/chrome-devel-sandbox

GEN_SPECIFIC_SITE_KEYWORDS=$NS_WDIR/sys/gen_specific_site_keywords.default
SCENARIO="-n $ONLY_SCENARIO_NAME_WITH_PRO_SUBPRO"
set_proj_subproj_scenario ${ONLY_SCENARIO_NAME_WITH_PRO_SUBPRO}

WORK_PROFILE=admin/system
NS_TA_DIR=$NS_WDIR/workspace/admin/system/cavisson
export WORK_PROFILE
WPARGS=" -W ${WORK_PROFILE}"

#Check for generator specific keyword file. 
#if file is there then add the file at the end of scenario
#DISABLE_USE_OF_GEN_SPEC_KWD -> Its value came through Keyword (DISABLE_USE_OF_GEN_SPECIFIC_KWD_FILE). 
#DISABLE_USE_OF_GEN_SPEC_KWD -> It specify we can used sys/gen_specific_site_keywords.default file or not on generator's
if [ $DISABLE_USE_OF_GEN_SPEC_KWD -eq 0 ];then
  if [ -f $GEN_SPECIFIC_SITE_KEYWORDS ];then
     echo "#Generator specific keywords" >>$NS_TA_DIR/$PROJ/$SUB_PROJ/scenarios/${SCENARIO_NAME}
     cat $GEN_SPECIFIC_SITE_KEYWORDS >>$NS_TA_DIR/$PROJ/$SUB_PROJ/scenarios/${SCENARIO_NAME}
  fi
fi

# In NetCloud setup we need to set generator machines with path provided by controller, therefore earlier we
# were trying to set PATH variable here.
# export PATH=$NS_WDIR/bin:$NS_WDIR/tools:$PATH
# But in ubuntu machines when logging as sudo or su it reset PATH variable with default path, hence this path
# provided by controller was overridden by default path.
# In release 3.9.6,
# In order to fix above issue save generator path in local variable and later in nsu_start_test export PATH variable 
# with this local variable 
export GEN_PATH=$NS_WDIR/bin:$NS_WDIR/tools:/home/cavisson/thirdparty/bin:$PATH
export HOME_DIR=/home/cavisson
export HOME=$HOME_DIR

#To set JMETER_HOME in generators
if [ -f $NS_WDIR/bin/nsu_get_jmeter_version ]; then
   . $NS_WDIR/bin/nsu_get_jmeter_version
fi

userid=`id -u`
if [ "$userid" == "0" ];then
  echo "CavMonAgent is running with root user. root user is not allowed 
        to run the test on generator. Kindly restart cmon with cavisson user"
  remove_pid_from_excp_list $MY_PID >/dev/null 2>&1
  exit -1
else
  ret=`$NS_WDIR/bin/nsu_start_test $SCENARIO $MASTER_IP -S gui ${WPARGS} $ADDITIONAL_KW`
fi

if [ $? -eq 0 ];then
  START_EXIT_VAL=0
else
  START_EXIT_VAL=-1
fi

echo $ret
remove_pid_from_excp_list $MY_PID >/dev/null 2>&1
exit $START_EXIT_VAL 
