#! /bin/sh
#
# chkconfig: 2345 98 02
# description: cavgen server
# cavgen   Start up cavgen
### BEGIN INIT INFO
# Provides:             cavgen
# Required-Start:       
# Required-Stop:        
# Should-Start:         
# Should-Stop:          
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    cavgen
### END INIT INFO

cavgen_service()
{
export NS_CONTROLLER_NAME=work
export NS_WDIR=/home/cavisson/$NS_CONTROLLER_NAME
if [ $NS_CONTROLLER_NAME == "work" ];then 
  export CAVGEN_CMD=cavgen
else
  export CAVGEN_CMD=cavgen_$NS_CONTROLLER_NAME
fi
. $NS_WDIR/bin/nsi_cavgen_control $1
}

USERID=`id -u`
if [ $USERID -ne 0 ];then
  cavgen_service $1
else
  export -f cavgen_service
  su cavisson -c "cavgen_service $1"
fi

