#! /bin/sh
#
# chkconfig: 2345 98 02
# description: cavisson  system
# Name: cavisson
#
### BEGIN INIT INFO
# Provides:             cavisson
# Required-Start:       
# Required-Stop:        
# Should-Start:         
# Should-Stop:          
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    cavisson
### END INIT INFO

export NS_WDIR=/home/cavisson/work
. $NS_WDIR/etc/netstorm.env

#export JAVA_HOME=/apps/java/j2sdk1.4.0

#export PATH=$NS_WDIR/bin:$PATH:$JAVA_HOME/bin:$TOMECAT_HOME/bin:/sbin:/bin:/usr/sbin:/usr/bin


COMMAND="${NS_WDIR}/bin/nsi_on_reboot"

DESC="Cavisson"

set -e

case "$1" in
  start)
    echo "Starting $DESC: "

    echo "executing $COMMAND"
    nohup $COMMAND &
    if [ -c /dev/cavmodem ];then
        chmod 666 /dev/cavmodem
    fi
    ;;
  stop)
    echo "Stopping $DESC: "
    ;;
  restart|force-reload)
    echo "Restarting $DESC: "
    ;;
  *)
    N=/etc/init.d/$0
    echo "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
