#! /bin/sh
#
# chkconfig: 2345 98 02
# description: nhpd server
# tomcat   Start up hpd
#
#     Written by Miquel van Smoorenburg <miquels@cistron.nl>.
#     Modified for Debian GNU/Linux
#     by Ian Murdock <imurdock@gnu.ai.mit.edu>.
#     Modified for Tomcat and Cocoon by <markj@luminas.co.uk>

export NS_WDIR=/home/cavisson/work
. ${NS_WDIR}/etc/netstorm.env

CONFIG=`grep CONFIG $HOME/etc/cav.conf | awk '{print $2}'`
if [ $CONFIG == 'NS+NO' ];then
    PORT=81
else
    PORT=80
fi

export PATH=$PATH:$JAVA_HOME/bin:$TOMECAT_HOME/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=$HPD_ROOT/nsu_start_hpd
NAME=hpd
DESC="hpd"

#test -f $DAEMON || exit 0

set -e

case "$1" in
		  start)
			echo -n "Starting $DESC: "
			cd $HPD_ROOT; $HPD_ROOT/nsu_start_hpd
			echo "$NAME."
			;;
		  stop)
			echo -n "Stopping $DESC: "
			$HPD_ROOT/nsu_stop_hpd
			echo "$NAME."
			;;
		  restart|force-reload)
			echo -n "Restarting $DESC: "
			$HPD_ROOT/nsu_stop_hpd
			sleep 1
			cd $HPD_ROOT; $HPD_ROOT/nsu_start_hpd -p $PORT
			echo "$NAME."
			;;
		  *)
			N=/etc/init.d/$NAME
			echo "Usage: $N {start|stop|restart|force-reload}" >&2
			exit 1
			;;
esac

exit 0
