#!/bin/bash
#Purpose: This file is to make tar of src; For which properly cleaning the src, gui, netchannel dir.
#Auther: Atul
#Date : 08/18/2007

logFile="/tmp/logMakeSrcTar"
cleanNetstorm()
{
  echo "Cleaning Netstorm" 1>>$logFile 2>&1
  make clean 1>>$logFile 2>&1
  echo "Removing export" 1>>$logFile 2>&1
  rm -rf export/ 1>>$logFile 2>&1
}

cleanGUI()
{
  echo "Cleaning GUI" 1>>$logFile 2>&1
  cd gui;
  make clean 1>>$logFile 2>&1
  rm -rf export/ srcbak/ 1>>$logFile 2>&1
  cd ..
}

cleanNetChannel()
{
  echo "Cleaning NetChannel" 1>>$logFile 2>&1
  cd netchannel;
  make clean 1>>$logFile 2>&1
  cd ..
}
>$logFile
cleanNetstorm
cleanGUI
cleanNetChannel
echo "Moving thirdparty outside src" 1>>$logFile 2>&1
mv thirdparty/ ../thirdpartybak/ 1>>$logFile 2>&1
echo "Moved..." 1>>$logFile 2>&1
tar cvzf ../srcbak.tar.gz ../src/ 1>>$logFile 2>&1
echo "Moving thirdparty inside src" 1>>$logFile 2>&1
mv ../thirdpartybak/ thirdparty/ 1>>$logFile 2>&1
echo "Moved..." 1>>$logFile 2>&1
