#!/bin/sh

if [ "X$NS_WDIR" == "X" ];then
  echo "Error: NS_WDIR must be set"
  exit -1
fi

TIME_STAMP=`date +%y-%m-%d_%H:%M:%S`
  
LOG_SIZE=1048576 # 1 MB
LOG_PATH="$NS_WDIR/ndc/logs/ndi_runtime_changes.log"

logger()
{
  file_size=`ls -l $LOG_PATH 2>/dev/null| awk '{print $5}'`
  if [  "X$file_size" != "X" ]  && [ $file_size -ge $LOG_SIZE ];then
    mv $LOG_PATH ${LOG_PATH}.prev
  fi
  echo $TIME_STAMP $* >>$LOG_PATH 
}

if [ $# != 6 ]; then
  echo "Usages:"
  echo "======"
  echo "$0 ND_COLLECTOR_IP ND_COLLECTOR_PORT TierName ServerName AppName Keyword=<value>;Keyword=<value>;.....;"
  echo "Example"
  echo "$0 10.10.40.8 7802 T1 S1 A1 \"instrProfile=Weblogic.xml;bciInstrSessionPct=80;\""
  exit -1
fi

logger "INPUT ARGUMENT:" "$*"
COMM_OUTPUT=`ndi_send_msg_ex $1 $2 "nd_control_req:action=modify; $3 $4 $5 $6 
" 1  2>&1`  
echo $COMM_OUTPUT  #/dev/tty is not working here
# here last argument 1 is for enabling debug
logger "OUTPUT : $COMM_OUTPUT"
exit 0
