#!/bin/bash

function Usage()
{
  echo
  echo -n "$0 >> ERROR: "
  echo $*
  echo
  echo "Usage: $0 <Testrun Number>"
  echo "Example:"
  echo "  $0 1234"
  exit -1
}


if [ $# -ne 1 ]; then
  Usage "Testrun Number argument is mandatory"
fi

psql test cavisson <<+
ANALYZE FlowPath_$1;
ANALYZE MethodTiming_$1;
ANALYZE MetaData_$1;
ANALYZE NDFunctionalGroup_$1;
ANALYZE NDAppLogs_$1;
ANALYZE NDSQL_$1;
ANALYZE NDSQLRecord_$1;
ANALYZE NDTier_$1;
ANALYZE NDAppServer_$1;
ANALYZE NDAppInstance_$1;
ANALYZE NDBCIArg_$1;
ANALYZE NDAutoSensorHotSpotThreads_$1;
ANALYZE NDHTTPHeaderMetaData_$1;
ANALYZE NDHTTPCaptureHeader_$1;
ANALYZE NDExceptionClass_$1;
ANALYZE NDExceptionThrowingClass_$1;
ANALYZE NDExceptionThrowingMethod_$1;
ANALYZE NDExceptionStackTrace_$1;
ANALYZE NDExceptionMessage_$1;
ANALYZE NDExceptionCause_$1;
ANALYZE NDExceptions_$1;
+
