#! /bin/sh
#Here we are drop indexes for ND tables
#Index will enhance database performance (indexes can be used to obtain fast access)

if [ -d $PWD/TR$1 ]; then
  BASE_DIR=$PWD
elif [ -d $NS_WDIR/logs/TR$1 ]; then
  BASE_DIR=$NS_WDIR/logs
else
  echo "Error: Test run number $1 is not a valid test run number"
  exit -1
fi

echo "ndu_drop_index: Please wait indexes will be dropped ..."
START=`date +%s`

psql test cavisson <<+

DROP INDEX IF EXISTS flow_path_ins_idx_$1;
DROP INDEX IF EXISTS flow_path_ins_start_time_idx_$1;
DROP INDEX IF EXISTS flow_path_ins_end_time_idx_$1;

DROP INDEX IF EXISTS flow_path_sign_idx_$1;
DROP INDEX IF EXISTS flow_path_status_code_idx_$1;
DROP INDEX IF EXISTS method_timing_idx_cls_$1;
DROP INDEX IF EXISTS method_timing_idx_pkg_$1;
DROP INDEX IF EXISTS nd_app_logs_idx_fpi_$1;
DROP INDEX IF EXISTS nd_app_logs_idx_sev_$1;
DROP INDEX IF EXISTS nd_app_logs_idx_dt_$1;
DROP INDEX IF EXISTS nd_app_logs_idx_fpi_sev_$1;
DROP INDEX IF EXISTS nd_sql_record_idx_$1;
DROP INDEX IF EXISTS nd_sql_record_flowpath_instance_$1;
DROP INDEX IF EXISTS nd_sql_record_sql_begin_timestamp_$1;
DROP INDEX IF EXISTS nd_sql_record_flowpath_ins_sql_begin_timestamp_$1;

DROP INDEX IF EXISTS nd_sql_record_sql_exec_time_$1;
DROP INDEX IF EXISTS nd_sql_record_sql_index_$1;
DROP INDEX IF EXISTS nd_sql_flowpath_instance_$1;
DROP INDEX IF EXISTS nd_sql_sql_index_$1;
DROP INDEX IF EXISTS nd_sql_query_type_$1;
DROP INDEX IF EXISTS nd_sql_sql_query_$1;
DROP INDEX IF EXISTS nd_as_tier_id_$1;
DROP INDEX IF EXISTS nd_as_server_id_$1;
DROP INDEX IF EXISTS nd_as_app_id_$1;
DROP INDEX IF EXISTS nd_as_thread_id_$1;
DROP INDEX IF EXISTS nd_as_start_time_$1;
DROP INDEX IF EXISTS nd_http_capture_header_fpi_$1;
DROP INDEX IF EXISTS nd_exception_fpi_$1;
DROP INDEX IF EXISTS nd_exception_class_id_$1;
DROP INDEX IF EXISTS nd_exception_throwing_class_id_$1;
DROP INDEX IF EXISTS nd_exception_throwing_method_id_$1;
DROP INDEX IF EXISTS nd_exception_cause_id_$1;
DROP INDEX IF EXISTS nd_exception_stack_trace_id_$1;
DROP INDEX IF EXISTS nd_exception_message_id_$1;

DROP INDEX IF EXISTS nd_method_timing_tierid_id_$1;
DROP INDEX IF EXISTS nd_method_timing_serverid_id_$1;
DROP INDEX IF EXISTS nd_method_timing_appid_id_$1;
DROP INDEX IF EXISTS nd_method_timing_methodid_starttime_id_$1;
DROP INDEX IF EXISTS nd_method_timing_methodid_endtime_id_$1;
DROP INDEX IF EXISTS nd_jms_flowpath_instance_$1;
+

END=`date +%s`
#echo $END
#echo $START
DIFF=`expr $END - $START`
#echo $DIFF
echo "ndu_drop_index: Deletion of indexes took $DIFF seconds"

