#!/bin/bash

usage()
{
  echo
  echo "$*"
  echo
  echo "USAGE:"
  echo "====="
  echo
  echo "$0 --testrun <value> --partition <value> [--skip_check 1]"
  echo
  echo "Where"
  echo "  --testrun and partition are both mandatory arguments"

  exit 1
}

#Function for checking whether agrument value is given or not
chk_args_of_option()
{
  if [ "X$2" == "X" ];then
    echo "Option $1 required a value."
    usage
  fi
}

chk_args()
{
  if [ "X$TRNUM" == "X" ]; then
    usage "Missing mandatory option --testrun."
  fi

  if [ "X$PARTITION" == "X" ]; then
    usage "Missing mandatory option --partition."
  fi
}

while [ "$1" != "" ];do
  case $1 in
    "--testrun")
        shift
        chk_args_of_option "--testrun" "$1"
        TRNUM=$1;;
    "--partition")
        shift
        chk_args_of_option "--partition" "$1"
        PARTITION=$1;;
    "--skip_check")
        shift
        SKIPCHK=$1;;
   --*) usage "Invalid option $1";;
    *) usage ;;
  esac
  shift
done

chk_args


if [ "X$SKIPCHK" != "X1" ];then

COUNT=`psql test cavisson <<+ |tail -3 |head -1 |sed 's/^ *//g'
SELECT COUNT (*) from
(
select 
 flowpathinstance, 
 correlationid
from 
 flowpath_${TRNUM}_${PARTITION}
where 
 correlationid like '%:%' 
 and split_part(reverse(correlationid), ':', 1) != ''
 and (split_part(reverse(correlationid), ':', 1) ~ '\D'
 or length((split_part(reverse(correlationid), ':', 1))) < 5)
) INQ
+`

if [ "X$COUNT" == "X" -o "$COUNT" == "0" ]; then
  tput setaf 1
    echo "No records found with corrid with : and not FPI in last field"
  tput sgr0
  exit 1
fi


psql test cavisson <<+
select 
 flowpathinstance, 
 correlationid
from 
 flowpath_${TRNUM}_${PARTITION}
where 
 correlationid like '%:%' 
 and split_part(reverse(correlationid), ':', 1) != ''
 and (split_part(reverse(correlationid), ':', 1) ~ '\D'
 or length((split_part(reverse(correlationid), ':', 1))) < 5)
limit 5
+

fi 

tput setaf 1

echo
echo "This script will update $COUNT rows in flowpath table for TR $TRNUM and partition $PARTITION for columns which have correlation IDs containging colon character" 

tput sgr0

if [ "X$SKIPCHK" != "X1" ];then
  echo " 	similar to as shown in the above samples"
fi
echo



read -p "Do you want to continue (y/N)?" choice
if [ "X$choice" != "Xy" -a "X$choice" != "XY" ]; then
  exit 1
fi
 

psql test cavisson <<+
update
 flowpath_${TRNUM}_${PARTITION}
set
 correlationid = correlationid || ':'
where 
 correlationid like '%:%' 
 and split_part(reverse(correlationid), ':', 1) != ''
 and (split_part(reverse(correlationid), ':', 1) ~ '\D'
 or length((split_part(reverse(correlationid), ':', 1))) < 5)
+

