#! /bin/sh

#Here we are creating indexes for tables
#Index will enhance database performance (indexes can be used to obtain fast access)

if [ -d $PWD/TR$1 ]; then
  BASE_DIR=$PWD
elif [ -d $NS_WDIR/logs/TR$1 ]; then
  BASE_DIR=$NS_WDIR/logs
else
  echo "Error: Test run number $1 is not a valid test run number"
  exit -1
fi

echo "ndu_create_index: Please wait indexes will be created ..."
START=`date +%s`

psql test cavisson <<+

CREATE INDEX flow_path_ins_idx_$1 ON FlowPath_$1 (FlowPathInstance);
CREATE INDEX flow_path_ins_start_time_idx_$1 ON FlowPath_$1 (FlowPathInstance, FlowPathBeginTimestamp);
CREATE INDEX flow_path_ins_end_time_idx_$1 ON FlowPath_$1 (FlowPathInstance, FlowPathEndTimestamp);

CREATE INDEX flow_path_sign_idx_$1 ON FlowPath_$1 (FlowPathSignature);
CREATE INDEX flow_path_status_code_idx_$1 ON FlowPath_$1 (StatusCode);
CREATE INDEX method_timing_idx_cls_$1 ON MethodTiming_$1 (MethodClassId);
CREATE INDEX method_timing_idx_pkg_$1 ON MethodTiming_$1 (MethodPackageId);
CREATE INDEX nd_app_logs_idx_fpi_$1 ON NDAppLogs_$1 (FlowPathInstance);
CREATE INDEX nd_app_logs_idx_sev_$1 ON NDAppLogs_$1 (Severity);
CREATE INDEX nd_app_logs_idx_dt_$1 ON NDAppLogs_$1 (Date);
CREATE INDEX nd_app_logs_idx_fpi_sev_$1 ON NDAppLogs_$1 (FlowPathInstance,Severity);
CREATE INDEX nd_sql_record_idx_$1 ON NDSQLRecord_$1 (FlowPathInstance,SQLIndex);
CREATE INDEX nd_sql_record_flowpath_instance_$1 ON NDSQLRecord_$1 (FlowPathInstance);
CREATE INDEX nd_sql_record_sql_begin_timestamp_$1 ON NDSQLRecord_$1 (SQLBeginTimestamp);
CREATE INDEX nd_sql_record_flowpath_ins_sql_begin_timestamp_$1 ON NDSQLRecord_$1 (FlowPathInstance, SQLBeginTimestamp);

CREATE INDEX nd_sql_record_sql_exec_time_$1 ON NDSQLRecord_$1 (SQLExecTime);
CREATE INDEX nd_sql_record_sql_index_$1 ON NDSQLRecord_$1 (SQLIndex);
CREATE INDEX nd_sql_flowpath_instance_$1 ON NDSQL_$1 (FlowPathInstance);
CREATE INDEX nd_sql_sql_index_$1 ON NDSQL_$1 (SQLIndex);
CREATE INDEX nd_sql_query_type_$1 ON NDSQL_$1 (QueryType);
CREATE INDEX nd_sql_sql_query_$1 ON NDSQL_$1 (SQLQuery);
CREATE INDEX nd_as_tier_id_$1 ON NDAutoSensorHotSpotThreads_$1 (TierID);
CREATE INDEX nd_as_server_id_$1 ON NDAutoSensorHotSpotThreads_$1 (ServerID);
CREATE INDEX nd_as_app_id_$1 ON NDAutoSensorHotSpotThreads_$1 (appID);
CREATE INDEX nd_as_thread_id_$1 ON NDAutoSensorHotSpotThreads_$1 (ThreadId);
CREATE INDEX nd_as_start_time_$1 ON NDAutoSensorHotSpotThreads_$1 (HotSpotStartTimeStamp);
CREATE INDEX nd_http_capture_header_fpi_$1 ON NDHTTPCaptureHeader_$1 (FlowpathInstance);
CREATE INDEX nd_exception_fpi_$1 ON NDExceptions_$1 (FlowPathInstance);
CREATE INDEX nd_exception_class_id_$1 ON NDExceptions_$1 (ExceptionClassID);
CREATE INDEX nd_exception_throwing_class_id_$1 ON NDExceptions_$1 (ThrowingClassID);
CREATE INDEX nd_exception_throwing_method_id_$1 ON NDExceptions_$1 (ThrowingMethodID);
CREATE INDEX nd_exception_cause_id_$1 ON NDExceptions_$1 (CauseID);
CREATE INDEX nd_exception_stack_trace_id_$1 ON NDExceptions_$1 (StackTraceID);
CREATE INDEX nd_exception_message_id_$1 ON NDExceptions_$1 (MessageID);

CREATE INDEX nd_method_timing_tierid_id_$1 ON NDMethodTiming_$1 (TierIndex);
CREATE INDEX nd_method_timing_serverid_id_$1 ON NDMethodTiming_$1 (ServerIndex);
CREATE INDEX nd_method_timing_appid_id_$1 ON NDMethodTiming_$1 (AppIndex);
CREATE INDEX nd_method_timing_methodid_starttime_id_$1 ON NDMethodTiming_$1 (MethodId,StartTime);
CREATE INDEX nd_method_timing_methodid_endtime_id_$1 ON NDMethodTiming_$1 (MethodId,EndTime);
CREATE INDEX nd_jms_flowpath_instance_$1 ON NDJMS_$1 (FlowPathInstance);

CREATE INDEX nd_bci_arg_flowpath_instance_$1 ON NDBCIArg_$1 (FlowPathInstance);
CREATE INDEX nd_bci_arg_bci_arg_id$1 ON NDBCIArg_$1 (BCIArgID);
CREATE INDEX nd_bci_arg_method_id$1 ON NDBCIArg_$1 (MethodID);
CREATE INDEX nd_bci_arg_tier_id$1 ON NDBCIArg_$1 (TierID);
CREATE INDEX nd_bci_arg_server_id$1 ON NDBCIArg_$1 (ServerID);
CREATE INDEX nd_bci_arg_app_id$1 ON NDBCIArg_$1 (AppID);
+

END=`date +%s`
#echo $END
#echo $START
DIFF=`expr $END - $START`
#echo $DIFF
echo "ndu_create_index: Creating indexes took $DIFF seconds"


