#! /bin/sh

usage()
{
  echo $*
  echo "Usage: neu_drop_partition_table <Test Run Number> <Partition Name> "
  echo "Example:"
  echo "  neu_drop_partition_table 1234 201402201000 "
  exit -1
}

if [ $# -lt 2 ]; then
  usage "INVALID ARGUMENTS"
fi

count=0
if [ -d $PWD/TR$1 ]; then
  BASE_DIR=$PWD
elif [ -d $NS_WDIR/logs/TR$1 ]; then
  BASE_DIR=$NS_WDIR/logs
else
  usage "Error: Test run number $1 is not a valid test run number"
  exit -1
fi

echo "neu_drop_partition_table: Please wait table will be dropped ..."
START=`date +%s`

if [ "X$3" == "X" -o "X$3" == "Xall" -o "X$3" == "XALL" ];then
  psql test cavisson <<+
  drop table if exists SessionRecord_$1_$2;
  drop table if exists TransactionRecord_$1_$2;
  drop table if exists PageRecord_$1_$2;
  drop table if exists URLRecord_$1_$2;
  drop table if exists TransPageRecord_$1_$2;
  drop table if exists PageDumpRecord_$1_$2;
  drop table if exists pagerbudetailrecord_$1_$2;
  drop table if exists AlertHistory_$1_$2;
  drop table if exists AlertActions_$1_$2;
  drop table if exists mssqlreport_$1_$2;
+
  if [ -f $NS_WDIR/logs/TR$1/common_files/.oracle_sql_report ];then
    psql test cavisson <<+
      drop table if exists orlStatsSQLIDTable_$1_$2 ;
      drop table if exists orlStatsSnapTable_$1_$2 ;
      drop table if exists orlStatsSQLStmtOrdByElapsedTime_$1_$2;
      drop table if exists orlStatsSQLStmtOrdByCPUTime_$1_$2;
      drop table if exists orlStatsSQLStmtOrdByUsrIOTime_$1_$2;
      drop table if exists orlStatsSQLStmtOrdByGets_$1_$2;
      drop table if exists orlStatsSQLStmtOrdByReads_$1_$2;
      drop table if exists orlStatsSQLStmtOrdByPhyReadsUnopt_$1_$2;
      drop table if exists orlStatsSQLStmtOrdByExec_$1_$2;
      drop table if exists orlStatsSQLStmtOrdByParseCalls_$1_$2;
      drop table if exists orlStatsSQLStmtOrdBySharableMemory_$1_$2;
      drop table if exists orlStatsSQLStmtOrdByVersionCount_$1_$2;
      drop table if exists orlStatsSQLStmtOrdByClusterWaitTime_$1_$2;
+
  fi

else
  # Case to drop a particular partition table based on the given partition name.
  NS_PARTITION_ARRAY=("sessionrecord_" "transactionrecord_" "transpagerecord_" "pagerecord_" "urlrecord_" "pagedumprecord_" "pagerbudetailrecord_" "alertactions_" "alerthistory_" "mssqlreport_")
  NS_CSV_NAMES=("src.csv" "trc.csv" "tprc.csv" "prc.csv" "urc.csv" "page_dump.csv" "PageRBUDetailRecord.csv" "alertAction.csv" "alertHistory.csv" "MSSQLReport.csv")  

  while [ $count -le ${#NS_CSV_NAMES[@]} ] ; do
    if [ "X${NS_CSV_NAMES[$count]}" == "X$3" ] ; then
      NS_PARTITION_TABLE_NAME=`echo ${NS_PARTITION_ARRAY[$count]}`"$1_$2"
      psql test cavisson <<+
      drop table if exists $NS_PARTITION_TABLE_NAME;
+
    fi
  count=`expr $count + 1`
  done
fi 
END=`date +%s`
DIFF=`expr $END - $START`
echo "neu_drop_partition_table: Deletion of table took $DIFF seconds"

