#! /bin/bash
####################################################
#  File: nii_cat_page_dump_files
#
#  Author: Manpreet
#
#  Date: 8 Oct 2013
#
#  Synopsis: 
#      This command is used for Netcloud testrun.
#
#      This command is used to concatenate the contents of
#      the following page dump files from Generator TR directories to 
#      Controller TR directory
#      log
#      sess_status_log
#      And move url_request/response/response_body files from generator TRs
#      
#      Page dump feature redesign: 
#      1. log ans sess_status_log files are not created 
#      2. url request response files path has been change (logs/TRxx/ns_logs/req_rep) 
#      3. Copy all docs files to controller directory (logs/TRxx/page_dump/docs)
#
#  Usage: nii_cat_page_dump_files <controller_trnum>
#
####################################################

if [ ! -f $NS_WDIR/logs/TR$1/NetCloud/NetCloud.data ]; then
  echo ERROR: File not found $NS_WDIR/logs/TR$1/NetCloud/NetCloud.data
  exit 1
fi

NII_GEN_DETAIL_FILE=$NS_WDIR/logs/TR$1/NetCloud/NetCloud.data
ARR_GEN_TRNUM=(`grep  ^NETCLOUD_GENERATOR_TRUN $NII_GEN_DETAIL_FILE | cut -d "|" -f1  |cut -d ' ' -f2`)
ARR_GEN_NAME=(`grep  ^NETCLOUD_GENERATOR_TRUN $NII_GEN_DETAIL_FILE | cut -d "|" -f2  |cut -d ' ' -f2`)

#> $NS_WDIR/logs/TR$1/log
#> $NS_WDIR/logs/TR$1/sess_status_log

for ((i = 0; i < ${#ARR_GEN_TRNUM[@]}; i++))
do
  #cat $NS_WDIR/logs/TR$1/NetCloud/${ARR_GEN_NAME[$i]}/TR${ARR_GEN_TRNUM[$i]}/log >> $NS_WDIR/logs/TR$1/log
  #cat $NS_WDIR/logs/TR$1/NetCloud/${ARR_GEN_NAME[$i]}/TR${ARR_GEN_TRNUM[$i]}/sess_status_log >> $NS_WDIR/logs/TR$1/sess_status_log
  #Move all url_req, url_rep and url_rep_body files to controller directory
  find $NS_WDIR/logs/TR$1/NetCloud/${ARR_GEN_NAME[$i]}/TR${ARR_GEN_TRNUM[$i]}/ns_logs/req_rep/ -name "url_re*" |xargs -i mv {} $NS_WDIR/logs/TR$1/ns_logs/req_rep/
  #Move all docs files to controller directory
  find $NS_WDIR/logs/TR$1/NetCloud/${ARR_GEN_NAME[$i]}/TR${ARR_GEN_TRNUM[$i]}/page_dump/docs/ -name "*.orig" |xargs -i mv {} $NS_WDIR/logs/TR$1/page_dump/docs/
done
