#!/bin/sh
# Name      : nsi_get_url
# Author    : Jyoti 
# Purpsose  : To show the url path, size and last modification date & time from real/control 
#
# Usage     :  
# - h get host name
# - t path of url from real/control 

usage ()
{
  echo "$1"
  echo "Usage: nsi_get_url -h <host name> -t <directory>"
  exit 1
}

# Parse and validate arguments
  while getopts :h:t: arg
  do
    case $arg in
      h) HOST_NAME=$OPTARG;;
      t) URL_PATH=$OPTARG;;
      ?) usage "Bad argument";;
    esac
  done

if [ $URL_PATH == "real" ]; then
  url_path=$HPD_ROOT/real/$HOST_NAME
else
  url_path=$HPD_ROOT/control/$HOST_NAME
fi

#Here we are checking host present or not
if [ ! -d $url_path ];then
  echo "Host $HOST_NAME not found"
  exit 1
fi

#echo $url_path
#Storing original path
org_path=`pwd`
#Changing path to given directory
cd $url_path

#Find all URLs with name, size and last modification date and time
find . -type f -printf  '%p|%s|%TD %TT\n'
#`expr substr $INPUT 5 ${#INPUT}`
#Restoring original path
cd $org_path

exit 0
