#!/bin/sh

PFLAG=0;
SFLAG=0;
#TAR_SCRIPT=`find $NS_WDIR/include -path "*.tar"`
TAR_SCRIPT=$NS_WDIR/include/ReplayDbScript.tar.gz
SYS_TX_ERROR_CODE_FILE=$NSWDIR/sys/tx_error_codes
NS_TA_DIR=""

display_help_and_exit(){
  echo "Usage: ns_db_replay_create_script -p <Project/Subproject -s scenario -w <workspace_name>/<profile_name>"
  echo "Where " 
  echo "  -p provides path to copy script"
  echo "  -s will be name of script"
  echo "  -w : To provide <workspace>/<profile>. Default values will be used, if not provided"
  exit 1
}

#This method check whether project/subproject exists or not 
check_and_copy_script(){

  SCRIPT_PATH=$NS_TA_DIR/scripts

  if [ ! -d $SCRIPT_PATH ];then
    echo "'$PROJ_SUB_PROJ/scripts' does not exists in $NS_TA_DIR directory"
    exit 1
  else
    cd $SCRIPT_PATH
    #mkdir -p $SCRIPT_NAME 
    #tar -xf $TAR_SCRIPT -C $SCRIPT_PATH/$PROJ_SUB_PROJ/$SCRIPT_NAME --strip-components 1 
    tar -xzf $TAR_SCRIPT
    rm -rf $SCRIPT_NAME 
    mv __Java_Scr $SCRIPT_NAME
    
    # Change class name  
    cd $SCRIPT_PATH/$SCRIPT_NAME
    sed -i 's/package com.cavisson.scripts.__Java_Scr/package com.cavisson.scripts.'$SCRIPT_NAME'/g' *.java
      
  fi
}

check_mandatory_options()
{
   if [ $PFLAG -eq 0 ]; then 
     echo "ns_db_replay -p option is mandatory"
     display_help_and_exit
   fi

   if [ $SFLAG -eq 0 ]; then 
     echo "ns_db_replay -s option is  mandatory"
     display_help_and_exit
   fi
}

#This method to check format of project and subproject, it should be "project/subproject"
check_format_of_proj_subproj()
{
    PROJECT=`echo $PROJ_SUB_PROJ | egrep "/" | cut -d'/' -f1`
    SUB_PROJECT=`echo $PROJ_SUB_PROJ | egrep "/" | cut -d'/' -f2`
    if [ "$PROJECT" == "" -o "$SUB_PROJECT" == "" ];then
      err_msgout "-p <Project/Subproject> is not given in proper format."
      exit -1
    fi
}

update_sys_tx_error_codes()
{
  echo "93 JNVM_QUERY_FAILURE\n94 DATABASE_QUERY_FAILURE\n" >> $SYS_TX_ERROR_CODE_FILE
}

if [[ $# -eq 0 ]] ; then
  display_help_and_exit 
fi

while getopts p:s:? opt
do
 case $opt in 
      p)
      PROJ_SUB_PROJ="$OPTARG";
      PFLAG=`expr $PFLAG + 1`
      check_format_of_proj_subproj $PROJ_SUB_PROJ;
      ;;
      s)
      SCRIPT_NAME="$OPTARG";
      SFLAG=`expr $SFLAG + 1`;;
      w)
      WORK_PROFILE="$OPTARG";;
      ?) display_help_and_exit ;; 
      *) display_help_and_exit  ;; 
 esac
done

check_mandatory_options
#************************************************************************************************
#set absolute test assets path
NS_TA_DIR=`nsi_get_work_space_path.sh $WORK_PROFILE $PROJ_SUB_PROJ`
#************************************************************************************************
check_and_copy_script
update_sys_tx_error_codes
exit 0;
