/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "ns_nvm_msg_def.pb-c.h"
void   ns_msg1__int__init
                     (NsMsg1Int         *message)
{
  static NsMsg1Int init_value = NS_MSG1__INT__INIT;
  *message = init_value;
}
size_t ns_msg1__int__get_packed_size
                     (const NsMsg1Int *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg1__int__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg1__int__pack
                     (const NsMsg1Int *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg1__int__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg1__int__pack_to_buffer
                     (const NsMsg1Int *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg1__int__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg1Int *
       ns_msg1__int__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg1Int *)
     protobuf_c_message_unpack (&ns_msg1__int__descriptor,
                                allocator, len, data);
}
void   ns_msg1__int__free_unpacked
                     (NsMsg1Int *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg1__int__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg1__uint__init
                     (NsMsg1UInt         *message)
{
  static NsMsg1UInt init_value = NS_MSG1__UINT__INIT;
  *message = init_value;
}
size_t ns_msg1__uint__get_packed_size
                     (const NsMsg1UInt *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg1__uint__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg1__uint__pack
                     (const NsMsg1UInt *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg1__uint__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg1__uint__pack_to_buffer
                     (const NsMsg1UInt *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg1__uint__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg1UInt *
       ns_msg1__uint__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg1UInt *)
     protobuf_c_message_unpack (&ns_msg1__uint__descriptor,
                                allocator, len, data);
}
void   ns_msg1__uint__free_unpacked
                     (NsMsg1UInt *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg1__uint__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg1__str__init
                     (NsMsg1Str         *message)
{
  static NsMsg1Str init_value = NS_MSG1__STR__INIT;
  *message = init_value;
}
size_t ns_msg1__str__get_packed_size
                     (const NsMsg1Str *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg1__str__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg1__str__pack
                     (const NsMsg1Str *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg1__str__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg1__str__pack_to_buffer
                     (const NsMsg1Str *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg1__str__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg1Str *
       ns_msg1__str__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg1Str *)
     protobuf_c_message_unpack (&ns_msg1__str__descriptor,
                                allocator, len, data);
}
void   ns_msg1__str__free_unpacked
                     (NsMsg1Str *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg1__str__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg1__double__init
                     (NsMsg1Double         *message)
{
  static NsMsg1Double init_value = NS_MSG1__DOUBLE__INIT;
  *message = init_value;
}
size_t ns_msg1__double__get_packed_size
                     (const NsMsg1Double *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg1__double__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg1__double__pack
                     (const NsMsg1Double *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg1__double__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg1__double__pack_to_buffer
                     (const NsMsg1Double *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg1__double__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg1Double *
       ns_msg1__double__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg1Double *)
     protobuf_c_message_unpack (&ns_msg1__double__descriptor,
                                allocator, len, data);
}
void   ns_msg1__double__free_unpacked
                     (NsMsg1Double *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg1__double__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg1__long__init
                     (NsMsg1Long         *message)
{
  static NsMsg1Long init_value = NS_MSG1__LONG__INIT;
  *message = init_value;
}
size_t ns_msg1__long__get_packed_size
                     (const NsMsg1Long *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg1__long__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg1__long__pack
                     (const NsMsg1Long *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg1__long__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg1__long__pack_to_buffer
                     (const NsMsg1Long *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg1__long__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg1Long *
       ns_msg1__long__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg1Long *)
     protobuf_c_message_unpack (&ns_msg1__long__descriptor,
                                allocator, len, data);
}
void   ns_msg1__long__free_unpacked
                     (NsMsg1Long *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg1__long__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg2__is__init
                     (NsMsg2IS         *message)
{
  static NsMsg2IS init_value = NS_MSG2__IS__INIT;
  *message = init_value;
}
size_t ns_msg2__is__get_packed_size
                     (const NsMsg2IS *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__is__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg2__is__pack
                     (const NsMsg2IS *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__is__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg2__is__pack_to_buffer
                     (const NsMsg2IS *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__is__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg2IS *
       ns_msg2__is__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg2IS *)
     protobuf_c_message_unpack (&ns_msg2__is__descriptor,
                                allocator, len, data);
}
void   ns_msg2__is__free_unpacked
                     (NsMsg2IS *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__is__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg2__si__init
                     (NsMsg2SI         *message)
{
  static NsMsg2SI init_value = NS_MSG2__SI__INIT;
  *message = init_value;
}
size_t ns_msg2__si__get_packed_size
                     (const NsMsg2SI *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__si__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg2__si__pack
                     (const NsMsg2SI *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__si__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg2__si__pack_to_buffer
                     (const NsMsg2SI *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__si__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg2SI *
       ns_msg2__si__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg2SI *)
     protobuf_c_message_unpack (&ns_msg2__si__descriptor,
                                allocator, len, data);
}
void   ns_msg2__si__free_unpacked
                     (NsMsg2SI *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__si__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg2__ii__init
                     (NsMsg2II         *message)
{
  static NsMsg2II init_value = NS_MSG2__II__INIT;
  *message = init_value;
}
size_t ns_msg2__ii__get_packed_size
                     (const NsMsg2II *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__ii__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg2__ii__pack
                     (const NsMsg2II *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__ii__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg2__ii__pack_to_buffer
                     (const NsMsg2II *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__ii__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg2II *
       ns_msg2__ii__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg2II *)
     protobuf_c_message_unpack (&ns_msg2__ii__descriptor,
                                allocator, len, data);
}
void   ns_msg2__ii__free_unpacked
                     (NsMsg2II *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__ii__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg2__ss__init
                     (NsMsg2SS         *message)
{
  static NsMsg2SS init_value = NS_MSG2__SS__INIT;
  *message = init_value;
}
size_t ns_msg2__ss__get_packed_size
                     (const NsMsg2SS *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__ss__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg2__ss__pack
                     (const NsMsg2SS *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__ss__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg2__ss__pack_to_buffer
                     (const NsMsg2SS *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__ss__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg2SS *
       ns_msg2__ss__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg2SS *)
     protobuf_c_message_unpack (&ns_msg2__ss__descriptor,
                                allocator, len, data);
}
void   ns_msg2__ss__free_unpacked
                     (NsMsg2SS *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__ss__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg2__sd__init
                     (NsMsg2SD         *message)
{
  static NsMsg2SD init_value = NS_MSG2__SD__INIT;
  *message = init_value;
}
size_t ns_msg2__sd__get_packed_size
                     (const NsMsg2SD *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__sd__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg2__sd__pack
                     (const NsMsg2SD *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__sd__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg2__sd__pack_to_buffer
                     (const NsMsg2SD *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__sd__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg2SD *
       ns_msg2__sd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg2SD *)
     protobuf_c_message_unpack (&ns_msg2__sd__descriptor,
                                allocator, len, data);
}
void   ns_msg2__sd__free_unpacked
                     (NsMsg2SD *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__sd__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg2__sui__init
                     (NsMsg2SUI         *message)
{
  static NsMsg2SUI init_value = NS_MSG2__SUI__INIT;
  *message = init_value;
}
size_t ns_msg2__sui__get_packed_size
                     (const NsMsg2SUI *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__sui__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg2__sui__pack
                     (const NsMsg2SUI *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__sui__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg2__sui__pack_to_buffer
                     (const NsMsg2SUI *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__sui__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg2SUI *
       ns_msg2__sui__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg2SUI *)
     protobuf_c_message_unpack (&ns_msg2__sui__descriptor,
                                allocator, len, data);
}
void   ns_msg2__sui__free_unpacked
                     (NsMsg2SUI *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg2__sui__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg3__iii__init
                     (NsMsg3III         *message)
{
  static NsMsg3III init_value = NS_MSG3__III__INIT;
  *message = init_value;
}
size_t ns_msg3__iii__get_packed_size
                     (const NsMsg3III *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__iii__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg3__iii__pack
                     (const NsMsg3III *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__iii__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg3__iii__pack_to_buffer
                     (const NsMsg3III *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__iii__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg3III *
       ns_msg3__iii__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg3III *)
     protobuf_c_message_unpack (&ns_msg3__iii__descriptor,
                                allocator, len, data);
}
void   ns_msg3__iii__free_unpacked
                     (NsMsg3III *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__iii__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg3__iis__init
                     (NsMsg3IIS         *message)
{
  static NsMsg3IIS init_value = NS_MSG3__IIS__INIT;
  *message = init_value;
}
size_t ns_msg3__iis__get_packed_size
                     (const NsMsg3IIS *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__iis__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg3__iis__pack
                     (const NsMsg3IIS *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__iis__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg3__iis__pack_to_buffer
                     (const NsMsg3IIS *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__iis__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg3IIS *
       ns_msg3__iis__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg3IIS *)
     protobuf_c_message_unpack (&ns_msg3__iis__descriptor,
                                allocator, len, data);
}
void   ns_msg3__iis__free_unpacked
                     (NsMsg3IIS *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__iis__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg3__isi__init
                     (NsMsg3ISI         *message)
{
  static NsMsg3ISI init_value = NS_MSG3__ISI__INIT;
  *message = init_value;
}
size_t ns_msg3__isi__get_packed_size
                     (const NsMsg3ISI *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__isi__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg3__isi__pack
                     (const NsMsg3ISI *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__isi__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg3__isi__pack_to_buffer
                     (const NsMsg3ISI *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__isi__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg3ISI *
       ns_msg3__isi__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg3ISI *)
     protobuf_c_message_unpack (&ns_msg3__isi__descriptor,
                                allocator, len, data);
}
void   ns_msg3__isi__free_unpacked
                     (NsMsg3ISI *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__isi__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg3__iss__init
                     (NsMsg3ISS         *message)
{
  static NsMsg3ISS init_value = NS_MSG3__ISS__INIT;
  *message = init_value;
}
size_t ns_msg3__iss__get_packed_size
                     (const NsMsg3ISS *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__iss__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg3__iss__pack
                     (const NsMsg3ISS *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__iss__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg3__iss__pack_to_buffer
                     (const NsMsg3ISS *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__iss__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg3ISS *
       ns_msg3__iss__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg3ISS *)
     protobuf_c_message_unpack (&ns_msg3__iss__descriptor,
                                allocator, len, data);
}
void   ns_msg3__iss__free_unpacked
                     (NsMsg3ISS *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__iss__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg3__sii__init
                     (NsMsg3SII         *message)
{
  static NsMsg3SII init_value = NS_MSG3__SII__INIT;
  *message = init_value;
}
size_t ns_msg3__sii__get_packed_size
                     (const NsMsg3SII *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__sii__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg3__sii__pack
                     (const NsMsg3SII *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__sii__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg3__sii__pack_to_buffer
                     (const NsMsg3SII *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__sii__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg3SII *
       ns_msg3__sii__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg3SII *)
     protobuf_c_message_unpack (&ns_msg3__sii__descriptor,
                                allocator, len, data);
}
void   ns_msg3__sii__free_unpacked
                     (NsMsg3SII *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__sii__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg3__sis__init
                     (NsMsg3SIS         *message)
{
  static NsMsg3SIS init_value = NS_MSG3__SIS__INIT;
  *message = init_value;
}
size_t ns_msg3__sis__get_packed_size
                     (const NsMsg3SIS *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__sis__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg3__sis__pack
                     (const NsMsg3SIS *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__sis__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg3__sis__pack_to_buffer
                     (const NsMsg3SIS *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__sis__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg3SIS *
       ns_msg3__sis__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg3SIS *)
     protobuf_c_message_unpack (&ns_msg3__sis__descriptor,
                                allocator, len, data);
}
void   ns_msg3__sis__free_unpacked
                     (NsMsg3SIS *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__sis__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg3__ssi__init
                     (NsMsg3SSI         *message)
{
  static NsMsg3SSI init_value = NS_MSG3__SSI__INIT;
  *message = init_value;
}
size_t ns_msg3__ssi__get_packed_size
                     (const NsMsg3SSI *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__ssi__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg3__ssi__pack
                     (const NsMsg3SSI *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__ssi__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg3__ssi__pack_to_buffer
                     (const NsMsg3SSI *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__ssi__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg3SSI *
       ns_msg3__ssi__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg3SSI *)
     protobuf_c_message_unpack (&ns_msg3__ssi__descriptor,
                                allocator, len, data);
}
void   ns_msg3__ssi__free_unpacked
                     (NsMsg3SSI *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__ssi__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg3__sss__init
                     (NsMsg3SSS         *message)
{
  static NsMsg3SSS init_value = NS_MSG3__SSS__INIT;
  *message = init_value;
}
size_t ns_msg3__sss__get_packed_size
                     (const NsMsg3SSS *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__sss__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg3__sss__pack
                     (const NsMsg3SSS *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__sss__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg3__sss__pack_to_buffer
                     (const NsMsg3SSS *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__sss__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg3SSS *
       ns_msg3__sss__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg3SSS *)
     protobuf_c_message_unpack (&ns_msg3__sss__descriptor,
                                allocator, len, data);
}
void   ns_msg3__sss__free_unpacked
                     (NsMsg3SSS *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__sss__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg3__iid__init
                     (NsMsg3IID         *message)
{
  static NsMsg3IID init_value = NS_MSG3__IID__INIT;
  *message = init_value;
}
size_t ns_msg3__iid__get_packed_size
                     (const NsMsg3IID *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__iid__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg3__iid__pack
                     (const NsMsg3IID *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__iid__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg3__iid__pack_to_buffer
                     (const NsMsg3IID *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__iid__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg3IID *
       ns_msg3__iid__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg3IID *)
     protobuf_c_message_unpack (&ns_msg3__iid__descriptor,
                                allocator, len, data);
}
void   ns_msg3__iid__free_unpacked
                     (NsMsg3IID *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg3__iid__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg4__ssss__init
                     (NsMsg4SSSS         *message)
{
  static NsMsg4SSSS init_value = NS_MSG4__SSSS__INIT;
  *message = init_value;
}
size_t ns_msg4__ssss__get_packed_size
                     (const NsMsg4SSSS *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg4__ssss__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg4__ssss__pack
                     (const NsMsg4SSSS *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg4__ssss__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg4__ssss__pack_to_buffer
                     (const NsMsg4SSSS *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg4__ssss__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg4SSSS *
       ns_msg4__ssss__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg4SSSS *)
     protobuf_c_message_unpack (&ns_msg4__ssss__descriptor,
                                allocator, len, data);
}
void   ns_msg4__ssss__free_unpacked
                     (NsMsg4SSSS *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg4__ssss__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg4__sssi__init
                     (NsMsg4SSSI         *message)
{
  static NsMsg4SSSI init_value = NS_MSG4__SSSI__INIT;
  *message = init_value;
}
size_t ns_msg4__sssi__get_packed_size
                     (const NsMsg4SSSI *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg4__sssi__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg4__sssi__pack
                     (const NsMsg4SSSI *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg4__sssi__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg4__sssi__pack_to_buffer
                     (const NsMsg4SSSI *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg4__sssi__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg4SSSI *
       ns_msg4__sssi__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg4SSSI *)
     protobuf_c_message_unpack (&ns_msg4__sssi__descriptor,
                                allocator, len, data);
}
void   ns_msg4__sssi__free_unpacked
                     (NsMsg4SSSI *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg4__sssi__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg__form_api__init
                     (NsMsgFormApi         *message)
{
  static NsMsgFormApi init_value = NS_MSG__FORM_API__INIT;
  *message = init_value;
}
size_t ns_msg__form_api__get_packed_size
                     (const NsMsgFormApi *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg__form_api__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg__form_api__pack
                     (const NsMsgFormApi *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg__form_api__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg__form_api__pack_to_buffer
                     (const NsMsgFormApi *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg__form_api__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsgFormApi *
       ns_msg__form_api__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsgFormApi *)
     protobuf_c_message_unpack (&ns_msg__form_api__descriptor,
                                allocator, len, data);
}
void   ns_msg__form_api__free_unpacked
                     (NsMsgFormApi *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg__form_api__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg__start_user__init
                     (NsMsgStartUser         *message)
{
  static NsMsgStartUser init_value = NS_MSG__START_USER__INIT;
  *message = init_value;
}
size_t ns_msg__start_user__get_packed_size
                     (const NsMsgStartUser *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg__start_user__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg__start_user__pack
                     (const NsMsgStartUser *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg__start_user__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg__start_user__pack_to_buffer
                     (const NsMsgStartUser *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg__start_user__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsgStartUser *
       ns_msg__start_user__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsgStartUser *)
     protobuf_c_message_unpack (&ns_msg__start_user__descriptor,
                                allocator, len, data);
}
void   ns_msg__start_user__free_unpacked
                     (NsMsgStartUser *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg__start_user__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg9__ssissssss__init
                     (NsMsg9SSISSSSSS         *message)
{
  static NsMsg9SSISSSSSS init_value = NS_MSG9__SSISSSSSS__INIT;
  *message = init_value;
}
size_t ns_msg9__ssissssss__get_packed_size
                     (const NsMsg9SSISSSSSS *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg9__ssissssss__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg9__ssissssss__pack
                     (const NsMsg9SSISSSSSS *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg9__ssissssss__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg9__ssissssss__pack_to_buffer
                     (const NsMsg9SSISSSSSS *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg9__ssissssss__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg9SSISSSSSS *
       ns_msg9__ssissssss__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg9SSISSSSSS *)
     protobuf_c_message_unpack (&ns_msg9__ssissssss__descriptor,
                                allocator, len, data);
}
void   ns_msg9__ssissssss__free_unpacked
                     (NsMsg9SSISSSSSS *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg9__ssissssss__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ns_msg9__isisssiii__init
                     (NsMsg9ISISSSIII         *message)
{
  static NsMsg9ISISSSIII init_value = NS_MSG9__ISISSSIII__INIT;
  *message = init_value;
}
size_t ns_msg9__isisssiii__get_packed_size
                     (const NsMsg9ISISSSIII *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg9__isisssiii__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ns_msg9__isisssiii__pack
                     (const NsMsg9ISISSSIII *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg9__isisssiii__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ns_msg9__isisssiii__pack_to_buffer
                     (const NsMsg9ISISSSIII *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg9__isisssiii__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NsMsg9ISISSSIII *
       ns_msg9__isisssiii__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NsMsg9ISISSSIII *)
     protobuf_c_message_unpack (&ns_msg9__isisssiii__descriptor,
                                allocator, len, data);
}
void   ns_msg9__isisssiii__free_unpacked
                     (NsMsg9ISISSSIII *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ns_msg9__isisssiii__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ns_msg1__int__field_descriptors[1] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg1Int, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg1__int__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
};
static const ProtobufCIntRange ns_msg1__int__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ns_msg1__int__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg1_Int",
  "NsMsg1Int",
  "NsMsg1Int",
  "",
  sizeof(NsMsg1Int),
  1,
  ns_msg1__int__field_descriptors,
  ns_msg1__int__field_indices_by_name,
  1,  ns_msg1__int__number_ranges,
  (ProtobufCMessageInit) ns_msg1__int__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg1__uint__field_descriptors[1] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg1UInt, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg1__uint__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
};
static const ProtobufCIntRange ns_msg1__uint__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ns_msg1__uint__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg1_UInt",
  "NsMsg1UInt",
  "NsMsg1UInt",
  "",
  sizeof(NsMsg1UInt),
  1,
  ns_msg1__uint__field_descriptors,
  ns_msg1__uint__field_indices_by_name,
  1,  ns_msg1__uint__number_ranges,
  (ProtobufCMessageInit) ns_msg1__uint__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg1__str__field_descriptors[1] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg1Str, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg1__str__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
};
static const ProtobufCIntRange ns_msg1__str__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ns_msg1__str__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg1_Str",
  "NsMsg1Str",
  "NsMsg1Str",
  "",
  sizeof(NsMsg1Str),
  1,
  ns_msg1__str__field_descriptors,
  ns_msg1__str__field_indices_by_name,
  1,  ns_msg1__str__number_ranges,
  (ProtobufCMessageInit) ns_msg1__str__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg1__double__field_descriptors[1] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg1Double, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg1__double__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
};
static const ProtobufCIntRange ns_msg1__double__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ns_msg1__double__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg1_Double",
  "NsMsg1Double",
  "NsMsg1Double",
  "",
  sizeof(NsMsg1Double),
  1,
  ns_msg1__double__field_descriptors,
  ns_msg1__double__field_indices_by_name,
  1,  ns_msg1__double__number_ranges,
  (ProtobufCMessageInit) ns_msg1__double__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg1__long__field_descriptors[1] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg1Long, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg1__long__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
};
static const ProtobufCIntRange ns_msg1__long__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ns_msg1__long__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg1_Long",
  "NsMsg1Long",
  "NsMsg1Long",
  "",
  sizeof(NsMsg1Long),
  1,
  ns_msg1__long__field_descriptors,
  ns_msg1__long__field_indices_by_name,
  1,  ns_msg1__long__number_ranges,
  (ProtobufCMessageInit) ns_msg1__long__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg2__is__field_descriptors[2] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg2IS, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg2IS, field2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg2__is__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
  1,   /* field[1] = field2 */
};
static const ProtobufCIntRange ns_msg2__is__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ns_msg2__is__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg2_IS",
  "NsMsg2IS",
  "NsMsg2IS",
  "",
  sizeof(NsMsg2IS),
  2,
  ns_msg2__is__field_descriptors,
  ns_msg2__is__field_indices_by_name,
  1,  ns_msg2__is__number_ranges,
  (ProtobufCMessageInit) ns_msg2__is__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg2__si__field_descriptors[2] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg2SI, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg2SI, field2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg2__si__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
  1,   /* field[1] = field2 */
};
static const ProtobufCIntRange ns_msg2__si__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ns_msg2__si__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg2_SI",
  "NsMsg2SI",
  "NsMsg2SI",
  "",
  sizeof(NsMsg2SI),
  2,
  ns_msg2__si__field_descriptors,
  ns_msg2__si__field_indices_by_name,
  1,  ns_msg2__si__number_ranges,
  (ProtobufCMessageInit) ns_msg2__si__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg2__ii__field_descriptors[2] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg2II, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg2II, field2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg2__ii__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
  1,   /* field[1] = field2 */
};
static const ProtobufCIntRange ns_msg2__ii__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ns_msg2__ii__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg2_II",
  "NsMsg2II",
  "NsMsg2II",
  "",
  sizeof(NsMsg2II),
  2,
  ns_msg2__ii__field_descriptors,
  ns_msg2__ii__field_indices_by_name,
  1,  ns_msg2__ii__number_ranges,
  (ProtobufCMessageInit) ns_msg2__ii__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg2__ss__field_descriptors[2] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg2SS, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg2SS, field2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg2__ss__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
  1,   /* field[1] = field2 */
};
static const ProtobufCIntRange ns_msg2__ss__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ns_msg2__ss__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg2_SS",
  "NsMsg2SS",
  "NsMsg2SS",
  "",
  sizeof(NsMsg2SS),
  2,
  ns_msg2__ss__field_descriptors,
  ns_msg2__ss__field_indices_by_name,
  1,  ns_msg2__ss__number_ranges,
  (ProtobufCMessageInit) ns_msg2__ss__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg2__sd__field_descriptors[2] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg2SD, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg2SD, field2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg2__sd__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
  1,   /* field[1] = field2 */
};
static const ProtobufCIntRange ns_msg2__sd__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ns_msg2__sd__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg2_SD",
  "NsMsg2SD",
  "NsMsg2SD",
  "",
  sizeof(NsMsg2SD),
  2,
  ns_msg2__sd__field_descriptors,
  ns_msg2__sd__field_indices_by_name,
  1,  ns_msg2__sd__number_ranges,
  (ProtobufCMessageInit) ns_msg2__sd__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg2__sui__field_descriptors[2] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg2SUI, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg2SUI, field2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg2__sui__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
  1,   /* field[1] = field2 */
};
static const ProtobufCIntRange ns_msg2__sui__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ns_msg2__sui__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg2_SUI",
  "NsMsg2SUI",
  "NsMsg2SUI",
  "",
  sizeof(NsMsg2SUI),
  2,
  ns_msg2__sui__field_descriptors,
  ns_msg2__sui__field_indices_by_name,
  1,  ns_msg2__sui__number_ranges,
  (ProtobufCMessageInit) ns_msg2__sui__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg3__iii__field_descriptors[3] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3III, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3III, field2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field3",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3III, field3),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg3__iii__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
  1,   /* field[1] = field2 */
  2,   /* field[2] = field3 */
};
static const ProtobufCIntRange ns_msg3__iii__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ns_msg3__iii__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg3_III",
  "NsMsg3III",
  "NsMsg3III",
  "",
  sizeof(NsMsg3III),
  3,
  ns_msg3__iii__field_descriptors,
  ns_msg3__iii__field_indices_by_name,
  1,  ns_msg3__iii__number_ranges,
  (ProtobufCMessageInit) ns_msg3__iii__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg3__iis__field_descriptors[3] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3IIS, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3IIS, field2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field3",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3IIS, field3),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg3__iis__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
  1,   /* field[1] = field2 */
  2,   /* field[2] = field3 */
};
static const ProtobufCIntRange ns_msg3__iis__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ns_msg3__iis__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg3_IIS",
  "NsMsg3IIS",
  "NsMsg3IIS",
  "",
  sizeof(NsMsg3IIS),
  3,
  ns_msg3__iis__field_descriptors,
  ns_msg3__iis__field_indices_by_name,
  1,  ns_msg3__iis__number_ranges,
  (ProtobufCMessageInit) ns_msg3__iis__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg3__isi__field_descriptors[3] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3ISI, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3ISI, field2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field3",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3ISI, field3),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg3__isi__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
  1,   /* field[1] = field2 */
  2,   /* field[2] = field3 */
};
static const ProtobufCIntRange ns_msg3__isi__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ns_msg3__isi__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg3_ISI",
  "NsMsg3ISI",
  "NsMsg3ISI",
  "",
  sizeof(NsMsg3ISI),
  3,
  ns_msg3__isi__field_descriptors,
  ns_msg3__isi__field_indices_by_name,
  1,  ns_msg3__isi__number_ranges,
  (ProtobufCMessageInit) ns_msg3__isi__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg3__iss__field_descriptors[3] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3ISS, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3ISS, field2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field3",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3ISS, field3),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg3__iss__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
  1,   /* field[1] = field2 */
  2,   /* field[2] = field3 */
};
static const ProtobufCIntRange ns_msg3__iss__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ns_msg3__iss__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg3_ISS",
  "NsMsg3ISS",
  "NsMsg3ISS",
  "",
  sizeof(NsMsg3ISS),
  3,
  ns_msg3__iss__field_descriptors,
  ns_msg3__iss__field_indices_by_name,
  1,  ns_msg3__iss__number_ranges,
  (ProtobufCMessageInit) ns_msg3__iss__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg3__sii__field_descriptors[3] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3SII, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3SII, field2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field3",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3SII, field3),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg3__sii__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
  1,   /* field[1] = field2 */
  2,   /* field[2] = field3 */
};
static const ProtobufCIntRange ns_msg3__sii__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ns_msg3__sii__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg3_SII",
  "NsMsg3SII",
  "NsMsg3SII",
  "",
  sizeof(NsMsg3SII),
  3,
  ns_msg3__sii__field_descriptors,
  ns_msg3__sii__field_indices_by_name,
  1,  ns_msg3__sii__number_ranges,
  (ProtobufCMessageInit) ns_msg3__sii__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg3__sis__field_descriptors[3] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3SIS, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3SIS, field2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field3",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3SIS, field3),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg3__sis__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
  1,   /* field[1] = field2 */
  2,   /* field[2] = field3 */
};
static const ProtobufCIntRange ns_msg3__sis__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ns_msg3__sis__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg3_SIS",
  "NsMsg3SIS",
  "NsMsg3SIS",
  "",
  sizeof(NsMsg3SIS),
  3,
  ns_msg3__sis__field_descriptors,
  ns_msg3__sis__field_indices_by_name,
  1,  ns_msg3__sis__number_ranges,
  (ProtobufCMessageInit) ns_msg3__sis__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg3__ssi__field_descriptors[3] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3SSI, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3SSI, field2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field3",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3SSI, field3),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg3__ssi__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
  1,   /* field[1] = field2 */
  2,   /* field[2] = field3 */
};
static const ProtobufCIntRange ns_msg3__ssi__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ns_msg3__ssi__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg3_SSI",
  "NsMsg3SSI",
  "NsMsg3SSI",
  "",
  sizeof(NsMsg3SSI),
  3,
  ns_msg3__ssi__field_descriptors,
  ns_msg3__ssi__field_indices_by_name,
  1,  ns_msg3__ssi__number_ranges,
  (ProtobufCMessageInit) ns_msg3__ssi__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg3__sss__field_descriptors[3] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3SSS, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3SSS, field2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field3",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3SSS, field3),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg3__sss__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
  1,   /* field[1] = field2 */
  2,   /* field[2] = field3 */
};
static const ProtobufCIntRange ns_msg3__sss__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ns_msg3__sss__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg3_SSS",
  "NsMsg3SSS",
  "NsMsg3SSS",
  "",
  sizeof(NsMsg3SSS),
  3,
  ns_msg3__sss__field_descriptors,
  ns_msg3__sss__field_indices_by_name,
  1,  ns_msg3__sss__number_ranges,
  (ProtobufCMessageInit) ns_msg3__sss__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg3__iid__field_descriptors[3] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3IID, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3IID, field2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field3",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg3IID, field3),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg3__iid__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
  1,   /* field[1] = field2 */
  2,   /* field[2] = field3 */
};
static const ProtobufCIntRange ns_msg3__iid__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ns_msg3__iid__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg3_IID",
  "NsMsg3IID",
  "NsMsg3IID",
  "",
  sizeof(NsMsg3IID),
  3,
  ns_msg3__iid__field_descriptors,
  ns_msg3__iid__field_indices_by_name,
  1,  ns_msg3__iid__number_ranges,
  (ProtobufCMessageInit) ns_msg3__iid__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg4__ssss__field_descriptors[4] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg4SSSS, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg4SSSS, field2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field3",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg4SSSS, field3),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field4",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg4SSSS, field4),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg4__ssss__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
  1,   /* field[1] = field2 */
  2,   /* field[2] = field3 */
  3,   /* field[3] = field4 */
};
static const ProtobufCIntRange ns_msg4__ssss__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ns_msg4__ssss__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg4_SSSS",
  "NsMsg4SSSS",
  "NsMsg4SSSS",
  "",
  sizeof(NsMsg4SSSS),
  4,
  ns_msg4__ssss__field_descriptors,
  ns_msg4__ssss__field_indices_by_name,
  1,  ns_msg4__ssss__number_ranges,
  (ProtobufCMessageInit) ns_msg4__ssss__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg4__sssi__field_descriptors[4] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg4SSSI, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg4SSSI, field2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field3",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg4SSSI, field3),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field4",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg4SSSI, field4),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg4__sssi__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
  1,   /* field[1] = field2 */
  2,   /* field[2] = field3 */
  3,   /* field[3] = field4 */
};
static const ProtobufCIntRange ns_msg4__sssi__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ns_msg4__sssi__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg4_SSSI",
  "NsMsg4SSSI",
  "NsMsg4SSSI",
  "",
  sizeof(NsMsg4SSSI),
  4,
  ns_msg4__sssi__field_descriptors,
  ns_msg4__sssi__field_indices_by_name,
  1,  ns_msg4__sssi__number_ranges,
  (ProtobufCMessageInit) ns_msg4__sssi__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg__form_api__field_descriptors[5] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsgFormApi, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsgFormApi, field2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field3",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsgFormApi, field3),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field4",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsgFormApi, field4),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fieldn",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(NsMsgFormApi, n_fieldn),
    PROTOBUF_C_OFFSETOF(NsMsgFormApi, fieldn),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg__form_api__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
  1,   /* field[1] = field2 */
  2,   /* field[2] = field3 */
  3,   /* field[3] = field4 */
  4,   /* field[4] = fieldn */
};
static const ProtobufCIntRange ns_msg__form_api__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ns_msg__form_api__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg_FormApi",
  "NsMsgFormApi",
  "NsMsgFormApi",
  "",
  sizeof(NsMsgFormApi),
  5,
  ns_msg__form_api__field_descriptors,
  ns_msg__form_api__field_indices_by_name,
  1,  ns_msg__form_api__number_ranges,
  (ProtobufCMessageInit) ns_msg__form_api__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg__start_user__field_descriptors[11] =
{
  {
    "user_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsgStartUser, user_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sess_idx",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsgStartUser, sess_idx),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sess_inst",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsgStartUser, sess_inst),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "script_name",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsgStartUser, script_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_ka_pct",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsgStartUser, num_ka_pct),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_ka_min",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsgStartUser, num_ka_min),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_ka",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsgStartUser, max_ka),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ua_string",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsgStartUser, ua_string),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group_id",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsgStartUser, group_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "runlogic_name",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsgStartUser, runlogic_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "package_name",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsgStartUser, package_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg__start_user__field_indices_by_name[] = {
  8,   /* field[8] = group_id */
  6,   /* field[6] = max_ka */
  5,   /* field[5] = num_ka_min */
  4,   /* field[4] = num_ka_pct */
  10,   /* field[10] = package_name */
  9,   /* field[9] = runlogic_name */
  3,   /* field[3] = script_name */
  1,   /* field[1] = sess_idx */
  2,   /* field[2] = sess_inst */
  7,   /* field[7] = ua_string */
  0,   /* field[0] = user_id */
};
static const ProtobufCIntRange ns_msg__start_user__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor ns_msg__start_user__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg_StartUser",
  "NsMsgStartUser",
  "NsMsgStartUser",
  "",
  sizeof(NsMsgStartUser),
  11,
  ns_msg__start_user__field_descriptors,
  ns_msg__start_user__field_indices_by_name,
  1,  ns_msg__start_user__number_ranges,
  (ProtobufCMessageInit) ns_msg__start_user__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg9__ssissssss__field_descriptors[9] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg9SSISSSSSS, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg9SSISSSSSS, field2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field3",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg9SSISSSSSS, field3),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field4",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg9SSISSSSSS, field4),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field5",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg9SSISSSSSS, field5),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field6",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg9SSISSSSSS, field6),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field7",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg9SSISSSSSS, field7),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field8",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg9SSISSSSSS, field8),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field9",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg9SSISSSSSS, field9),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg9__ssissssss__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
  1,   /* field[1] = field2 */
  2,   /* field[2] = field3 */
  3,   /* field[3] = field4 */
  4,   /* field[4] = field5 */
  5,   /* field[5] = field6 */
  6,   /* field[6] = field7 */
  7,   /* field[7] = field8 */
  8,   /* field[8] = field9 */
};
static const ProtobufCIntRange ns_msg9__ssissssss__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor ns_msg9__ssissssss__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg9_SSISSSSSS",
  "NsMsg9SSISSSSSS",
  "NsMsg9SSISSSSSS",
  "",
  sizeof(NsMsg9SSISSSSSS),
  9,
  ns_msg9__ssissssss__field_descriptors,
  ns_msg9__ssissssss__field_indices_by_name,
  1,  ns_msg9__ssissssss__number_ranges,
  (ProtobufCMessageInit) ns_msg9__ssissssss__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ns_msg9__isisssiii__field_descriptors[9] =
{
  {
    "field1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg9ISISSSIII, field1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg9ISISSSIII, field2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field3",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg9ISISSSIII, field3),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field4",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg9ISISSSIII, field4),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field5",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg9ISISSSIII, field5),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field6",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg9ISISSSIII, field6),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field7",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg9ISISSSIII, field7),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field8",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg9ISISSSIII, field8),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field9",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NsMsg9ISISSSIII, field9),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ns_msg9__isisssiii__field_indices_by_name[] = {
  0,   /* field[0] = field1 */
  1,   /* field[1] = field2 */
  2,   /* field[2] = field3 */
  3,   /* field[3] = field4 */
  4,   /* field[4] = field5 */
  5,   /* field[5] = field6 */
  6,   /* field[6] = field7 */
  7,   /* field[7] = field8 */
  8,   /* field[8] = field9 */
};
static const ProtobufCIntRange ns_msg9__isisssiii__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor ns_msg9__isisssiii__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NsMsg9_ISISSSIII",
  "NsMsg9ISISSSIII",
  "NsMsg9ISISSSIII",
  "",
  sizeof(NsMsg9ISISSSIII),
  9,
  ns_msg9__isisssiii__field_descriptors,
  ns_msg9__isisssiii__field_indices_by_name,
  1,  ns_msg9__isisssiii__number_ranges,
  (ProtobufCMessageInit) ns_msg9__isisssiii__init,
  NULL,NULL,NULL    /* reserved[123] */
};
