#!/bin/sh

# Name  : nsi_is_gateway_config_button
# Author: Achint
# usage :
#         nsi_is_gateway_config_button
#Script will show 0 or 1.Script will show 0 if there is atleast one gateway entry in ip entries file otherwise will show 1
# Modification History:
#   07/28/06  Initial version

#ip entries is now no longer Controller specific . Hence changing it to /home/cavisson/work
IP_ENTRIES=/home/cavisson/work/sys/ip_entries
get_ip_fields()
{
  GATEWAY=`echo $1 | cut -d "|" -f8`
}

gateway=0

# Add this check by Neeraj on Dec 20, 11
#Handle case when ip entries file is not present
if [ -f $IP_ENTRIES ]; then
  while read line
  do
    #Extracting Gateway IP Entries file.
    get_ip_fields $line
    if [ $GATEWAY != "-" ];then
      gateway=1
      break
    fi
  done<$IP_ENTRIES
fi

if [ $gateway == 1 ];then
  echo 0
else
  echo 1
fi
exit 0
