#!/bin/bash
#
# Name:    nsi_allocate_gen_instances
ALLOCATION_ID=$1
LOCATION=$2
GEN_REQ=$3
GEN_CAPACITY=$4
VENDOR=$5
BUILD_VERSION=$6
WHITELIST_IP_LIST=$7

TEST_RUN=$ALLOCATION_ID
if [ -d $NS_WDIR/logs/TR$TEST_RUN/NetCloud ]; then
  DEBUG_LOG_FILENAME=$NS_WDIR/logs/TR$TEST_RUN/NetCloud/gen_inst.netstorm.log
  GENERATOR_VALIDATION="$NS_WDIR/logs/TR$TEST_RUN/ready_reports/TestInitStatus/2_generatorValidation.log"
  CTRL_IP=`egrep ^NSAdminIP $NS_WDIR/logs/TR$TEST_RUN/cav.conf | awk -F " " '{print $2}'`
  HOST=`gethostip -x $CTRL_IP|tr '[:upper:]' '[:lower:]'`
  ALLOCATION_ID="i$HOST-tr$TEST_RUN"
else
  DATE=`date "+%Y-%m-%d"`
  DEBUG_LOG_FILENAME="$NS_WDIR/webapps/netstorm/logs/gen_inst.netstorm-${DATE}.log"
fi

debug_log()
{
   echo "`date "+%D %H:%M:%S"`|[$LOCATION]$*" >> $DEBUG_LOG_FILENAME
}

gen_log()
{
  echo "`date "+%D %H:%M:%S"`|$*" >> $GENERATOR_VALIDATION
}

##############################################################################
# 1. If generator server is configured and It is the test controller then
#      send Generator Allocation Request to Generator Server
# 2. Else use local generator allocation service
##############################################################################

NS_GEN_FILE="$NS_WDIR/etc/.netcloud/gen_server.conf"
if [ -f $NS_GEN_FILE -a "X$CTRL_IP" != "X" ]; then
  cp $NS_GEN_FILE $NS_WDIR/logs/TR$TEST_RUN/NetCloud
  GEN_SERV_URL=`grep "^generatorServer" $NS_GEN_FILE | cut -d'=' -f 2 | tr -d '[:space:]'`
  if [ "XX${GEN_SERV_URL}" != "XX" ]; then
    SUMMARY_TOP="$NS_WDIR/logs/TR$TEST_RUN/summary.top"
    TEST_OWNER=`cat $SUMMARY_TOP | cut -d '|' '-f6'`
    SCENARIO_NAME=`cat $SUMMARY_TOP | cut -d '|' '-f2'`
    START_TIMESTAMP=`cat $SUMMARY_TOP | cut -d '|' '-f3'` 
    START_TIMESTAMP=`date +%s -d "$START_TIMESTAMP"`
    debug_log "Sending Generator Allocation Request to Generator Server ${GEN_SERV_URL}"
    gen_log "Fetching the generator information for $LOCATION"
    #Call Rest API to allocate generator
    #ALLOCATED_ID|TEST_RUN|CONTROLLER_IP|LOCATION|NUM_GEN|TEST_OWNER|SCENARIO_NAME|START_TIMESTAMP
    nsi_gen_server_api -o allocateGenerator -a "$ALLOCATION_ID|$TEST_RUN|$CTRL_IP|$LOCATION|$GEN_REQ|$TEST_OWNER|$SCENARIO_NAME|$START_TIMESTAMP"
    exit 0
  fi
fi

debug_log "Allocating generator instances"
if [ "X$VENDOR" == "XGCP" ];then
  debug_log "Allocating GCP instances"
  $NS_WDIR/bin/nsi_allocate_gcp_instances $ALLOCATION_ID $LOCATION $GEN_REQ $GEN_CAPACITY $BUILD_VERSION $WHITELIST_IP_LIST
fi

#if [ "X$VENDOR" == "XCAV" ];then
#  debug_log "Allocating CAV instances"
#  nsi_allocate_cav_instances $ALLOCATION_ID $LOCATION $GEN_REQ $GEN_CAPACITY $WHITELIST_IP_LIST
#fi
