#!/bin/sh
#----------------------------------------------------------------------
# Name    :    nsu_check_vuser
# Author  :    Jagannath Dora
# Purpose :    To remove TR  from generators 
# Usage   :    nsi_rm_gen_trun -f <File> -d <days> -w  
# Modification History:
#   22/06/20:  Jagannath
#----------------------------------------------------



f=$1
file=$2
w=$5
d=$3
s_file(){


echo "export NS_WDIR=/home/cavisson/$con" > shell.sh
echo "for j in \`find /home/cavisson/$con/logs/ -maxdepth 1 -type d -mtime +$day|awk -F '/' '{print \$6}'|grep TR \`
do" >> shell.sh
if [[ "$w" = "-w" ]]
then
echo "nsi_set_test_mode \${j:2} W" >> shell.sh
fi
echo " 
echo y|nsu_rm_trun -n \${j:2} 
echo ""
done " >> shell.sh
}

remove_tr(){
for i in `cat $file`
do
ip=$(echo $i|awk -F '|' '{print $1}')
con=$(echo $i|awk -F '|' '{print $2}')
echo IP is $ip Controller is $con
s_file
nsu_server_admin -s $ip -F  shell.sh -D /tmp|grep -vw "Connecting to server"|grep -vw 'File "shell.sh" uploaded successfully.'
nsu_server_admin -s $ip -c 'sh /tmp/shell.sh'|grep -vw "Connecting to server"
echo
done

}

error_message(){
red=`tput setaf 1`
reset=`tput sgr0`
echo Error: Atleast -f and File Name should be used
echo "NOTE: Do Not Add Controller's IP "
echo Usage:
echo "${red}nsi_rm_gen_trun -f <file name> -d <days> -w ${reset}"
echo
echo "-f <File name> : File format should be:- IP|Controller"
echo "-d <To keep the tr from last n days> : n is the number of days"
echo "-w : To Unlock All The TR"
echo "It will keep 5days data on generators "

}

##########################################################################################################################################
#							Main										 #
##########################################################################################################################################
if [[ "$#" > 5 ]]
then
echo Too Many Arguments, Please Check Syntax
error_message
exit
elif [[ "$f" = "-f" ]] && [[ "$file" != '' ]] && [[ "$d" = "-d" ]] && [[ "$4"  =~ ^[0-500]+$ ]] 
then
if [[ $4 -eq 0 ]]
then
day=5
else
day=$4
fi

remove_tr  
else
error_message
fi

