#!/bin/sh
# Name  : nsi_del_ipv6
# usage :
#       nsi_del_ip entity start_ip end_ip vlanid netbits exclude_ip netid gateway
# if  entity C (means clinet), command would be run locally, 
# if entity is S, run it for netocean.. In this case same cmd is 
# run on netocean with entity set to R and passing an extra argument of Load interface
# netbits is the number of bits in netid.
HOME_DIR=/home/cavisson
CONFIG=`grep ^CONFIG $HOME_DIR/etc/cav.conf | awk  '{print $2}'`

USER=`whoami`
if [ "X$USER" != "Xcavisson" ];then
    echo "You must be logged in as cavisson user to execute this command"
    exit -1
fi

CHECK_FORMAT=$NS_WDIR/bin/nsu_check_ipv6_format

if [ "$#" -ne 10 ];then
  echo "usage:nsi_del_ipv6 entity start_ip end_ip vlanid netbits exclude_ip netid gateway interface"
  exit 1
fi
RLOGIN="ssh -n"
ENTITY=$1
start_ip=$2
end_ip=$3
VLANID=$4
netbits=$5
EXCLUDE_IP=$6
netid=$7
GATEWAY=$8
LOAD_INTERFACE=$9
DEL_VLAN=${10}

#Do Input validation
#Check start-ip and end-ip are valid
  $CHECK_FORMAT  $start_ip
  if [ $? -ne 0 ];then
    echo "start ip $2 not in valid ipv6 format"
    exit 1
  fi
  $CHECK_FORMAT  $end_ip
  if [ $? -ne 0 ];then
    echo "End ip $end_ip not in valid ipv6 format"
    exit 1
  fi

#check vlanid is either - or non-negative
  if [ $VLANID != "-" ];then
    if [ $VLANID -lt 0 ];then
      echo "Vlan Id can not be Negative"
      exit 1
    fi
  fi
#check netbits is more than 0 and less than 128
  if [ $netbits -le 0 -o $netbits -gt 127 ];then
    echo "Netbits can not be less than 0 and greater than 127"
    exit 1
  fi
#check exclude ip is either - or a valid IP
  if [ $EXCLUDE_IP != "-" ];then
   $CHECK_FORMAT  $EXCLUDE_IP
    if [ $? -ne 0 ];then
      echo "EXCLUDE IP $EXCLUDE_IP not in valid ipv6 format"
      exit 1
    fi
  fi
#Check net id is in correct format
  if [ $netid != "-" ];then
    $CHECK_FORMAT  $netid
    if [ $? -ne 0 ];then
      echo "Net Id $netid not in valid ipv6 format"
      exit 1
    fi
  fi
#check gateway is in correct format
  if [ $GATEWAY != "-" -a $GATEWAY != "SELF" ];then
    $CHECK_FORMAT  $GATEWAY
    if [ $? -ne 0 ];then
      echo "Gateway $GATEWAY not in valid ipv6 format"
      exit 1
    fi
  fi

#Function to delete the route and gateway
#First argument is netid/netbits and second arg is gateway 
 del_route () 
{ 
  if [ $2 == "-" ];then 
    return 0 
  fi 

  #delete route 
  if [ $2 == "SELF" ];then 
      sudo /sbin/ip route del default table $1 
  else
      sudo /sbin/ip route del default via $2 table $1 
  fi
  #delete same net rule if gateway is present 
  if [ $2 != "-" ];then
    sudo /sbin/ip rule del from $1 to $1 table main
  fi
  #delete main rule 
  sudo /sbin/ip rule del from $1 table $1
#delete route tableid 
  cp /etc/iproute2/rt_tables /tmp/del_route.$$ 
  grep -v $1 /tmp/del_route.$$ >/etc/iproute2/rt_tables 
  rm /tmp/del_route.$$ 
  return 0
}

#changes for deletion of ip on NO machine
if [ "XX$CONFIG" != "XXNO" ];then 
  if [ "$ENTITY" == "S" ];then
    SR_ADDRESS=`cat $HOME_DIR/etc/cav.conf | grep "SRAdminIP" | cut -d" " -f2 | cut -d/ -f1`
    NS_ADDRESS=`cat $HOME_DIR/etc/cav.conf | grep "NSAdminIP" | cut -d" " -f2 | cut -d/ -f1`
    if [ "$SR_ADDRESS" != "$NS_ADDRESS" ];then
      # Run '$NS_WDIR/nsi_del_ipv6 R $start_ip $end_ip $VLANID $netbits $EXCLUDE_IP $LOAD' on $SR_ADDRESS as root
      output_rlogin=`$RLOGIN $SR_ADDRESS $NS_WDIR/bin/nsi_del_ipv6 R $start_ip $end_ip $VLANID $netbits $EXCLUDE_IP $netid $GATEWAY $LOAD_INTERFACE $DEL_VLAN`
      echo $output_rlogin
      exit 0
    fi
  fi 
fi

#Call function to delete the route and gateway
#First argument is netid/netbits and second arg is gateway 
del_route $netid/$netbits $GATEWAY

if [ "$VLANID" != "-" ];then
  del_interface=$LOAD_INTERFACE.$VLANID
else
  del_interface=$LOAD_INTERFACE
fi

#Delete IP $start_ip $end_ip
for x in `$NS_WDIR/bin/nsu_seq_ipv6 $start_ip $end_ip`
do
  if [ "$x" != $EXCLUDE_IP ];then
     `/sbin/ip address del $x/$netbits dev $del_interface` 1>/dev/null 2>&1
  fi
done

if [ $DEL_VLAN -eq 1 ];then
	/sbin/vconfig rem $del_interface
fi
exit 0
