#!/bin/bash

#args: TestRun UrlIndex Location Access [RunPhaseFlag]

. $NS_WDIR/bin/nsi_db_utils

NEED_SESS_REC=1
if [ $3 = "All" -a $4 = "All" ];then
	NEED_SESS_REC=0
fi

SELECT="SELECT  round(avg(ConnectStartTime-UrlRecord_$1.StartTime)) AS \"DNS Lookup\",
	round(avg(ConnectDoneTime-ConnectStartTime)) AS \"Connection Time\",
	round(avg(SSLHandShakeDone-ConnectDoneTime)) AS \"SSL Handshake\",
	round(avg(WriteCompleTime-SSLHandShakeDone)) AS \"Request Send Time\",
	round(avg(FirstByteRcdTime-WriteCompleTime)) AS \"First Byte Received Time\",
	round(avg(RequestCompletedTime-FirstByteRcdTime)) AS \"Content Download Time\""
FROM="FROM UrlRecord_$1"
WHERE="WHERE UrlRecord_$1.Status = 0 AND UrlRecord_$1.UrlIndex = $2"

if [ $RPO -eq 1 ];then
	WHERE="$WHERE AND isRunPhase = true"
	NEED_SESS_REC=1
fi

if [ $NEED_SESS_REC -eq 1 ];then
        WHERE="$WHERE AND UrlRecord_$1.SessionInstance = SessionRecord_$1.SessionInstance
        AND UrlRecord_$1.ChildIndex = SessionRecord_$1.ChildIndex" 
        FROM="$FROM,  SessionRecord_$1"
fi

#Add Location/Access
if [ $3 != "All" ];then
    WHERE="$WHERE AND Location = ""'"$3"'"
fi

if [ $4 != "All" ];then
    WHERE="$WHERE AND Access = ""'"$4"'"
fi

log_query
run_nd_query
show_ns_query_result
exit 0
