#!/bin/bash

VERSION_NO=""
BUILD_NO=""
GUI_BUILD_FILE=$NS_WDIR/webapps/netstorm/etc/version

usage()
{ 
  echo $'\t' Usage:
  echo $'\t'  "nsi_migrate_alert_tabel[-t <test run number>]"
  echo $'\t'  This command is used to upgrade alerthistory data table.
  echo $'\t'  where :
  echo $'\t'"    -t : provide test run number for which we need to update data structure."
  exit -1
}

echo $OPTARG
while getopts :t: options
  do
    case $options in
      t) TR_NUMBER="$OPTARG";;
      ?) usage;;
    esac
  done


if [ $# -eq 0 ] || [ "X$TR_NUMBER" == "X" ] ;then
  echo $'\n' Please provide test run number to update table
  echo ""
  usage
  exit -1
fi

#method will get gui build version annd build number
get_version_build_no()
{
  VERSION_NO=`cat $1 | grep "VERSION"| cut -d" " -f2`
  BUILD_NO=`cat $1 | grep "BUILD" | cut -d" " -f2` 
}

get_version_build_no $GUI_BUILD_FILE

RELEASE_FIRST_FIELD=`echo $VERSION_NO| cut -d'.' -f1`
RELEASE_SECOND_FIELD=`echo $VERSION_NO| cut -d'.' -f2`
RELEASE_THIRD_FIELD=`echo $VERSION_NO| cut -d'.' -f3`

if [ $RELEASE_FIRST_FIELD -eq 4 ] && [ $RELEASE_SECOND_FIELD -eq 1 ] && [ $RELEASE_THIRD_FIELD -ge 12 ]
then
  psql test cavisson <<+
     ALTER TABLE alerthistory_$TR_NUMBER ADD GraphType smallint;
     ALTER TABLE alerthistory_$TR_NUMBER ADD DrivedVectors varchar(4096);
     ALTER TABLE alerthistory_$TR_NUMBER ADD SourceProtocol varchar(10);
     ALTER TABLE alerthistory_$TR_NUMBER ADD SourceIP varchar(20);
     ALTER TABLE alerthistory_$TR_NUMBER ADD SourcePort varchar(10);
     ALTER TABLE alerthistory_$TR_NUMBER ADD mcSpecialCase int;
     ALTER TABLE alerthistory_$TR_NUMBER ADD mcRuleLevel int;
     ALTER TABLE alerthistory_$TR_NUMBER ADD mcIndices varchar;
     ALTER TABLE alerthistory_$TR_NUMBER ADD mcAlertValue varchar;
     ALTER TABLE alerthistory_$TR_NUMBER ADD mcBaselineValue varchar;
     ALTER TABLE alerthistory_$TR_NUMBER ADD mcConditionExp varchar;
     ALTER TABLE alerthistory_$TR_NUMBER ADD mcConditionInfo varchar;
     ALTER TABLE alerthistory_$TR_NUMBER ADD mcSatisfiedGGV varchar;
     ALTER TABLE alerthistory_$TR_NUMBER ADD mcSeverityLevel smallint;
     ALTER TABLE alerthistory_$TR_NUMBER ALTER COLUMN mcIndices TYPE varchar;
     ALTER TABLE alerthistory_$TR_NUMBER ALTER COLUMN mcAlertValue TYPE varchar;
     ALTER TABLE alerthistory_$TR_NUMBER ALTER COLUMN mcBaselineValue TYPE varchar;
     ALTER TABLE alerthistory_$TR_NUMBER ALTER COLUMN mcConditionExp TYPE varchar;
     ALTER TABLE alerthistory_$TR_NUMBER ALTER COLUMN mcConditionInfo TYPE varchar;
     ALTER TABLE alerthistory_$TR_NUMBER ALTER COLUMN mcSatisfiedGGV TYPE varchar;
+
elif [ $RELEASE_FIRST_FIELD -eq 4 ] && [ $RELEASE_SECOND_FIELD -eq 1 ] && [ $RELEASE_THIRD_FIELD -le 11 ] && [ $RELEASE_THIRD_FIELD -ge 10 ] && [ $BUILD_NO -gt 0 ]
then
  psql test cavisson <<+
     ALTER TABLE alerthistory_$TR_NUMBER ADD GraphType smallint;
     ALTER TABLE alerthistory_$TR_NUMBER ADD DrivedVectors varchar(4096);
     ALTER TABLE alerthistory_$TR_NUMBER ADD SourceProtocol varchar(10);
     ALTER TABLE alerthistory_$TR_NUMBER ADD SourceIP varchar(20);
     ALTER TABLE alerthistory_$TR_NUMBER ADD SourcePort varchar(10);
     ALTER TABLE alerthistory_$TR_NUMBER DROP COLUMN mcSpecialCase;
     ALTER TABLE alerthistory_$TR_NUMBER DROP COLUMN mcRuleLevel;
     ALTER TABLE alerthistory_$TR_NUMBER DROP COLUMN mcIndices; 
     ALTER TABLE alerthistory_$TR_NUMBER DROP COLUMN mcAlertValue;
     ALTER TABLE alerthistory_$TR_NUMBER DROP COLUMN mcBaselineValue;
     ALTER TABLE alerthistory_$TR_NUMBER DROP COLUMN mcConditionExp;
     ALTER TABLE alerthistory_$TR_NUMBER DROP COLUMN mcConditionInfo;
     ALTER TABLE alerthistory_$TR_NUMBER DROP COLUMN mcSatisfiedGGV;
     ALTER TABLE alerthistory_$TR_NUMBER DROP COLUMN mcSeverityLevel;
+
elif [ $RELEASE_FIRST_FIELD -eq 4 ] && [ $RELEASE_SECOND_FIELD -eq 1 ] && [ $RELEASE_THIRD_FIELD -eq 9 ] && [ $BUILD_NO -gt 0 ]
then
  psql test cavisson <<+
     ALTER TABLE alerthistory_$TR_NUMBER DROP COLUMN SourceProtocol;
     ALTER TABLE alerthistory_$TR_NUMBER DROP COLUMN SourceIP;
     ALTER TABLE alerthistory_$TR_NUMBER DROP COLUMN SourcePort;
     ALTER TABLE alerthistory_$TR_NUMBER ADD GraphType smallint;
     ALTER TABLE alerthistory_$TR_NUMBER ADD DrivedVectors varchar(4096);
     ALTER TABLE alerthistory_$TR_NUMBER DROP COLUMN mcSpecialCase;
     ALTER TABLE alerthistory_$TR_NUMBER DROP COLUMN mcRuleLevel;
     ALTER TABLE alerthistory_$TR_NUMBER DROP COLUMN mcIndices; 
     ALTER TABLE alerthistory_$TR_NUMBER DROP COLUMN mcAlertValue;
     ALTER TABLE alerthistory_$TR_NUMBER DROP COLUMN mcBaselineValue;
     ALTER TABLE alerthistory_$TR_NUMBER DROP COLUMN mcConditionExp;
     ALTER TABLE alerthistory_$TR_NUMBER DROP COLUMN mcConditionInfo;
     ALTER TABLE alerthistory_$TR_NUMBER DROP COLUMN mcSatisfiedGGV;
     ALTER TABLE alerthistory_$TR_NUMBER DROP COLUMN mcSeverityLevel;
+
fi
