#! /bin/sh
if [ $# -eq 0 ];then
	echo "$0: At leaset one session name is required"
	exit 1;	
fi

if [ "XX" = "XX$NS_WDIR" ];then
	NS_WDIR=/home/cavisson/work
fi

for i in `seq 1 $#`
do

if [ -f $NS_WDIR/scripts/$1/$1.h ];then
	DETAIL="$NS_WDIR/scripts/$1/$1.h"
elif [ -f $NS_WDIR/scripts/$1/script.h ];then
	DETAIL="$NS_WDIR/scripts/$1/script.h"
else
	echo "script $1 does not seem to have proper h file"
	exit 1
fi

	cat $DETAIL | egrep "^#define" | awk '{print $2}'
	shift
done
exit 0
