#!/bin/sh
# Name  : nsi_get_primary
# usage : nsi_get_primary entity sip/netbits load
# Author: Sanjay/Achint

#This command is used by nsu_check_ip command
#This command get the primary ip for given start ip
HOME_DIR=/home/cavisson
CONFIG=`grep ^CONFIG $HOME_DIR/etc/cav.conf | awk  '{print $2}'`

if [ "$#" -lt 4 ];then
  echo "usage:nsi_get_primary entity sip/netbits valn Interface"
  exit 1
fi
ENTITY=$1
echo $2 | grep / >>/dev/null
if [ $? -ne 0 ];then
  echo "usage:nsi_get_primary entity sip/netbits valn Interface"
  exit 1
fi

RLOGIN="ssh -n"
sip_netbits=$2
VLANID=$3
LOAD=$4
#changes for deletion of ip on NO machine
if [ "XX$CONFIG" != "XXNO" ];then
  if [ "$ENTITY" == "S" ];then
    SR_ADDRESS=`cat $HOME_DIR/etc/cav.conf | grep "SRAdminIP" | cut -d" " -f2 | cut -d/ -f1`
    NS_ADDRESS=`cat $HOME_DIR/etc/cav.conf | grep "NSAdminIP" | cut -d" " -f2 | cut -d/ -f1`
    if [ "$SR_ADDRESS" != "$NS_ADDRESS" ];then
      # Run '$NS_WDIR/nsi_get_primary R $sip_netbits $VLANID $LOAD on $SR_ADDRESS as root
      output_rlogin=`$RLOGIN $SR_ADDRESS $NS_WDIR/bin/nsi_get_primary R $sip_netbits $VLANID $LOAD`
      echo $output_rlogin
      exit 0
    fi
  fi
fi

if [ "$VLANID" != "-" ];then
  LOAD=$LOAD.$VLANID
else
  LOAD=$LOAD
fi
primary=`sudo /sbin/ip addr show to $sip_netbits dev $LOAD primary | grep inet`
primary=`echo $primary | cut -d" " -f2 | cut -d"/" -f1`
if [ "XX$primary" == "XX" ];then
  primary=0
fi
echo $primary
exit 0

