#! /bin/sh

# This is called from nsi_gui_upgrade to start tomcat after some time so that upgrade from GUI can show upgrade logs

#UPGRADE_FROM_GUI environment variable is set in nsu_upgrade_build 
if [ "X$UPGRADE_FROM_GUI" == "X1" ];then
  sleep 60
fi

echo "Stopping tomcat Server" 
/etc/init.d/$TOMCAT_CMD stop

echo "Removing $TOMCAT_DIR/work/Catalina/localhost" 
#rm -rf $TOMCAT_DIR/work/Catalina/localhost >/dev/null
rm -rf $TOMCAT_DIR/work/Catalina/localhost 

#Give some time for port to become free
sleep 5 

echo "Starting tomcat Server" 
/etc/init.d/$TOMCAT_CMD start 

exit 0
