#!/bin/bash

cd $NS_WDIR/upgrade
rm -f /var/lib/pgsql/dbfunc*gz
su postgres -c "cp dbfunc*gz /var/lib/pgsql"
cd /var/lib/pgsql

su postgres -c "tar -xzf dbfunc*gz"
su postgres -c "./install_percentiles"



