#!/bin/bash

#args: TR-NUM Parent-tx pgidx loc-selection acc-selection

if [ $# -lt 5 ];then
    	echo "Usage: nsi_get_5p TR-NUM parent-tx pgidx loc-selection acc-selection"
	echo "TR-NUM is the test run number"
	echo "parent-tx can be tx name or All"
	echo "pgidx is teh page index"
	echo "location-slectection: All for all otherwise location name"
	echo "access-slectection: All for all otherwise access name"
	echo "run-time-flag is 1 for run-time phase only, otherwise 0"
	exit 1
fi
TRNUM=$1

if [ "XX" == "XX$NS_WDIR" ]
then
  NS_WDIR=/home/cavisson/work
fi

. $NS_WDIR/bin/nsi_db_utils
set_query_files $TRNUM

if [ $# -eq 5 ];then
	RPO=0
else
	RPO=$6
fi
NEED_SESS_REC=1
if [ $4 = "All" -a $5 = "All" ];then
	NEED_SESS_REC=0
fi

#To exclude failed records. URLs are always excluded, aggrgates are excluded
#based on config
if [ -f $NS_WDIR/logs/TR$1/exclude_failed_aggregate ];then
	EXCLUDE=1
else
	EXCLUDE=0
fi

SELECT="SELECT UrlType AS \"Component\", 
	round(avg(UrlRecord_$1.EndTime-UrlRecord_$1.StartTime)) AS \"Average Response Time\""
FROM="FROM UrlRecord_$1"
WHERE="WHERE UrlRecord_$1.PageIndex = $3 AND UrlType != 2"
#WHERE="WHERE PageRecord_$1.PageIndex = $3"
#WHERE="$WHERE AND PageRecord_$1.ChildIndex = UrlRecord_$1.ChildIndex"
#WHERE="$WHERE AND PageRecord_$1.SessionInstance = UrlRecord_$1.SessionInstance"
#WHERE="$WHERE AND PageRecord_$1.PageInstance = UrlRecord_$1.PageInstance"
#WHERE="$WHERE AND UrlType != 2"
if [ $EXCLUDE -eq 1 ];then
    WHERE="$WHERE AND PageRecord_$1.Status = 0"
fi
GROUP="GROUP BY UrlType"
ORDER="ORDER BY UrlType"

if [ $RPO -eq 1 ];then
	WHERE="$WHERE AND isRunPhase = true"
	NEED_SESS_REC=1
fi

if [ $NEED_SESS_REC -eq 1 ];then
        WHERE="$WHERE AND UrlRecord_$1.SessionInstance = SessionRecord_$1.SessionInstance
        AND UrlRecord_$1.ChildIndex = SessionRecord_$1.ChildIndex" 
        FROM="$FROM,  SessionRecord_$1"
fi

#Add obj name
if [ $2 != "All" ];then
    WHERE="$WHERE AND TransactionTable_$1.TransactionName = ""'"$2"'"
    WHERE="$WHERE AND UrlRecord_$1.TransactionIndex = TransactionTable_$1.TransactionIndex"
    FROM="$FROM,  TransactionTable_$1"
fi

#Add Location/Access
if [ $4 != "All" ];then
    WHERE="$WHERE AND Location = ""'"$4"'"
fi

if [ $5 != "All" ];then
    WHERE="$WHERE AND Access = ""'"$5"'"
fi

log_query
run_query
show_ns_query_result 

exit 0
