#!/bin/sh

# Name   : nsi_gen_msr_info
# Author : Neeraj
# Purpose: 
# Takes input in the format 
#  nsi_gen_msr_info <Input File> <Output File> <Min Time(In Minutes)>
#
# Exit Values:
#   0 - OK
#   1 - Bad Arguments/Invalid input format
#
# Modification History:
#   10/05/07  Initial version


# This is to set CLASSPATH
export CLASSPATH=$CLASSPATH:$NS_WDIR/webapps/netstorm/WEB-INF/lib/chart1.5.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/itext-paulo-154.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/jcommon-0.9.5.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/poi.jar

if [ $# -lt 3 ];then
  echo "Usage: nsi_gen_msr_info <Input File> <Output File> <Min Time(In Minutes)>"
  echo "Input File"
  echo "Output File"
  echo "Minimum Time(In Minutes)"
  exit 1 
fi

if [ "XX$NS_WDIR" == "XX" ];then
  echo "NS_WDIR must be defined"
  exit 1
fi

#if [ ! -d $NS_WDIR/logs/TR$1 ];then 
#  echo "Given Test Run number $1 does not exist."
#  exit 1
#fi

#cd $NS_WDIR/webapps/netstorm/WEB-INF/classes
java -cp $NS_WDIR/webapps/netstorm/WEB-INF/lib/netstorm_bean.jar -DNS_WDIR=$NS_WDIR -Djava.awt.headless=true pac1.Bean.GenMsrInfo $*

exit 0
