#!/bin/bash

#############################################################################################
# Name    : nsi_drop_empty_partition_table
# Purpose : Drop empty partition table from table. Which has no records.
# Date    : 20/09/2017
# Author  : Jharana Sa
#
############################################################################################

#This modification will only remove those tables which are empty and which has no further child tables
 
TABLE_NAMES=(`psql test cavisson -t --no-align <<+
            select relname from pg_class ,(select a.inhrelid from pg_inherits as a where  not exists (select 1 from pg_inherits as b where b.inhparent = a.inhrelid))inq  where pg_class.oid = inq.inhrelid group by relname;
+`)



TABLE_NAMES_COUNT="${#TABLE_NAMES[@]}"

for((i=0; i < $TABLE_NAMES_COUNT; i++));
do
TABLE_SIZE=`psql test cavisson -t --no-align <<+
  SELECT pg_relation_size('${TABLE_NAMES[$i]}');
+`
if [ "X$TABLE_SIZE" == "X0" ];then
  echo "name = ${TABLE_NAMES[$i]}, size = $TABLE_SIZE" >>/tmp/ff
 psql test cavisson <<+
   drop table ${TABLE_NAMES[$i]};
+

fi
done
