#! /bin/sh

# Basename is exported from nsi_upgrade shell
export WORK=$BASENAME

RELEASE_CMD="nsi_get_linux_release_ex"
DISTRO=`$RELEASE_CMD -d`

init_saas()
{
  msgout_both "initializing saas variables"
  SAAS_SCENARIO_PATH="$NS_WDIR/scenarios/default/default"
  SAAS_SCENARIO="saas_scenario.conf"

  SAAS_TOPOLOGY_PATH="$NS_WDIR/topology/saas_topology"
  SAAS_TOPOLOGY="saas_topology"

  SAAS_SCRIPT_PATH="$NS_WDIR/scripts/default/default/saas_server_only_script"
}

#msgout_both "############################################################"
if [ "X$NDC_ROOT" = "X" ];then
  export NDC_ROOT=$NS_WDIR/ndc
  export NDC_CMD=ndc
fi

if [ "X$LPS_ROOT" = "X" ];then
  export LPS_ROOT=$NS_WDIR/lps
  export LPS_CMD=lps
fi

msgout_both "Start ndc upgradation NDC_CMD = $NDC_CMD"
if [ -f /etc/init.d/$NDC_CMD ];then
  msgout_both "Stopping ndc releated processes"
  /etc/init.d/$NDC_CMD forcestop
fi

#sudo update-rc.d -f $NDC_CMD remove >/dev/null 2>&1

mkdir -p $NDC_ROOT
mkdir -p $NS_WDIR/dr
mkdir -p $NS_WDIR/dr/conf
mkdir -p $NS_WDIR/dr/logs

cd $NDC_ROOT

msgout_both "Removing directories of old version."
rm -rf bin etc

msgout_both "Uncompressing tar file - $GZ"
cp $NS_WDIR/.rel/$GZ .
tar xvzf $GZ >> $LOG_FILE_NAME
rm $GZ

if [ "$?" != 0 ];then
  msgout_both "Error: Error in uncompressing the $GZ"
  exit 1
fi

cp -r ndc/* .
rm -rf ndc
#Change perm to 777 so that custom monitor (remote) can open log files if not running as root
# DO it after untar as tar also has logs dir
mkdir -p logs
chmod 777 logs

#Make directory for csv dump by NDC
mkdir -p .reports
chmod 777 .reports

if [ ! -f "$NDC_ROOT/conf/ndc.conf" ];then
  mkdir -p  $NDC_ROOT/conf
  cp sample/ndc.conf  conf/

  if [ "X$NDC_LISTEN_PORT" != "X" ]; then
    sed -i "s/PORT 7892/PORT $NDC_LISTEN_PORT/g" conf/ndc.conf
  fi
fi

if [ ! -f "$NDC_ROOT/conf/nd_dr_state.conf" ]; then
  cp sample/nd_dr_state.conf conf/
fi

if [ ! -f "$NDC_ROOT/conf/nd.conf" ]; then
  cp sample/nd.conf  conf/
fi

if [ ! -f "$NS_WDIR/dr/conf/nde_dr_keywords.conf" ]; then
  cp sample/nde_dr_keywords.conf $NS_WDIR/dr/conf/
fi

if [ ! -f "$NDC_ROOT/conf/HealthConfig.json" ]; then
  cp sample/HealthConfig.json conf/
fi

init_saas

#if [ ! -d "$SAAS_SCENARIO_PATH" ];then
#  mkdir -p $SAAS_SCENARIO_PATH
#fi

#if [ ! -f "$SAAS_SCENARIO_PATH/$SAAS_SCENARIO" ];then
#  cp sample/$SAAS_SCENARIO  $SAAS_SCENARIO_PATH/
#fi

if [ ! -d "$SAAS_TOPOLOGY_PATH" ];then
  mkdir -p $SAAS_TOPOLOGY_PATH
  cp -r sample/$SAAS_TOPOLOGY/*  $SAAS_TOPOLOGY_PATH/
fi

#if [ ! -d $SAAS_SCRIPT_PATH ];then
#  mkdir -p $SAAS_SCRIPT_PATH
#  cp -r sample/saas_server_only_script/*  $SAAS_SCRIPT_PATH/
#fi

#Copy health check and rsync shells from NS_WDIR/bin to dr/ directory for DR Phase 2
cp $NS_WDIR/bin/nsi_dr_common.sh $NS_WDIR/dr/
cp $NS_WDIR/bin/nsi_dr_rsync.sh $NS_WDIR/dr/
cp $NS_WDIR/bin/nsu_dr_health_check.sh $NS_WDIR/dr/

#We need to overwrite this file each time
cp sample/global.xml  conf/
cp sample/PetStoreAllInstrumented.xml  conf/
cp sample/ns_samplesAllInst.xml  conf/
cp sample/netstorm_beanAllInst.xml  conf/
cp sample/NDMonitors.conf  conf/
cp sample/ndc_http_hdr_state_model.txt conf/


#msgout_both "Copying ndc startup shell to /etc/init.d/$NDC_CMD"
#pwd
#echo "Copying ndc startup shell to /etc/init.d/$NDC_CMD"
 # sudo cp bin/ndc /etc/init.d/$NDC_CMD
 # sudo chmod +x /etc/init.d/$NDC_CMD  

  #Adding LSB headers to the init script so as to remove warning coming in build
 # echo -e "### BEGIN INIT INFO\n# Provides: ndc\n# Required-Start:\n# Required-Stop:\n# Default-Start:\n# Default-Stop:\n# Short-Description: start|stop|restart|show|version|show_monitors|show_pid ndc\n# Description: Starting NetDiagnostics Server (HPD)\n### END INIT INFO\n" >>/etc/init.d/$NDC_CMD
#if [ "X$NDC_CMD" != "ndc" ];then
#  sudo sed -i "s/export NDC_ROOT=\/home\/cavisson\/work\/ndc/export NDC_ROOT=\/home\/cavisson\/$WORK\/ndc/g" /etc/init.d/$NDC_CMD
#  sudo sed -i "s/export NDC_CMD=ndc/export NDC_CMD=$NDC_CMD/g" /etc/init.d/$NDC_CMD
#  sudo sed -i "s/export NS_CONTROLLER_NAME=work/export NS_CONTROLLER_NAME=$WORK/g" /etc/init.d/$NDC_CMD
#  sudo cp /etc/init.d/$NDC_CMD bin/ndc 
#fi

cp /etc/init.d/$NDC_CMD bin/ndc 
#Change the directory owner:group
#chown -R cavisson:cavisson ../ndc

#Updating ndc service
sudo $CavService $BASENAME 5 ndc

#add ndc persimission to listen on reserved port
sudo setcap 'cap_net_bind_service+ep' $NDC_ROOT/bin/ndcollector >/dev/null 2>&1
sudo setcap 'cap_net_bind_service+ep' $NDC_ROOT/bin/ndcollector.debug >/dev/null 2>&1

#msgout_both "Starting ndc Server"
/etc/init.d/$NDC_CMD start
#sudo update-rc.d $NDC_CMD defaults
exit 0

