#!/bin/bash

#args: TR-NUM Parent-obj-type obj-name loc-selection acc-selection run-time-flag
if [ $# -lt 5 ];then
        echo "Usage: nsi_get_5a TR-NUM parent-obj-type parent-obj-name loc-selection acc-selection run-time_flag"
        echo "TR-NUM is the test run number"
        echo "parent-obj-type can be 2: Tx 3:Sess"
        echo "obj-name : Tx or Session name"
        echo "location-slectection: All for all otherwise location name"
        echo "access-slectection: All for all otherwise access name"
        echo "run-time-flag is 1 for run-time phase only, otherwise 0"
        exit 1
fi

TRNUM=$1

if [ "XX" == "XX$NS_WDIR" ]
then
  NS_WDIR=/home/cavisson/work
fi

. $NS_WDIR/bin/nsi_db_utils
set_query_files $TRNUM

#To exclude failed records. URLs are always excluded, aggrgates are excluded
#based on config
if [ -f $NS_WDIR/logs/TR$1/exclude_failed_aggregate ];then
        EXCLUDE=1
else
        EXCLUDE=0
fi

if [ $# -eq 5 ];then
        RPO=0
else
        RPO=$6
fi


#nsi_get_5a 2977 2 hpd_page1_trans1 All All 0
#        PageRecord_$1.PageIndex AS \"Page Index\",


SELECT="SELECT PageName AS \"Page Name\",inq.*"
INNER_QUERY="SELECT
        PageRecord_$1.PageIndex,
        count(*) AS \"Total\",
        round(avg(PageRecord_$1.EndTime - PageRecord_$1.StartTime)) AS \"Avg Page Response Time\""
INNER_QUERY_FROM="FROM PageRecord_$1"
if [ $2 -eq 2 ];then
    INNER_QUERY_WHERE="WHERE TransactionIndex IN
        (select TransactionIndex from TransactionTable_$1
        WHERE TransactionTable_$1.TransactionName = ""'"$3"')"
elif [ $2 -eq 3 ];then
    INNER_QUERY_WHERE="WHERE SessionIndex IN
        (select SessionIndex from SessionTable_$1
        WHERE SessionTable_$1.SessionName = ""'"$3"')"
else
    echo "Invalid object-type (valid values 2 or 3)"
    exit 1
fi
if [ $4 != "All" -o $5 != "All" -o $RPO -eq 1 ];then
   INNER_QUERY_WHERE="$INNER_QUERY_WHERE AND (sessioninstance, childindex) IN"
   SECOND_INNER_QUERY="(select SessionInstance, ChildIndex from SessionRecord_$1"
   SECOND_INNER_WHERE="WHERE"
   AND=""
#Add Location/Access
  if [ $4 != "All" ];then
    SECOND_INNER_WHERE="$SECOND_INNER_WHERE $AND Location = ""'"$4"'"
    AND="AND"
  fi

  if [ $5 != "All" ];then
    SECOND_INNER_WHERE="$SECOND_INNER_WHERE $AND Access = ""'"$5"'"
    AND="AND"
  fi
  if [ $RPO -eq 1 ]; then
    SECOND_INNER_WHERE="$SECOND_INNER_WHERE $AND isRunPhase = true"
    AND="AND"
  fi
   SECOND_INNER_QUERY="$SECOND_INNER_QUERY $SECOND_INNER_WHERE )";
fi

INNER_QUERY_GROUPBY="GROUP BY PageRecord_$1.pageIndex"
WHERE="WHERE inq.PageIndex = PageTable_$1.PageIndex"
ORDER="ORDER BY PageName"

SELECT="$SELECT FROM ( $INNER_QUERY $INNER_QUERY_FROM $INNER_QUERY_WHERE $SECOND_INNER_QUERY $INNER_QUERY_GROUPBY ) inq, PageTable_$1"

log_query
run_query
show_query_result
exit 0

