#!/bin/sh
. $NS_WDIR/etc/.netcloud/GCP.cfg

ALLOCATION_ID=$1
GEN_LIST=$2

export DEBUG_LOG_FILENAME=""

DATE=`date "+%Y-%m-%d"`
DEBUG_LOG_FILENAME="$NS_WDIR/webapps/netstorm/logs/gen_inst.netstorm-${DATE}.log"
D_IFS="$IFS"

debug_log()
{
  echo "`date "+%D %H:%M:%S"`|[$ALLOCATION_ID|GCP]$*" >> $DEBUG_LOG_FILENAME
}

cav_gcloud()
{
  CMD="gcloud $* --verbosity=\"error\""
  debug_log "Command: $CMD"

  RESULT=`eval $CMD 2>&1`
  EXIT_STATUS=$?

  debug_log "Result: $RESULT"

  echo "$RESULT"
  return $EXIT_STATUS
}

delete_instance()
{
  NAME=$1
  ZONE=$2

  debug_log "INFO: Delete instance $NAME."
  cav_gcloud compute instances delete "$NAME" --zone=$ZONE --quiet >/dev/null 2>&1

  if [ $? -ne 0 ]; then
    debug_log "ERROR: Failed to delete instance $NAME."
  else
    debug_log "SUCCESS: Instance $NAME is deleted."
  fi
}

#Retry 10 times if instances are up. otherwise exited
check_instance_down_or_not()
{
  debug_log "INFO: Checking if all instances are down or not. Interval is 10 sec and retry count is 30"

  for i in {1..30}
  do
    sleep 10
    debug_log "INFO: Checking if all instances are down or not, retry count = $i"
    UP_INST=`cav_gcloud compute instances list --filter="\"${FILTER_TYPE}:${FILTER}\"" --flatten='"networkInterfaces[].accessConfigs[]"' --format='"csv[no-heading,separator=|](name,networkInterfaces.accessConfigs.natIP)"'`
  
    if [ "X$UP_INST" == "X"  ];then
      break
    fi
  done

  if [ "X$UP_INST" != "X" ];then
    echo "$UP_INST"
  else
    debug_log "SUCCESS: All instances are deleted."
  fi
}

#################################################################################################
#Execution Starts Here
debug_log "nsi_release_gcp_instances $@"
#Set your project
cav_gcloud config set project $PROJECT >/dev/null 2>&1
if [ $? -ne 0 ]; then
  debug_log "ERROR: Failed to add project $PROJECT."
  exit 1
fi

if [ "X$ALLOCATION_ID" != "XNA" ]; then
  FILTER_TYPE="tags"
  FILTER="${ALLOCATION_ID//,/ OR }"    
  IFS=',' ALLOCATION_ID_LIST=($ALLOCATION_ID) IFS="$D_IFS"
else
  FILTER_TYPE="name"
  FILTER="${GEN_LIST//,/ OR }"    
  IFS=',' ALLOCATION_ID_LIST=($GEN_LIST) IFS="$D_IFS"
fi

for ((j = 0; j < ${#ALLOCATION_ID_LIST[@]}; j++))
do
  ALLOCATION_ID=${ALLOCATION_ID_LIST[$j]}
  INST_LIST=`cav_gcloud compute instances list --filter=${FILTER_TYPE}:${ALLOCATION_ID} --format='"csv[no-heading,separator=|](name,zone)"'`
  if [ $? -ne 0 ]; then
     debug_log "ERROR: Failed to Instance list for $ALLOCATION_ID"
     continue
  fi
  IFS=$'\n' INST_LIST=($INST_LIST) IFS="$D_IFS"

  for ((k = 0; k < ${#INST_LIST[@]}; k++))
  do
    IFS='|' INST_LIST_ZONE=(${INST_LIST[$k]}) IFS="$D_IFS"
    INST_NAME=${INST_LIST_ZONE[0]}
    INST_ZONE=${INST_LIST_ZONE[1]}
    delete_instance "$INST_NAME" "$INST_ZONE" &
  done
done

check_instance_down_or_not

exit 0
