#!/bin/sh

. $NS_WDIR/etc/.netcloud/GCP.cfg

DEBUG_LEVEL=1
DEBUG_LOG_FILENAME="$NS_WDIR/webapps/netstorm/logs/gen_inst.netstorm-${DATE}.log"

debug_log()
{
  if [ "X$DEBUG_LEVEL" == "X0" ]; then
    return
  else
    echo "`date "+%D %H:%M:%S"`|[GCP]$*" >> $DEBUG_LOG_FILENAME
  fi
}

debug_log "gcloud config set project $PROJECT"

gcloud config set project $PROJECT >/dev/null 2>&1

if [ "X$1" == "Xview" ]; then
  gcloud compute instances list --flatten="networkInterfaces[].accessConfigs[]" --format="csv[no-heading,separator=|](name,networkInterfaces.accessConfigs.natIP,creationTimestamp.date(),status)"
else
  export CUR_TIMESTAMP=`date +%s`
  gcloud compute instances list --flatten="networkInterfaces[].accessConfigs[]" --format="csv[no-heading,separator=|](name,networkInterfaces.accessConfigs.natIP,creationTimestamp.date('%s'))" | awk -F'|' '{time_diff=ENVIRON["CUR_TIMESTAMP"] - int($3); if(time_diff > 300) print $1"|"$2}'
fi
