#!/bin/sh
# Name  : nsi_add_ipv6_all
# Author: Abhay
# Usage : nsi_add_ipv6_all [load interface]
# This script is used to assign the IP addresses at the time of reboot the machine.
# Only one load inteface argument can be given. Default is all load interfaces

IPV6_ENTRIES=$NS_WDIR/sys/ipv6_entries
NSI_ADD_IPV6=$NS_WDIR/bin/nsi_add_ipv6
CONFIG=`/home/cavisson/work/bin/nsi_show_config`

USER=`whoami`
if [ "X$USER" != "Xcavisson" ];then
    echo "You must be logged in as cavisson user to execute this command"
    exit -1
fi

ARG_LOAD=$1
#Achint - Do we really need this in case of NC? because on controller we dont need IPs.
if [ $CONFIG == 'NS>NO' -o $CONFIG == 'NS' -o $CONFIG == 'NC' ];then
  entity=C
else
  entity=S
fi

#Get IP fields from the IP entries file.
get_ip_fields()
{
  ENTITY=`echo $1 | cut -d "|" -f1`
  NET_ID=`echo $1 | cut -d "|" -f2`
  NET_BITS=`echo $1 | cut -d "|" -f3`
  START_IP=`echo $1 | cut -d "|" -f4`
  END_IP=`echo $1 | cut -d "|" -f5`
  VLAN_ID=`echo $1 | cut -d "|" -f7`
  GATEWAY=`echo $1 | cut -d "|" -f8`
  EXCLUDE_IP=`echo $1 | cut -d "|" -f9`
  LOAD=`echo $1 | cut -d "|" -f10`
}
LOGFILE=/tmp/nsi_add_ipv6_all_log
> $LOGFILE
while read line
do
  if [ "XX$line" == "XX" ];then
    continue
  fi
  get_ip_fields $line
  if [ "$ENTITY" == "$entity" -a "$ENTITY" == "C" ];then
    #Call nsi_add_ipv6 script to assign the IPs.
    if [ "XX$ARG_LOAD" != "XX" ];then
       if [ "$ARG_LOAD" != "$LOAD" ];then  
         continue
       fi
    fi
     echo "Assigning IPs on client : $NSI_ADD_IPV6 $ENTITY $START_IP $END_IP $VLAN_ID $NET_BITS $EXCLUDE_IP $NET_ID $GATEWAY $LOAD" >>$LOGFILE
    `$NSI_ADD_IPV6 $ENTITY $START_IP $END_IP $VLAN_ID $NET_BITS $EXCLUDE_IP $NET_ID $GATEWAY $LOAD`1>/dev/null 2>&1 
  fi
  if [ "$ENTITY" == "$entity" -a $ENTITY == "S" ];then
    #Call nsi_add_ipv6 script to assign the IPs.
    if [ "XX$ARG_LOAD" != "XX" ];then
      if [ "$ARG_LOAD" != "$LOAD" ];then 
        continue 
      fi
    fi
     echo "Assigning IPs on Server : $NSI_ADD_IPV6 R $START_IP $END_IP $VLAN_ID $NET_BITS $EXCLUDE_IP $NET_ID $GATEWAY $LOAD" >>$LOGFILE
    `$NSI_ADD_IPV6 R $START_IP $END_IP $VLAN_ID $NET_BITS $EXCLUDE_IP $NET_ID $GATEWAY $LOAD`1>/dev/null 2>&1
  fi
done <$IPV6_ENTRIES

rm -f $LOGFILE

exit 0

