#!/bin/bash
FILE=$1
OUT_FILE=".tmp_file"

LINE_COUNT=`wc -l $FILE | cut -d ' ' -f 1`

LINE_COUNT=`expr $LINE_COUNT - 1`

head -1 $FILE > $OUT_FILE
tail -$LINE_COUNT $FILE | sort -k 1 -k 2 >> $OUT_FILE
mv $OUT_FILE $FILE
