#!/bin/sh

# Name   : nsi_gen_cmp_rep_set
# Author : Neeraj
# Purpose: 
# Takes input in the format 
#  nsi_gen_cmp_rep_set -t <TestRun number> -T <Template Name> -n <IsNetCloud> -r <Report Set Name> -f <msrDataFile> or <Measurement data> 
#  IsNetCloud : 0 Standalone test 
#               1 Netcloud test
# Exit Values:
#   0 - OK
#   1 - Bad Arguments/Invalid input format
#
# Modification History:
#   07/29/07  Initial version


# This is to set CLASSPATH
export CLASSPATH=$CLASSPATH:$NS_WDIR/webapps/netstorm/WEB-INF/lib/jfreechart-1.0.14.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/java-getopt-1.0.9.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/itext-paulo-154.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/jcommon-1.0.17.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/poi.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/jcommon-1.0.17.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/commons-io-2.2.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/kryo-2.23.0.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/exp4j-0.4.5.jar:.

if [ $# -lt 5 ];then
  echo "Usage: nsi_gen_cmp_rep_set -t <TestRun number> -T <Template Name> -n <IsNetCloud> -r <Report Set Name> -f <msrDataFile> or <Measurement data> ....."
  echo "Test Run Number should be numeric"
  echo "Report SetName must be in double quotes"
  echo "One or more measurement data"
  exit 1 
fi

if [ "XX$NS_WDIR" == "XX" ];then
  echo "NS_WDIR must be defined"
  exit 1
fi

#if [ ! -d $NS_WDIR/logs/TR$1 ];then 
#  echo "Given Test Run number $1 does not exist."
#  exit 1
#fi

#cd $NS_WDIR/webapps/netstorm/WEB-INF/classes
java -cp $CLASSPATH:$NS_WDIR/webapps/netstorm/WEB-INF/lib/netstorm_bean.jar -DNS_WDIR=$NS_WDIR -Djava.awt.headless=true pac1.Bean.CmpRptUsingRtpl $*

exit 0
