#!/bin/sh
# Name  : nsi_get_ext_controller 
# Author: Naveen 
# usage :
#        nsi_get_ext_controller  

CLOUD_CON_FILE=$NS_WDIR/netcloud_controller.dat 

while read line
do

  #Skipping any commented line in file netcloud_controller.dat
  echo $line | grep '^#' >/dev/null
  if [ $? == 0 ];then
    continue
  fi
  
  #Getting the status from the file
  #If ACTIVE then printing the ip and port of the first active controller 
  STATUS=`echo $line | cut -d"|" -f3`   

  if [ "X$STATUS" == "XACTIVE" ];then
    IP_WITH_PORT=`echo $line | cut -d"|" -f2`
    echo "$IP_WITH_PORT"
    exit 0
  fi

done < $CLOUD_CON_FILE

echo "There is no controller which is in Active state"
exit 1
