#!/bin/sh

##################################################################
# Name		: nsi_get_caverr
# Purpose	: This tool will provide occupied CavErr codes
#                 for specific Product and Error.
# Author(s)	: Nisha|Thu Feb 27 17:23:41 IST 2020
###################################################################

# Product Code:
# NS = 10, NO = 11, Agent = 12, NDC = 13, NDP = 14, DBupload = 15, NF = 16, NV = 17, UI = 18

# Error Code:

# Example:
# CavErr[<ProductCode><ErrCode><SeqNum>]: <ErrorMsg>
# For Product = NS, System Error -
#    CavErr[1015001]: Failed to create auto fetch table entry 

ERR_MSG_FILE="ns_error_msg.h"

get_input()
{
  input=""
  while [ "${input}x" = "x" ]
  do
    read input
  done
  echo $input
}

echo -n "Provide Product Name: "
prod_code=`get_input`

echo -n "Error code: "
err_code=`get_input`

grep "CavErr\[${prod_code}${err_code}" ${ERR_MSG_FILE} |cut -d' ' -f2
