#!/bin/sh
# Name  : nsi_syn_netocean

# Author: Achint
# usage : nsi_syn_netocean
# This command is used in copy the ip entries file from NetStrom to NetOcean.When delete or add IPs is done, then this script called to copy updated ip entries file at NetOcean.

SR_ADDRESS=`cat $HOME_DIR/etc/cav.conf | grep "SRAdminIP" | cut -d" " -f2 | cut -d/ -f1`
CONFIG=`grep ^CONFIG $HOME_DIR/etc/cav.conf | awk  '{print $2}'`

#changes for deletion of ip on NO machine
if [ "XX$CONFIG" != "XXNO" ];then
  scp /home/cavisson/work/sys/ip_entries $SR_ADDRESS:/home/cavisson/work/sys/ > /dev/null
fi
