#!/bin/bash
##################################################################
#Purpose : Get Product Key from any Server
#Usage   : nsi_get_product_key <URL> <Username> <Password>
#            URL      - <http/https>://<IP>:<PORT>
#            Username - ACL User
#            Password - ACL User's Password
#NOTE    : Use https, if https is enabled in tomcat setting
#################################################################

PUB_KEY_FILE=""
URL=""
USER='nsrepo.cavisson'
PASS='C@vN$Rep0^2K21'
TIMEOUT=60

if [ "X$1" == "X" ]; then
  echo "Error: URL is not provided."
else
  URL=$1
fi

if [ "X$2" != "X" ]; then
  USER=$2
fi

if [ "X$3" != "X" ]; then
  PASS=$3
fi

OUTPUT=`nsu_encrypt -s "$URL"`
OUTPUT=${OUTPUT//\//_}

PUB_KEY_FILE="$NS_WDIR/.$OUTPUT.pub"

#Create Public Key File
if [ ! -f $PUB_KEY_FILE ]; then
  echo "-----BEGIN PUBLIC KEY-----" > $PUB_KEY_FILE
  PUB_KEY=`curl -ks --max-time ${TIMEOUT} --compressed "${URL}/ProductUI/productSummary/SummaryWebService/getProductName?productKey=null" | awk -F'"publicMetaKey":' '{print $2}' | cut -d'"' -f2`

  if [ "X$PUB_KEY" == "X" ]; then
    echo "ERROR: Failed to get public key from server."
    rm $PUB_KEY_FILE
    exit -1
  else 
    echo "$PUB_KEY" >> $PUB_KEY_FILE
  fi

  echo "-----END PUBLIC KEY-----" >> $PUB_KEY_FILE
fi

#Generate Token
TOKEN=`echo -n ${PASS} | openssl rsautl  -encrypt -inkey $PUB_KEY_FILE -pubin 2> /dev/null | base64 -w 0`

if [ "$?" != 0 -o "X${TOKEN}" == "X" ]; then
  echo "Error: Failed to generate authentication token."
  exit -1
fi

#Get Product Key
BODY="{\"user\":\"${USER}\",\"token\":\"${TOKEN}\"}"

PRODUCT_KEY=`curl -ks --max-time ${TIMEOUT} -d  "${BODY}" -H 'Content-Type: application/json' -X POST "${URL}/DashboardServer/acl/user/authenticateUser?productKey=${USER}&userName=${USER}&isRequestFrmLogin=true" | awk -F'"productKey":' '{print $2}' | cut -d'"' -f2`

if [ "$?" != 0 -o "X${PRODUCT_KEY}" == "X" ]; then
  echo "Error: Failed to get Product Key."
  exit -1
fi

PRODUCT_KEY=${PRODUCT_KEY// /%20}

echo $PRODUCT_KEY
