#!/bin/sh
# Name    : nsi_is_display_gateway_column
# Author  : Achint
# usage   :
#           nsi_is_display_gateway_column
# Purpose : This script will use in to get the value of keyword DUT_LAYER. If the value of DUT_LAYER is 2 then script will echo 1 otherwise will echo 0
# Modification History:
#   07/29/06  Initial version
keyword_value=0
IP_PROPERTIES=$NS_WDIR/sys/ip_properties

if [ ! -f $IP_PROPERTIES ]; then
  echo 0
  exit 0
fi

#Search DUT_LAYER in the file

keyword=`grep "^DUT_LAYER" $IP_PROPERTIES` >>/dev/null
#Take the value of keyword, if keyword founf
if [ $? -eq 0 ];then
 keyword_value=`echo $keyword | cut -d" " -f2`
fi

#Take the value of keyword
#Show 0 or 1 depending upon the keyword value

if [ $keyword_value == 2 ]; then
  echo 1
else
  echo 0
fi 
exit 0
