#!/bin/bash
# Name      : nsi_get_client
# Author    : Atul
# Purpsose  : To show Client Ip and Port.
# Usage : ./nsi_get_client
# Exit Values:
#    0 - OK
#   -1 - Bad Arguments
#   -2 - Total number of IP Addresses are less than number of IP Addresses (For -l option)
# Modification History:
#    05/29/07: Atul - Initial Version

if [ "XX" = "XX$NS_WDIR" ]
then
  NS_WDIR=/home/cavisson/work
fi

conf="$NS_WDIR/sys/master.conf"

echo "CLIENT IP|PORT"
if [ ! -f $conf ];then
#  echo "Conf file not found, $conf"
  exit 0 
fi
#cat $conf | grep -w "^CLIENT" | awk '{print $2"|"$3}'
while read line
  do
    echo $line | grep "^#" >/dev/null
    if [ $? -eq 0 ]; then
      continue
    elif [ "XX$line" == "XX"  ];then
      continue
    else
      echo $line | grep -w "^CLIENT" > /dev/null
      if [ $? -eq 0 ]; then
        ip=`echo $line | cut -d " " -f2`
        port=`echo $line | cut -d " " -f3`
        if [ "XX$port" == "XX" ];then
          port="7891"
        fi
        echo $ip"|"$port
      fi
    fi
  done < $conf 
exit 0
