#!/bin/bash

usage()
{
  echo
  echo "$*"
  echo
  echo "USAGE:"
  echo "====="
  echo
  echo "$0 -t <TRNUM> -s <tablespace>" 
  echo 
  echo "Where"
  echo " testrun is test run number, which is mandatory argument."
  echo " please provide tablespace if your environment is multidisk"
  exit 1
}

show_error()
{
  echo $Error | grep "ERROR" >/dev/null
  if [ $? == 0  ]; then
    echo "Can't create column/index or primary key on table"
    echo $Error
  fi
}

while getopts t:s: option
do
  case $option in
    t) TRNUM="$OPTARG" ;;
    s) tablespace="$OPTARG" ;;
    *) usage "Please pass some arguement" ;;
  esac
done

if [ "X$TRNUM" == "X" ]
then
  usage "please provide test run "
fi 

if [ "X$tablespace" != "X" ]
then
  tablespace="TABLESPACE $tablespace"
else
  tablespace=" "
fi

Error=`psql test cavisson 2>&1 <<+
drop index ndsql_sqlq_$TRNUM;
+`


Error=`psql test cavisson 2>&1 <<+
create index metadata_ENTITYID_$TRNUM on metadata_$TRNUM (Entityid) $tablespace;
create index metadata_METATYPE_$TRNUM on metadata_$TRNUM (MetaType) $tablespace; 
+`
show_error

Error=`psql test cavisson 2>&1 <<+
create index ndtier_TIERNAME_$TRNUM on ndtier_$TRNUM (TierName) $tablespace;
create index ndtier_TIERID_$TRNUM on ndtier_$TRNUM (TierID) $tablespace;
+`
show_error

Error=`psql test cavisson 2>&1 <<+
create index ndappserver_SERVERNAME_$TRNUM on ndappserver_$TRNUM (ServerName) $tablespace;
create index ndappserver_SERVERID_$TRNUM on ndappserver_$TRNUM (ServerID) $tablespace;
+`
show_error

Error=`psql test cavisson 2>&1 <<+
create index ndappinstance_APPNAME_$TRNUM on ndappinstance_$TRNUM (appName) $tablespace;
create index ndappinstance_APPID_$TRNUM on ndappinstance_$TRNUM (APPID) $tablespace;
+`
show_error

Error=`psql test cavisson 2>&1  <<+
create table ndcustomdata_$TRNUM(
             timestamp bigint,
             FlowPathInstance bigInt,
             NameId int,
             HTTPHeadername text,
             ValueType smallint,
             ValueInt bigint,
             HTTPHeadervalue text,
             TierId smallInt,
             ServerId smallInt,
             appId int);


CREATE INDEX ndcustomdata_FPI_$TRNUM on ndcustomdata_$TRNUM(FlowpathInstance) $tablespace;
CREATE INDEX ndcustomdata_FPI_TIME_$TRNUM on ndcustomdata_$TRNUM(FlowpathInstance, TimeStamp) $tablespace;
CREATE INDEX ndcustomdata_NAME_$TRNUM on ndcustomdata_$TRNUM(NameId) $tablespace;
CREATE INDEX ndcustomdata_VALUE_$TRNUM on ndcustomdata_$TRNUM(ValueInt) $tablespace;
CREATE INDEX VALUETYPE on ndcustomdata_$TRNUM(ValueType) $tablespace;

+`
show_error

Error=`psql test cavisson 2>&1  <<+
alter table Flowpath_$TRNUM add column HTTPMethod smallint;
+`


Error=`psql test cavisson 2>&1  <<+
alter table Flowpath_$TRNUM add column EntryPointId int;
+`


Error=`psql test cavisson 2>&1  <<+
alter table Flowpath_$TRNUM add column DBCallCounts int;
+`


Error=`psql test cavisson 2>&1  <<+
alter table Flowpath_$TRNUM add column HTTPCalloutCount int;
+`


Error=`psql test cavisson 2>&1  <<+
alter table Flowpath_$TRNUM add column JMSCallCount int;
+`


Error=`psql test cavisson 2>&1  <<+
alter table Flowpath_$TRNUM add column ExceptionCount int;
+`


Error=`psql test cavisson 2>&1  <<+
alter table Flowpath_$TRNUM add column CoherenceCount int;
+`


Error=`psql test cavisson 2>&1  <<+
alter table Flowpath_$TRNUM add column NDSessionId bigint;
+`


Error=`psql test cavisson 2>&1  <<+
alter table Flowpath_$TRNUM add column NVSessionId bigint;
+`


Error=`psql test cavisson 2>&1  <<+
alter table Flowpath_$TRNUM add column NVPageId smallint;
+`

Error=`psql test cavisson 2>&1  <<+
alter table Flowpath_$TRNUM add column Thread varchar(256);
+`

Error=`psql test cavisson 2>&1  <<+
alter table Flowpath_$TRNUM add column FlowpathType smallint;
+`

Error=`psql test cavisson 2>&1  <<+
alter table Flowpath_$TRNUM add column WaitTime bigint;
+`

Error=`psql test cavisson 2>&1  <<+
alter table Flowpath_$TRNUM add column SyncTime bigint;
+`

Error=`psql test cavisson 2>&1  <<+
alter table Flowpath_$TRNUM add column IOTime bigint;
+`

Error=`psql test cavisson 2>&1  <<+
alter table Flowpath_$TRNUM add column SuspensionTime bigint;
+`

Error=`psql test cavisson 2>&1 <<+
create index Flowpath_NDSESSID_$TRNUM on Flowpath_$TRNUM (NDSessionId) $tablespace; 
+`
show_error

Error=`psql test cavisson 2>&1 <<+
create index ndhttpheadermetadata_HDERID_$TRNUM on ndhttpheadermetadata_$TRNUM (HeaderID) $tablespace;
+`
show_error

Error=`psql test cavisson 2>&1 <<+
alter table NDBciArg_$TRNUM add column WallTime bigint;
alter table NDBciArg_$TRNUM add column SyncTime bigint;
alter table NDBciArg_$TRNUM add column IOTime bigint;
alter table NDBciArg_$TRNUM add column SuspensionTime bigint;
+`


Error=`psql test cavisson 2>&1 <<+
alter table NDMethodTiming_$TRNUM add column CumWaitTime bigint;
alter table NDMethodTiming_$TRNUM add column CumSyncTime bigint;
alter table NDMethodTiming_$TRNUM add column CumIOTime bigint;
alter table NDMethodTiming_$TRNUM add column CumSuspensionTime bigint;
alter table NDMethodTiming_$TRNUM add column CumSelfWaitTime bigint;
alter table NDMethodTiming_$TRNUM add column CumSelfSyncTime bigint;
alter table NDMethodTiming_$TRNUM add column CumSelfIOTime bigint;
alter table NDMethodTiming_$TRNUM add column CumSelfSuspensionTime bigint;
+`

Error=`psql test cavisson 2>&1 <<+
alter table NDSQLTiming_$TRNUM ALTER COLUMN CumSQLExecTime type numeric;
alter table NDSQLTiming_$TRNUM ALTER COLUMN Min type numeric;
alter table NDSQLTiming_$TRNUM ALTER COLUMN Max type numeric;
+`

Error=`psql test cavisson 2>&1 <<+
alter table NDIPResourceTiming_$TRNUM ALTER COLUMN CumResourceExecTime type numeric;
alter table NDIPResourceTiming_$TRNUM ALTER COLUMN Min type numeric;
alter table NDIPResourceTiming_$TRNUM ALTER COLUMN Max type numeric;
+`

Error=`psql test cavisson 2>&1 <<+
alter table NDAPPINSTANCE_$TRNUM add column instance_type text;
+`

Error=`psql test cavisson 2>&1 <<+
alter table Flowpath_$TRNUM ALTER COLUMN ServerIndex type int;
alter table Flowpath_$TRNUM ALTER COLUMN AppIndex type int;
alter table NDCustomData_$TRNUM ALTER COLUMN ServerId type int;
alter table NDAppLogs_$TRNUM ALTER COLUMN ServerIndex type int;
alter table NDAppLogs_$TRNUM ALTER COLUMN AppIndex type int;
alter table NDExceptions_$TRNUM ALTER COLUMN ServerIndex type int;
alter table NDExceptions_$TRNUM ALTER COLUMN AppIndex type int;
alter table NDMethodTiming_$TRNUM ALTER COLUMN ServerIndex type int;
alter table NDMethodTiming_$TRNUM ALTER COLUMN AppIndex type int;
alter table NDSQLTiming_$TRNUM ALTER COLUMN ServerIndex type int;
alter table NDSQLTiming_$TRNUM ALTER COLUMN AppIndex type int;
alter table NDSQLRecord_$TRNUM ALTER COLUMN ServerIndex type int;
alter table NDSQLRecord_$TRNUM ALTER COLUMN AppIndex type int;
+`

Error=`psql test cavisson 2>&1 <<+
alter table Flowpath_$TRNUM add column QTimeInMS bigint;
+`

Error=`psql test cavisson 2>&1 <<+
create index Flowpath_PFPI_$TRNUM on Flowpath_$TRNUM (PrevFlowPathInstance) $tablespace;
create index Flowpath_FTYPE_$TRNUM on Flowpath_$TRNUM (FlowpathType) $tablespace;
create index Flowpath_TINDEX_$TRNUM on Flowpath_$TRNUM (TierIndex) $tablespace;
+`
show_error
Error=`psql test cavisson 2>&1 <<+
ALTER TABLE ndtier_$TRNUM ADD PRIMARY KEY (TierID);
ALTER TABLE ndtier_$TRNUM ADD UNIQUE(tiername);
ALTER TABLE ndappserver_$TRNUM ADD PRIMARY KEY (ServerName,ServerID,TierID);
ALTER TABLE ndappinstance_$TRNUM ADD PRIMARY KEY (appName,appID,ServerID,TierID);
DROP INDEX flowpath_fpi_fpbgnts_$TRNUM;
DROP INDEX ndmethodtiming_mtdid_strttm_$TRNUM;
DROP INDEX ndipresourcetiming_fpi_srbtm_$TRNUM;
DROP INDEX ndipresourcetiming_srbtm_$TRNUM;
DROP INDEX urlrecord_urlid_sttm_$TRNUM;
DROP INDEX ndsqltiming_fpi_ssqlbtm_$TRNUM;
+`
show_error
Error=`psql test cavisson 2>&1  <<+
alter table PageRBUDetailRecord_$TRNUM add column PageStatus int;
+`
show_error
Error=`psql test netstorm 2>&1  <<+
alter table PageRBUDetailRecord_$TRNUM add column SessionInstance int;
+`
show_error
Error=`psql test netstorm 2>&1  <<+
alter table PageRBUDetailRecord_$TRNUM add column DeviceInfo text;
+`
show_error
Error=`psql test netstorm 2>&1  <<+
alter table PageRBUDetailRecord_$TRNUM add column PerformanceTraceMode smallint;
+`
show_error
Error=`psql test netstorm 2>&1  <<+
alter table PageRBUDetailRecord_$TRNUM add column DOMElement int;
+`
show_error
Error=`psql test netstorm 2>&1  <<+
alter table PageRBUDetailRecord_$TRNUM add column BackendRespTime int;
+`
show_error
Error=`psql test netstorm 2>&1  <<+
alter table PageRBUDetailRecord_$TRNUM add column BytesReceivedBeforeDomContent int;
+`
show_error
Error=`psql test netstorm 2>&1  <<+
alter table PageRBUDetailRecord_$TRNUM add column BytesReceivedBeforeOnLoad int;
+`
show_error
Error=`psql test netstorm 2>&1  <<+
alter table PageRBUDetailRecord_$TRNUM add column FirstPaint int;
+`
show_error
Error=`psql test netstorm 2>&1  <<+
alter table PageRBUDetailRecord_$TRNUM add column FirstContentfulPaint int;
+`
show_error
Error=`psql test netstorm 2>&1  <<+
alter table PageRBUDetailRecord_$TRNUM add column LargestContentfulPaint int;
+`
show_error
Error=`psql test netstorm 2>&1  <<+
alter table PageRBUDetailRecord_$TRNUM add column CumLayoutShift float;
+`
show_error
Error=`psql test netstorm 2>&1  <<+
alter table PageRBUDetailRecord_$TRNUM add column TotalBlockingTime int;
+`
show_error

Error=`psql test netstorm 2>&1  <<+
alter table ActualServerTable_$TRNUM add column GroupIdx int;
+`

Error=`psql test cavisson 2>&1 <<+
create index Flowpath_$TRNUM_FPI_ENDTS on Flowpath_$TRNUM (FlowPathEndTimestamp) $tablespace;
+`
show_error

Error=`psql test cavisson 2>&1 <<+
create index Flowpath_$TRNUM_RSTIME on Flowpath_$TRNUM (ResponseTime) $tablespace;
+`
show_error

Error=`psql test cavisson 2>&1  <<+
alter table Flowpath_$TRNUM add column SelfResponseTime bigint, add column ParentFlowPathInstance bigint;
+`
show_error

Error=`psql test cavisson 2>&1  <<+
alter table Flowpath_$TRNUM add column BackendId int[], add column BackendMaxRespTime int[];
+`
show_error

Error=`psql test cavisson 2>&1  <<+
alter table ndappserver_$TRNUM add column discoveryTime bigint, add column lastDisconnectedTime bigint;
+`
show_error

Error=`psql test cavisson 2>&1  <<+
alter table ndappinstance_$TRNUM add column discoveryTime bigint, add column lastDisconnectedTime bigint;
+`
show_error


Error=`psql test cavisson 2>&1  <<+
alter table ndsqltiming_$TRNUM add column backendid int;
+`
show_error


Error=`psql test cavisson 2>&1  <<+
create index ndsqltiming_BCKDIDX_$TRNUM on ndsqltiming_$TRNUM (backendid) $tablespace;
+`
show_error


Error=`psql test cavisson 2>&1  <<+
alter table Flowpath_$TRNUM add column Garagecollectionover int;
+`
show_error

Error=`psql test cavisson 2>&1  <<+
alter table Flowpath_$TRNUM add column DynamicLoggingFlag int;
+`
show_error

Error=`psql test cavisson 2>&1  <<+
alter table Flowpath_$TRNUM add column TraceRequest int;
+`
show_error

Error=`psql test cavisson 2>&1  <<+
alter table NDAppInstance_$TRNUM add column attributes jsonb;
+`
show_error
