#!/bin/sh
###########################################################################################
# Name    : nsi_compile_script
# Author  : Naveen Raina
# Purpose : This is a shell which is used to compile scripts.
# Usage   : nsi_compile_script -s <Workspace/Profile/Project/Subproject/Script Name> -o compile 
#
# Here,-s : s option specifies the path of script.
#      -o : 1) if "compile" is given in this option then the given script will be compiled
#              successfully and no test run is generated.
#           2) if "DoNotCompile" option is given then this will run the test but not compile
#              the scripts.
###########################################################################################

usage()
{
  echo "ERROR: In correct usage"
  echo "Usage:"
  echo "nsi_compile_script "
  echo "  -s <Workspace/Profile/Project/Subproject/Script Name> "
  echo "  -o used to compile the script "
  echo "  -v used to disable script validate "
  exit -1
}

#defaults

NumUsers=1
TEST_NAME="NA"
compile_script="DoNotCompile"
NETSTORM_BIN="bin/netstorm"
PRE_TEST_CHECK_RETRY_COUNT=0
DISABLE_SCRIPT_VALIDATION=0

export LD_LIBRARY_PATH=$NS_WDIR/thirdparty/lib

chk_args_of_option()
{
  if [ "X$2" == "X" ];then
    echo "Option $1 required a value."
    usage
    exit -1
  fi
}

while [ "$1" != "" ];do
  case $1 in
    "-s")
        shift
      chk_args_of_option "-s" "$1"
        ARGUMENT=$1;;
    "-o")
        shift
      chk_args_of_option "-o" "$1"
        compile_script=$1;;
    "-v")
        DISABLE_SCRIPT_VALIDATION=1;;
    -*) usage "Invalid option $1";;
    *) usage;;
  esac
  shift
done

Workspace=`echo "$ARGUMENT" | awk -F'/' '{print $1}'`
Profile=`echo "$ARGUMENT" | awk -F'/' '{print $2}'`
ProjectName=`echo "$ARGUMENT" | awk -F'/' '{print $3}'`
SubprojectName=`echo "$ARGUMENT" | awk -F'/' '{print $4}'`
ScriptName=`echo "$ARGUMENT" | awk -F'/' '{print $5}'`

if [ "XX$Workspace" == "XX" -o "XX$Profile" == "XX" -o "XX$ProjectName" == "XX" -o "XX$SubprojectName" == "XX" -o "XX$ScriptName" == "XX" ];then
  usage
fi


if [ "XX$compile_script" == "XX" ];then
  usage
fi

DISABLE_SCRIPT_VALIDATION_OPTION=""
if [ "X$DISABLE_SCRIPT_VALIDATION" = "X1" ];then
  DISABLE_SCRIPT_VALIDATION_OPTION="-v"
fi

#Check and get login user name
USER_NAME=`whoami 2>/dev/null`
if [ $? != 0 ];then
  echo "Error: Unable to get the real user name"
  exit 1
fi

if [ "XX$NS_WDIR" == "XX" ];then
   NS_WDIR="/home/cavisson/work"
fi

NS_RTA_DIR="workspace/$Workspace/$Profile/cavisson"
export NS_RTA_DIR
NS_TA_DIR="$NS_WDIR/$NS_RTA_DIR/$ProjectName/$SubprojectName"

#Creating test script file for each username since any user can create scenario file for testing of script
ScenFileName="$NS_TA_DIR/scenarios/$USER_NAME.TestScript.conf"
> $ScenFileName

[ "X$compile_script" == "XDoNotCompile" ] && echo "DISABLE_SCRIPT_VALIDATION $DISABLE_SCRIPT_VALIDATION " >> $ScenFileName
echo "SGRP TestGroup NA Internet 0 $ProjectName/$SubprojectName/$ScriptName $NumUsers" >> $ScenFileName

if [ $? != 0 ];then
  echo "Error: Not permitted to create scenario in $ProjectName/$SubprojectName"
  exit 1
fi

if [ $PRE_TEST_CHECK_RETRY_COUNT == 0 ]; then
  if [ "$TEST_NAME" == "NA" ]; then
    echo "Starting netstorm using - nohup $NETSTORM_BIN -c $ScenFileName -o $compile_script $DISABLE_SCRIPT_VALIDATION_OPTION " >/dev/null
    $NETSTORM_BIN  -c $ScenFileName -o $compile_script $DISABLE_SCRIPT_VALIDATION_OPTION
  else 
    echo "Starting netstorm using - nohup $NETSTORM_BIN -c $ScenFileName -o $compile_script $DISABLE_SCRIPT_VALIDATION_OPTION " >/dev/null
    $NETSTORM_BIN  -c $ScenFileName -o $compile_script $DISABLE_SCRIPT_VALIDATION_OPTION
  fi
else
  if [ "$TEST_NAME" == "NA" ]; then
    echo "Starting netstorm using - nohup $NETSTORM_BIN -c $ScenFileName -o $compile_script $DISABLE_SCRIPT_VALIDATION_OPTION " >/dev/null
    $NETSTORM_BIN -c $ScenFileName -o $compile_script $DISABLE_SCRIPT_VALIDATION_OPTION
  else
    echo "Starting netstorm using - nohup $NETSTORM_BIN -c $ScenFileName -o $compile_script $DISABLE_SCRIPT_VALIDATION_OPTION " >/dev/null
    $NETSTORM_BIN -c $ScenFileName -o $compile_script $DISABLE_SCRIPT_VALIDATION_OPTION
  fi
fi


exit $?

