#!/bin/sh

##########################################################################
# Program : create_error_table.sh  \
#
# Purpose : This shell will do following task..
#          (1) Create ect.csv file into TRxxx directory
#              Formate of ect.csv is...
#                Obj_type,error_code,error_msg
#                here: obj_type: URL --> 0
#                                Page--> 1
#                                Tx  --> 2
#                                Sess--> 3
#              ex:
#                0,1,success
#          (2) Create ERRORCODETABLE
#          (3) Fill import the data into table
#          
# Author  : Nikita Pandey
# Date    : 29 March 2012
# Modified: -
##########################################################################

#Set the environment variable NS_WDIR if not set
if [ "XX" == "XX$NS_WDIR" ];then
  NS_WDIR=/home/cavisson/work
fi

#Variable's declaraction and definition
TRNUM=$1
ERR_CSV_FILE="$NS_WDIR/logs/$TRNUM/reports/csv/ect.csv"
#ERR_CSV_FILE="ect.csv"

#Fill err.csv file
#For obj_type URL(0)
>$ERR_CSV_FILE
nsu_get_errors 0 1| sed 's/ //g' | awk -F'-' '{print "0,"$1","$2}' >> $ERR_CSV_FILE

#For obj_type Page(1)
nsu_get_errors 1 1| sed 's/ //g' | awk -F'-' '{print "1,"$1","$2}' >> $ERR_CSV_FILE

#For obj_type Transaction(2)
nsu_get_errors 2 1| sed 's/ //g' | awk -F'-' '{print "2,"$1","$2}' >> $ERR_CSV_FILE

#for obj_type Sess(3)
nsu_get_errors 3 1| sed 's/ //g' | awk -F'-' '{print "3,"$1","$2}' >> $ERR_CSV_FILE
