#! /bin/sh

# Basename is exported from nsi_upgrade shell
export WORK=$BASENAME

RELEASE_CMD="nsi_get_linux_release_ex"
DISTRO=`$RELEASE_CMD -d`

#msgout_both "############################################################"
if [ "X$LPS_ROOT" = "X" ];then
  export LPS_ROOT=/home/cavisson/work/lps
  export LPS_CMD=lps
fi
msgout_both "Start lps upgradation LPS_CMD = $LPS_CMD"
if [ -f /etc/init.d/$LPS_CMD ];then
  msgout_both "Stopping lps releated processes"
  /etc/init.d/$LPS_CMD stop
fi

#sudo update-rc.d -f $LPS_CMD remove >/dev/null 2>&1

mkdir -p $LPS_ROOT
cd $LPS_ROOT

msgout_both "Removing directories of old version."
rm -rf bin etc

msgout_both "Uncompressing tar file - $GZ"
cp $NS_WDIR/.rel/$GZ .
tar xvzf $GZ >> $LOG_FILE_NAME
rm $GZ

if [ "$?" != 0 ];then
  msgout_both "Error: Error in uncompressing the $GZ"
  exit 1
fi

cp -r lps/* .
rm -rf lps
#Change perm to 777 so that custom monitor (remote) can open log files if not running as root
# DO it after untar as tar also has logs dir
mkdir -p logs
chmod 777 logs

if [ ! -f "$LPS_ROOT/conf/lps.conf" ];then
  mkdir -p  $LPS_ROOT/conf
  cp sample/lps.conf  conf/
  if [ "X$LPS_LISTEN_PORT" != "X" ];then
    sed -i "s/PORT 7892/PORT $LPS_LISTEN_PORT/g" conf/lps.conf
  fi
fi

#if [ ! -f "$LPS_ROOT/conf/.db_mon_config.json" ];then
  cp sample/.db_mon_config.json  conf/
#fi

#msgout_both "Copying lps startup shell to /etc/init.d/$LPS_CMD"
#pwd
#echo "Copying lps startup shell to /etc/init.d/$LPS_CMD"
  #sudo cp bin/lps /etc/init.d/$LPS_CMD
  #sudo chmod +x /etc/init.d/$LPS_CMD

  #Adding LSB headers to the init script so as to remove warning coming in build
#  echo -e "### BEGIN INIT INFO\n# Provides: $LPS_CMD\n# Required-Start:\n# Required-Stop:\n# Default-Start:\n# Default-Stop:\n# Short-Description: start|stop|restart|show|version|show_monitors|show_pid $LPS_CMD\n# Description: Starting Log Parsing System Server (HPD)\n### END INIT INFO\n" >>/etc/init.d/$LPS_CMD
#if [ "X$LPS_CMD" != "lps" ];then
#  sudo sed -i "s/export LPS_ROOT=\/home\/cavisson\/work\/lps/export LPS_ROOT=\/home\/cavisson\/$WORK\/lps/g" /etc/init.d/$LPS_CMD
#  sudo sed -i "s/export LPS_CMD=lps/export LPS_CMD=$LPS_CMD/g" /etc/init.d/$LPS_CMD
#  sudo sed -i "s/export NS_CONTROLLER_NAME=work/export NS_CONTROLLER_NAME=$WORK/g" /etc/init.d/$LPS_CMD
#  sudo cp /etc/init.d/$LPS_CMD bin/lps 
#fi
cp /etc/init.d/$LPS_CMD bin/lps
#Change the directory owner:group
#chown -R cavisson:cavisson ../lps

#Updating lps service
sudo $CavService $BASENAME 5 lps

#msgout_both "Starting lps Server"
/etc/init.d/$LPS_CMD start
#sudo update-rc.d $LPS_CMD defaults
exit 0

