#!/bin/bash

if [ $# -lt 4 ];then
        echo $#
	echo "Usage: ./nsu_get_8x tr-num obj-type cildidx sessionInstance ..."
	exit 1
fi

if [ $2 -eq 0 -a $# -ne 6 ];then
	echo "Usage: ./nsu_get_8x tr-num 0  ChildIdex sessionInstance pageInstance UrlIndex"
	exit 1
elif [ $2 -eq 1 -a $# -ne 5 ];then
	echo "Usage: ./nsu_get_8x tr-num 1  ChildIdex sessionInstance pageInstance"
	exit 1
elif [ $2 -eq 2 -a $# -ne 5 ];then
	echo "Usage: ./nsu_get_8x tr-num 2  ChildIdex sessionInstance TxInstance"
	exit 1
fi

TRNUM=$1
ECT_FLAG=0

if [ "XX" == "XX$NS_WDIR" ]
then
  NS_WDIR=/home/cavisson/work
fi

. $NS_WDIR/bin/nsi_db_utils
set_query_files $TRNUM
#set_debug_level_from_config

#args TR-NUM obj-tyepe ...
#args: TR-NUM  0 Child-idx sIidx  pIidx urlidex
#args: TR-NUM  1 Child-idx sIidx  pIidx
#args: TR-NUM  2 Child-idx sIidx  tIidx
#args: TR-NUM  3 Child-idx sIidx 

# this check is used to run old query for older TR where 40 fields were coming
if [ -s $NS_WDIR/logs/TR$TRNUM/reports/csv/urc.csv ]; then

  NOOF_FIELDS_URC=`awk -F ',' '{print NF}' $NS_WDIR/logs/TR$TRNUM/reports/csv/urc.csv | head -1`
  if [ "X$NOOF_FIELDS_URC" == "X40" ]; then
    nsi_get_8x_old_tr $ARGS
    exit 0
  fi
fi

#Add obj name
if [ $2 -eq 0 ];then
    OBJ="UrlRecord_$1"
    WHERE="WHERE  UrlRecord_$1.PageInstance = $5
        AND UrlRecord_$1.UrlIndex = $6 AND"
    INST="UrlIndex"
elif [ $2 -eq 1 ];then
    OBJ="PageRecord_$1"
    WHERE="WHERE  UrlRecord_$1.PageInstance = $5 AND"
    INST="PageIndex"
elif [ $2 -eq 2 ];then
    OBJ="TransactionRecord_$1"
    WHERE="WHERE  UrlRecord_$1.TransactionIndex = $OBJ.TransactionIndex AND UrlRecord_$1.TxInstance = $5 AND UrlRecord_$1.TransactionIndex IS NOT NULL AND"
  if [ -s $NS_WDIR/logs/TR$TRNUM/reports/csv/tprc.csv  ];then
     WHERE="WHERE  TransPageRecord_$1.TransactionIndex = $OBJ.TransactionIndex AND $OBJ.TxInstance = $5 AND TransPageRecord_$1.TransactionIndex IS NOT NULL AND"
#    FROM="$FROM, TransPageRecord_$TRNUM"
  fi
    INST="TransactionIndex"
elif [ $2 -eq 3 ];then
    OBJ="SessionRecord_$1"
    WHERE="WHERE "
    INST="SessionIndex"
else
    echo "Invalid object-type (valid values 0-3)"
    exit 1
fi
#case 1: When ND is disable and ect.csv file is not present in TR
if [ -f $NS_WDIR/logs/TR$TRNUM/reports/csv/ect.csv ];then
ECT_FLAG=1
fi
check_is_nd_enabled
#ISND=`cat $NS_WDIR/logs/TR$TRNUM/sorted_*.conf | grep G_ENABLE_NET_DIAGNOSTICS | cut -d ' ' -f3`
if [ $ISND -ne 1 -a $ECT_FLAG -ne 1 ];then
  SELECT="SELECT URLRecord_$1.PageInstance, PageName, UrlName, URLRecord_$1.StartTime,
        ConnectDuration,
        SSLHandshakeDuration,
        WriteCompleteDuration,
        FirstByteRcdDuration,
        RequestCompleteDuration,
        URLRecord_$1.Status,
        HttpResponseCode,
        AppBytesRcd,
        ConReused,
        HttsReqReused,
        ConnectionNumber,
        URLRecord_$1.FlowPathInstance"

  FROM="FROM  URLRecord_$1, PageTable_$1, URLTable_$1"
  WHERE="$WHERE UrlRecord_$1.PageIndex = PageTable_$1.PageIndex
      AND URLRecord_$1.URLIndex = URLTable_$1.URLIndex
      AND $OBJ.ChildIndex = $3
      AND $OBJ.SessionInstance = $4 
      AND UrlRecord_$1.pageindex = PageTable_$1.pageindex"
  if [ $2 -eq 1 ];then
    WHERE="$WHERE AND PageRecord_$1.ChildIndex = UrlRecord_$1.ChildIndex AND 
    PageRecord_$1.SessionInstance = UrlRecord_$1.SessionInstance AND UrlRecord_$1.PageInstance = PageRecord_$1.PageInstance"
    FROM="$FROM, $OBJ"
  fi
  if [ $2 -eq 2 ];then
    WHERE="$WHERE AND TransactionRecord_$1.ChildIndex = UrlRecord_$1.ChildIndex
      AND TransactionRecord_$1.SessionInstance = UrlRecord_$1.SessionInstance"
    FROM="$FROM, $OBJ"
  fi
  if [ $2 -eq 3 ];then
    WHERE="$WHERE AND SessionRecord_$1.SessionInstance = UrlRecord_$1.SessionInstance 
           AND SessionRecord_$1.ChildIndex = UrlRecord_$1.ChildIndex"
    FROM="$FROM, $OBJ"
  fi
  ORDER="ORDER BY StartTime"
fi

#Case2: When ND is disable but ect.csv file is present in TR
StatusFlag=0
if [ $ECT_FLAG -eq 1  -a $ISND -ne 1 ];then
SELECT="SELECT URLRecord_$1.PageInstance, PageName, UrlName, URLRecord_$1.StartTime,
        ConnectDuration,
        SSLHandshakeDuration,
        WriteCompleteDuration,
        FirstByteRcdDuration,
        RequestCompleteDuration,
        ErrorName,
        HttpResponseCode,
        AppBytesRcd,
        ConReused,
        HttsReqReused,
        ConnectionNumber,
        FlowPathInstance"
FROM="FROM  URLRecord_$1, PageTable_$1, URLTable_$1, ErrorCodes_$1"
if [ $2 -eq 0 ];then
WHERE="$WHERE UrlRecord_$1.PageIndex = PageTable_$1.PageIndex
      AND URLRecord_$1.URLIndex = URLTable_$1.URLIndex
      AND ChildIndex = $3
      AND SessionInstance = $4
      AND ErrorCodes_$1.errorcode =  URLRecord_$1.Status AND ErrorCodes_$1.ObjectType = $2
      AND UrlRecord_$1.pageindex = PageTable_$1.pageindex"
fi

if [ $2 -eq 1 ];then
FROM="$FROM, $OBJ"
WHERE="$WHERE $OBJ.ChildIndex = $3
      AND $OBJ.SessionInstance = $4
      AND  $OBJ.PageIndex = UrlRecord_$1.PageIndex
      AND $OBJ.PageInstance = UrlRecord_$1.PageInstance
      AND $OBJ.ChildIndex = UrlRecord_$1.ChildIndex
      AND $OBJ.SessionInstance = UrlRecord_$1.SessionInstance
      AND $OBJ.PageIndex = PageTable_$1.PageIndex
      AND URLRecord_$1.URLIndex = URLTable_$1.URLIndex
      AND ErrorCodes_$1.errorcode = URLRecord_$1.Status 
      AND ErrorCodes_$1.ObjectType = 0
      AND UrlRecord_$1.pageindex = PageTable_$1.pageindex"

fi

if [ $2 -eq 2  ];then
FROM="$FROM, $OBJ"
WHERE="$WHERE 
      $OBJ.ChildIndex = $3
      AND $OBJ.SessionInstance = $4
      AND $OBJ.ChildIndex = UrlRecord_$1.ChildIndex
      AND $OBJ.SessionInstance = UrlRecord_$1.SessionInstance
      AND URLRecord_$1.URLIndex = URLTable_$1.URLIndex
      AND ErrorCodes_$1.errorcode = UrlRecord_$1.Status
      AND ErrorCodes_$1.ObjectType = 0
      AND UrlRecord_$1.pageindex = PageTable_$1.pageindex"
  if [ -s $NS_WDIR/logs/TR$TRNUM/reports/csv/tprc.csv  ];then
    WHERE="$WHERE AND TransPageRecord_$TRNUM.pageinstance = URLRecord_$TRNUM.pageinstance AND URLRecord_$TRNUM.childindex = TransPageRecord_$TRNUM.childindex AND TransPageRecord_$TRNUM.sessioninstance = URLRecord_$TRNUM.sessioninstance"
    FROM="$FROM, TransPageRecord_$TRNUM"
  fi
fi
if [ $2 -eq 3  ];then
FROM="$FROM, $OBJ"
WHERE="$WHERE $OBJ.ChildIndex = $3
      AND $OBJ.SessionInstance = $4
      AND $OBJ.ChildIndex = UrlRecord_$1.ChildIndex
      AND $OBJ.SessionInstance = UrlRecord_$1.SessionInstance
      AND URLRecord_$1.URLIndex = URLTable_$1.URLIndex
      AND ErrorCodes_$1.errorcode = UrlRecord_$1.Status
      AND ErrorCodes_$1.ObjectType = 0
      AND UrlRecord_$1.pageindex = PageTable_$1.pageindex"
fi

ORDER="ORDER BY StartTime"
fi
#echo "ISND= $ISND,ECT_FLAG = $ECT_FLAG"
#Case3: When Nd is enable and ect.csv is not present in TR
if [ $ISND -eq 1 -a $ECT_FLAG -eq 0 ];then
SELECT="SELECT URLRecord_$1.PageInstance, PageName, UrlName, URLRecord_$1.StartTime,
        ConnectDuration,
        SSLHandshakeDuration,
        WriteCompleteDuration,
        FirstByteRcdDuration,
        RequestCompleteDuration,
        URLRecord_$1.Status,
        HttpResponseCode,
        AppBytesRcd,
        ConReused,
        HttsReqReused,
        ConnectionNumber,
        URLRecord_$1.FlowPathInstance,
        FlowPathSignature"

FROM="FROM  URLRecord_$1, PageTable_$1, URLTable_$1, Flowpath_$1"
WHERE="$WHERE UrlRecord_$1.PageIndex = PageTable_$1.PageIndex
      AND URLRecord_$1.URLIndex = URLTable_$1.URLIndex
      AND $OBJ.ChildIndex = $3
      AND $OBJ.SessionInstance = $4
      AND Flowpath_$1.FlowPathInstance = URLRecord_$1.FlowPathInstance
      AND UrlRecord_$1.pageindex = PageTable_$1.pageindex"
  if [ $2 -eq 1 ];then
    WHERE="$WHERE AND PageRecord_$1.ChildIndex = UrlRecord_$1.ChildIndex AND
    PageRecord_$1.SessionInstance = UrlRecord_$1.SessionInstance AND UrlRecord_$1.PageInstance = PageRecord_$1.PageInstance"
    FROM="$FROM, $OBJ"
  fi

  if [ $2 -eq 2 ];then
    WHERE="$WHERE AND TransactionRecord_$1.ChildIndex = UrlRecord_$1.ChildIndex
      AND TransactionRecord_$1.SessionInstance = UrlRecord_$1.SessionInstance"
    FROM="$FROM, $OBJ"
  if [ -s $NS_WDIR/logs/TR$TRNUM/reports/csv/tprc.csv  ];then
    WHERE="$WHERE AND  TransPageRecord_$TRNUM.pageinstance = URLRecord_$TRNUM.pageinstance AND URLRecord_$TRNUM.childindex = TransPageRecord_$TRNUM.childindex AND TransPageRecord_$TRNUM.sessioninstance = URLRecord_$TRNUM.sessioninstance"
    FROM="$FROM, TransPageRecord_$TRNUM"
  fi
  fi
  if [ $2 -eq 3 ];then
    WHERE="$WHERE AND SessionRecord_$1.SessionInstance = UrlRecord_$1.SessionInstance
           AND SessionRecord_$1.ChildIndex = UrlRecord_$1.ChildIndex"
    FROM="$FROM, $OBJ"
  fi

ORDER="ORDER BY StartTime"
fi


#Case4: When Nd is enable and ect.csv is  present in TR
if [ $ISND -eq 1 -a $ECT_FLAG -eq 1 ];then
SELECT="SELECT URLRecord_$1.PageInstance, PageName, UrlName, URLRecord_$1.StartTime,
        ConnectDuration,
        SSLHandshakeDuration,
        WriteCompleteDuration,
        FirstByteRcdDuration,
        RequestCompleteDuration,
        ErrorName,
        HttpResponseCode,
        AppBytesRcd,
        ConReused,
        HttsReqReused,
        ConnectionNumber,
        URLRecord_$1.FlowPathInstance,
        FlowPathSignature"
        FROM="FROM  URLRecord_$1, PageTable_$1, URLTable_$1, Flowpath_$1,ErrorCodes_$1"

  if [ $2 -eq 0 ];then
      WHERE="$WHERE UrlRecord_$1.PageIndex = PageTable_$1.PageIndex
      AND URLRecord_$1.URLIndex = URLTable_$1.URLIndex
      AND ChildIndex = $3
      AND SessionInstance = $4
      AND Flowpath_$1.FlowPathInstance = URLRecord_$1.FlowPathInstance
      AND ErrorCodes_$1.errorcode =  URLRecord_$1.Status 
      AND ErrorCodes_$1.ObjectType = $2
      AND UrlRecord_$1.pageindex = PageTable_$1.pageindex"
  fi

  if [ $2 -eq 1 ];then
  FROM="$FROM, $OBJ"
  WHERE="$WHERE
       $OBJ.ChildIndex = $3
      AND $OBJ.SessionInstance = $4
      AND  $OBJ.PageIndex = UrlRecord_$1.PageIndex
      AND $OBJ.PageInstance = UrlRecord_$1.PageInstance
      AND $OBJ.ChildIndex = UrlRecord_$1.ChildIndex
      AND $OBJ.SessionInstance = UrlRecord_$1.SessionInstance
      AND $OBJ.PageIndex = PageTable_$1.PageIndex
      AND URLRecord_$1.URLIndex = URLTable_$1.URLIndex
      AND ErrorCodes_$1.errorcode = UrlRecord_$1.Status
      AND ErrorCodes_$1.ObjectType = 0
      AND Flowpath_$1.FlowPathInstance = URLRecord_$1.FlowPathInstance
      AND UrlRecord_$1.pageindex = PageTable_$1.pageindex"
  fi
  if [ $2 -eq 2 ];then
  FROM="$FROM, $OBJ"
  WHERE="$WHERE
      $OBJ.ChildIndex = $3
      AND $OBJ.SessionInstance = $4
      AND $OBJ.ChildIndex = UrlRecord_$1.ChildIndex
      AND $OBJ.SessionInstance = UrlRecord_$1.SessionInstance
      AND URLRecord_$1.URLIndex = URLTable_$1.URLIndex
      AND ErrorCodes_$1.errorcode = UrlRecord_$1.Status
      AND ErrorCodes_$1.ObjectType = 0
      AND Flowpath_$1.FlowPathInstance = URLRecord_$1.FlowPathInstance
      AND UrlRecord_$1.pageindex = PageTable_$1.pageindex"

  if [ -s $NS_WDIR/logs/TR$TRNUM/reports/csv/tprc.csv  ];then
    WHERE="$WHERE AND TransPageRecord_$TRNUM.pageinstance = URLRecord_$TRNUM.pageinstance AND URLRecord_$TRNUM.childindex = TransPageRecord_$TRNUM.childindex AND TransPageRecord_$TRNUM.sessioninstance = URLRecord_$TRNUM.sessioninstance"
    FROM="$FROM, TransPageRecord_$TRNUM"
  fi

  fi

  if [ $2 -eq 3 ];then
    FROM="$FROM, $OBJ"
    WHERE="$WHERE $OBJ.ChildIndex = $3
      AND $OBJ.SessionInstance = $4
      AND $OBJ.ChildIndex = UrlRecord_$1.ChildIndex
      AND $OBJ.SessionInstance = UrlRecord_$1.SessionInstance
      AND URLRecord_$1.URLIndex = URLTable_$1.URLIndex
      AND ErrorCodes_$1.errorcode = UrlRecord_$1.Status
      AND ErrorCodes_$1.ObjectType = 0
      AND Flowpath_$1.FlowPathInstance = URLRecord_$1.FlowPathInstance
      AND UrlRecord_$1.pageindex = PageTable_$1.pageindex"
  fi
  ORDER="ORDER BY StartTime"
fi

echo "$SELECT" >/tmp/8x.txt
echo "$FROM" >>/tmp/8x.txt
echo "$WHERE" >>/tmp/8x.txt
 
log_query
run_nd_query
show_query_result


