#!/bin/sh
#
# Name: nsi_get_host
#
# Author: Abhishek
#
# Purpsose: To get host name or Ip Address of server host. There is three way to get this either input script name or input URL or both scripts and URLs. All server host or IPs output will be Unique.
#
# Usage: nsi_get_host  <script name or URL> | <scripts and URLs> 
#
# Example: 
# 1. Get host name or IP address of server host when only script name is input
# nsi_get_host <workspace_name>/<profile>/<proj>/<sub_proj>/static64B  [more than one script name can be input...]
#
# 2. Get host name or IP address of server host when only URL is input
# nsi_get_host http://www.google.com [more than one URL can be input...]
#
# 3. Get host name or IP address of server host when bot script name and  URL are input
# nsi_get_host <workspace_name>/<profile>/<proj>/<sub_proj>/static64B http://www.google.com static40K http://127.0.0.12:80/index.jsp [any number of script name or URL can be input....]
# 
#
# Exit Values:
#    0 - Success
#    1 - Validation errors
#
# Modification History:
#   25/11/06: Abhishek - Initial Version
#   18/12/06  Atul -  Change TempFile Name
#   02/04/21  Anup Singh- Support workspace/profile

if [ $# -eq 0 ];then
	echo "$0: At leaset one session name or URL is required"
	exit 1;	
fi


if [ "XX" = "XX$NS_WDIR" ];then
	NS_WDIR=/home/cavisson/work
fi


#rm -f /tmp/hosts

#------ Atul-------

TEMPFILE=/tmp/hosts.$$
touch $TEMPFILE
#-----End Atul-----

for i in `seq 1 $#`
do


tmpUrl=`echo $1 | cut -d"/" -f1`

if [ "$tmpUrl" = "http:" -o "$tmpUrl" = "https:" ];then
  tmpHost=`echo $1  | cut -d"/" -f3`
#  tmpHostIp=`echo $tmpHost | cut -d":" -f1`
  echo "$tmpHost" | sort -u >>$TEMPFILE
else

WORKSPACE=`echo ${1} | egrep "/" | cut -d'/' -f1`
PROFILE=`echo ${1} | egrep "/" | cut -d'/' -f2`
PROJ=`echo ${1} | egrep "/" | cut -d'/' -f3`
SUB_PROJ=`echo ${1} | egrep "/" | cut -d'/' -f4`
SCRIPT_DIR=`echo ${1} | egrep "/" | cut -d'/' -f5`
NS_TA_DIR=$NS_WDIR/$WORKSPACE/$PROFILE/cavisson/$PROJ/$SUB_PROJ
SCRIPT_PATH=$NS_TA_DIR/scripts/$SCRIPT_DIR
if [ -f $SCRIPT_PATH/$PROJ/$SUB_PROJ/$SCRIPT_DIR.detail ];then
	DETAIL="$SCRIPT_PATH/$PROJ/$SUB_PROJ/$SCRIPT_DIR.detail"
elif [ -f $SCRIPT_PATH/script.detail ];then
	DETAIL="$SCRIPT_PATH/script.detail"
else
	echo "script $SCRIPT_PATH does not seem to have proper detail file"
	exit 1
fi


if [ -f $SCRIPT_PATH/$PROJ/$SUB_PROJ/$SCRIPT_DIR.capture ];then
	CAPTURE="$SCRIPT_PATH/$PROJ/$SUB_PROJ/$SCRIPT_DIR.capture"
elif [ -f $SCRIPT_PATH/script.capture ];then
	CAPTURE="$SCRIPT_PATH/script.capture"
else
	echo "script $1 does not seem to have proper capture file"
	exit 1
fi
#ignore single line comment in capture & detail file (block comments are not ignored)
        grep Host: $DETAIL | awk '!/^\/\// {print $2}' | sort -u >>$TEMPFILE 
        grep URL $CAPTURE | awk '{print $1}' | awk '!/^\/\// {print $1}' | awk -F"/" '{print $3}' | sort -u >>$TEMPFILE
        egrep "SMTP_SERVER|POP_SERVER|FTP_SERVER|DNS_SERVER_IP" $CAPTURE | awk '{print $1}' | awk '!/^\/\// {print $1}' | awk -F"=" '{print $2}' | awk -F',' '{print $1}' | sort -u >>$TEMPFILE
   
fi
	shift


done

# Since some host have  as the end, we need to convert to unix format to remove it.
# This is required so that we get unique list

dos2unix $TEMPFILE 1>/dev/null 2>&1
sort -u $TEMPFILE
rm -f $TEMPFILE

exit 0
