#!/bin/bash
TR_NUM=""
PARTITION_NUM=""
TR_NOTE=""
FILE=""
DIR=""

if [ "X$NS_WDIR" == "X" ]; then
  NS_WDIR=/home/cavisson/work
fi

do_entry()
{
  if [ -d $DIR ]; then
    echo $TR_NOTE >$FILE  2>/dev/null
    if [ "X$?" == "X1" ]; then
      echo "Error occured while writing in file test_notes.txt"
    fi
  fi
}

Usage()
{
  echo "Usage:"
  echo "$0 -n <test run number> -p <partition> -s <\"string to write\">"
  exit -1
}
while getopts n:s:p:? c 2>/dev/null
do
  case $c in 
    n)TR_NUM=$OPTARG;;
    p)PARTITION_NUM=$OPTARG;;
    s)TR_NOTE=$OPTARG;;
    ?)Usage;;
    *)Usage;;
  esac
done

if [ "X$TR_NUM" == "X" -a "X$TR_NOTE" == "X" ]; then
  Usage
fi

if [ "X$PARTITION_NUM" != "X" -a "X$TR_NOTE" == "X" ]; then
  Usage
fi

if [ -d $NS_WDIR/logs/TR$TR_NUM/$PARTITION_NUM ]; then
  DIR=$NS_WDIR/logs/TR$TR_NUM/$PARTITION_NUM/user_notes
  mkdir $DIR 2>/dev/null
  FILE=$DIR/test_notes.txt
fi
do_entry

exit 0
