#!/bin/sh

TEST_RUN_NUM=$1
USER_NAME=$2

# This is to set CLASSPATH
export CLASSPATH=$CLASSPATH:$NS_WDIR/webapps/DashboardServer/WEB-INF/lib/gson-2.2.2.jar:$NS_WDIR/webapps/DashboardServer/WEB-INF/lib/netstorm_bean.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/jfreechart-1.0.14.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/java-getopt-1.0.9.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/itext-paulo-154.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/jcommon-1.0.17.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/poi.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/jcommon-1.0.17.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/commons-io-2.2.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/kryo-2.23.0.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/exp4j-0.4.5.jar:.

if [ $# -lt 2 ];then
  echo "Usage: nsi_gen_cmp_rep_set_data <TestRun number> <User Name>....."
  echo "Test Run Number should be numeric"
  echo "User name should be string"
  exit 1 
fi

if [ "XX$NS_WDIR" == "XX" ];then
  echo "NS_WDIR must be defined"
  exit 1
fi
  
  #Getting controller name
Controller_name=`echo $HPD_ROOT |cut -d'/' -f3`
#set apps controller name
APPS_CONTROLLER_NAME=$NS_WDIR/apps
#set tomcat home path
#Note: In future, if any new version of tomcat is added then we need to add condition here.
if [ -d $APPS_CONTROLLER_NAME/apache-tomcat-9.0.50 ];then
  TOMCAT_HOME=$APPS_CONTROLLER_NAME/apache-tomcat-9.0.50
elif [ -d $APPS_CONTROLLER_NAME/apache-tomcat-9.0.43 ];then
  TOMCAT_HOME=$APPS_CONTROLLER_NAME/apache-tomcat-9.0.43
elif [ -d $APPS_CONTROLLER_NAME/apache-tomcat-9.0.41 ];then
  TOMCAT_HOME=$APPS_CONTROLLER_NAME/apache-tomcat-9.0.41
elif [ -d $APPS_CONTROLLER_NAME/apache-tomcat-7.0.105 ];then
  TOMCAT_HOME=$APPS_CONTROLLER_NAME/apache-tomcat-7.0.105
elif [ -d $APPS_CONTROLLER_NAME/apache-tomcat-7.0.104 ];then
  TOMCAT_HOME=$APPS_CONTROLLER_NAME/apache-tomcat-7.0.104
elif [ -d $APPS_CONTROLLER_NAME/apache-tomcat-7.0.99 ];then
  TOMCAT_HOME=$APPS_CONTROLLER_NAME/apache-tomcat-7.0.99
elif [ -d $APPS_CONTROLLER_NAME/apache-tomcat-7.0.91 ];then
  TOMCAT_HOME=$APPS_CONTROLLER_NAME/apache-tomcat-7.0.91
elif [ -d $APPS_CONTROLLER_NAME/apache-tomcat-7.0.59 ];then
  TOMCAT_HOME=$APPS_CONTROLLER_NAME/apache-tomcat-7.0.59
elif [ -d $APPS_CONTROLLER_NAME/apache-tomcat-7.0.52 ];then
  TOMCAT_HOME=$APPS_CONTROLLER_NAME/apache-tomcat-7.0.52
else
  TOMCAT_HOME=$APPS_CONTROLLER_NAME/apache-tomcat-6.0.16  
fi
#server.xml path
XML_FILE="$TOMCAT_HOME/conf/server.xml"

#Get All active HTTP/1.1 Connector. 
  CONNECTOR_FILE=/tmp/connector.$$
  cat $XML_FILE|sed -e "s/-->/\n-->/g" | sed -e "/<!--/,/-->/d"|tr '[\n]' '[ ]'|sed -e 's#/>#/>\n#g' -e 's#<#\n<#g'|grep "<Connector" |grep "HTTP\/1.1" >$CONNECTOR_FILE 
#Check if SSLEnabled connector is present then we will pick that one.
  CONNECTOR_STRING=`grep "SSLEnabled" $CONNECTOR_FILE`
  if [ -z "$CONNECTOR_STRING" ];then
    CONNECTOR_STRING=`head -1 $CONNECTOR_FILE`
    Protocol="http"
  else 
    Protocol="https" 
  fi
  rm $CONNECTOR_FILE
  
#getting port  and IP
  PORT=`echo $CONNECTOR_STRING | grep -o 'port=\"[0-9]*\"'|grep -o "[0-9]*"` 
  IP=`echo $CONNECTOR_STRING | grep -o 'address=\"[0-9.]*\"'|grep -o "[0-9.]*"`
  
#Set default values. 
  if [ -z $PORT ];then
    if [ "X$Protocol" == "Xhttp" ];then
      PORT=80
    else 
      PORT=443
    fi 
  fi  
  
  if [ -z $IP ];then
    INTERFACE=`netstat -nr|grep -wm1 UG|awk '{print $8}'`
    IP=`ifconfig $INTERFACE |grep 'inet addr' |cut -d':' -f2 |cut -d' ' -f1`
    if [ -z "$IP" ];then
      IP=127.0.0.1
    fi
  fi
  
#cd $NS_WDIR/webapps/netstorm/WEB-INF/classes
java -cp $CLASSPATH:$NS_WDIR/webapps/DashboardServer/WEB-INF/lib/dashboardserver.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/commons-fileupload-1.3.jar:$NS_WDIR/webapps/DashboardServer/WEB-INF/lib/json_simple-1.1.jar:$NS_WDIR/webapps/DashboardServer/WEB-INF/lib/web-dashboard-bean.jar::$NS_WDIR/webapps/DashboardServer/WEB-INF/lib/batik-all-1.7.jar:$NS_WDIR/webapps/DashboardServer/WEB-INF/lib/rhino-1.7R2.jar:$NS_WDIR/webapps/DashboardServer/WEB-INF/lib/xml-apis-ext.jar:$NS_WDIR/webapps/netstorm/WEB-INF/lib/log4j-1.2.16.jar:$NS_WDIR/webapps/DashboardServer/WEB-INF/lib/slf4j-log4j12-1.5.8.jar:$NS_WDIR/webapps/DashboardServer/WEB-INF/lib/slf4j-api-1.5.8.jar -DNS_WDIR=$NS_WDIR -Djava.awt.headless=true com.cavisson.gui.server.webreports.services.CompareReportGenerator $* $Protocol $PORT $IP

exit 0
