#!/bin/bash
#################################################################################################################################################
############
# Name      : nsi_get_controller_name 
# Author    : Naveen Raina
# Purpose   : To get all the active controllers from /home/cavisson/etc/cav.conf 
#
#################################################################################################################################################

i=0
CTRL_CONF_FILE=/home/cavisson/etc/cav_controller.conf
TMP_CONTROLLER_FILE=/tmp/controller_file.$$

if [ ! -f $CTRL_CONF_FILE ];then
  echo "work"
  exit 0
fi

while read line
do
    #skip header line
    if [ $i -eq 0 ];then
      i=`expr $i + 1`
      continue
    fi

    echo $line | grep '^#' >/dev/null
    if [ $? == 0 ];then
      continue
    fi
    
    #skip blank lines
    echo $line | egrep '^$' >/dev/null
    if [ $? == 0 ];then
      continue
    fi

    #Get controller dir or WORK dir
    CTRL_DIR=`echo "$line"| cut -d'|' -f3` 
    [[ ! -d $CTRL_DIR ]]
    if [ $? == 0 ];then
      echo "Controller $CTRL_DIR Not Found"  
      continue
    fi
    basename $CTRL_DIR >>$TMP_CONTROLLER_FILE
        
done < $CTRL_CONF_FILE

cat $TMP_CONTROLLER_FILE
 
rm $TMP_CONTROLLER_FILE
exit 0
