#!/bin/sh
usage()
{
  echo "usage:"
  echo "$0 -p <path of TR>"
  exit 1
}

#this function will create partition directory according to timestamp inside summary.top
create_partition_dir()
{
  path=`echo $NS_WDIR/logs/TR$TRNum`
  temp=`awk -F'|' '{print $3}' $path/summary.top`
  year=`echo $temp |awk '{print $1}'|awk -F'/' '{print 20$3$1$2}'`
  Time=`echo $temp |awk '{print $2}'|awk -F':' '{print $1$2$3}'`
  part_name=`echo $year$Time`
  mkdir $path/$part_name

  if [ $? -ne 0 ];then
    echo "can not create partition directory inside $path"
    exit 1
  fi
  cd $path

}
#this function will move all necessary files inside partition 
move_files_inside_partiton_dir()
{
  mv rtgMessage.dat* testrun.gdf* testrun.pdf* $path/$part_name/

  mv event.log monitor.log pctMessage.dat version error.log* percentile.csv url_req*.dat gui.data pct_message_samples_* $path/$part_name/ 2>/dev/null
  #since progress.report and summary.top are present at both inside outside partition therefore we don't move
  cp progress.report summary.top $path/$part_name/
  #since ns_logs , scripts at both inside outside partition therefore we don't move
  cp -r ns_logs scripts $path/$part_name/

  #server_logs present both inside and outside partition therefore we don't move
  if [ -d server_logs ];then
    cp -r server_logs $path/$part_name/
  fi

  if [ -d page_dump ];then
    mv page_dump $path/$part_name/
  fi

  if [ -d data_log_file ];then
    mv data_log_file $path/$part_name/
  fi

  if [ -d rbu_logs ];then
    mv rbu_logs $path/$part_name/
  fi
  
  mv reports/raw_data/slog reports/raw_data/slog $commonFiles_path/reports/raw_data 2>/dev/null

  mv reports $path/$part_name/ 2>/dev/null

  #nd dir is present both inside and outside partition
  #nd dir inside partition have following dir.
  # csv/instance dir, logs, sql, raw_data, hs (rest files and dir are present outside partition)
  #nd dir outside partition have csv/common meta data
  if [ -d nd ];then
    #need to check whether Common Metdata CSV file is already present in TRxxx/nd/csv directory. If not use neu_migrate_common_metadata_csv to migrate
    neu_migrate_common_metadata_csv -t $TRNum >/dev/null

    mkdir $path/$part_name/nd
    if [ $? -ne 0 ];then
      echo "Can not create nd dir inside partition"
      exit 1
    fi
    mv nd/logs nd/sqb nd/raw_data nd/hs $path/$part_name/nd/ 2>/dev/null
    mkdir $path/$part_name/nd/csv
    if [ $? -ne 0 ];then
      echo "Can not create nd/csv dir inside partition"
      exit 1
    fi

    instance_files=`ls $path/nd/csv|grep _instance`
    #to move only instance dir
    for inst in $instance_files
    do
      mv nd/csv/$inst $path/$part_name/nd/csv
    done
  fi

}
make_common_files_dir_and_move_files()
{
  commonFiles_path=`echo $path/common_files`
  if [ ! -d $commonFiles_path ];then
    mkdir $commonFiles_path

    if [ $? -ne 0 ];then
      echo "can not create common_files directory inside $path"
      exit 1
    fi
  fi

  mv ns_files VendorData.default schedule_phases.dat $commonFiles_path/

  if [ -f sess_status_log ];then
    mv sess_status_log $commonFiles_path/
  fi

  if [ -f schedule_phases.dat ];then
    mv schedule_phases.dat $commonFiles_path/
  fi

  if [ -f .oracle_sql_report ];then
    mv .oracle_sql_report $commonFiles_path/
  fi

  commonFiles_nsLogs=`echo $commonFiles_path/ns_logs`

  mkdir $commonFiles_nsLogs

  if [ $? -ne 0 ];then
    echo "can not create ns_logs directory inside $commonFiles_path"
   
  else

    if [ -d ns_logs/njvm ];then
      mv ns_logs/njvm $commonFiles_nsLogs/
    fi

    if [ -d ns_logs/http_req_rep_body ];then
      mv ns_logs/http_req_rep_body $commonFiles_nsLogs/
    fi

    mv ns_logs/topology_structure_dump_file ns_logs/monitor_structure_dump_file ns_logs/user_profile_rec.dat $commonFiles_nsLogs/ 2>/dev/null
  fi
  #Dynamic csv files are present inside partition/reports/csv
  #And Static csv files are present inside commonfiles/reports/csv
  #Here we are moving static csv files to commonfiles
  
  mkdir $commonFiles_path/reports/csv 2>/dev/null
  if [ $? -ne 0 ];then
    echo "can not create reports/csv directory inside $commonFiles_path"
  
    mv reports/csv/rpf.csv reports/csv/upf.csv reports/csv/spf.csv reports/csv/sst.csv reports/csv/pgt.csv reports/csv/trt.csv reports/csv/urt.csv reports/csv/hrt.csv reports/csv/hat.csv reports/csv/log_phase_table.csv reports/csv/generator_table.csv reports/csv/HostTable.csv $commonFiles_path/reports/csv 2>/dev/null
  fi

}

change_partition_settings()
{
  sed -i '/PARTITION_SETTINGS 0/c\PARTITION_SETTINGS 1 0 8H' sorted_scenario.conf
  echo -e "FirstPartitionIdx=$part_name\nCurPartitionIdx=$part_name" >.curPartition
}

tr_flag=0
while getopts t: c
do
  case $c in
    t) TRNum=$OPTARG;
       tr_flag=1
       ;;
    ?) usage ;;
  esac
done

if [ $tr_flag -eq 0 ];then
  usage
fi

if [ "X$NS_WDIR" = "X" ]; then
  echo "Error: NS_WDIR is not set"
  exit 1
fi

create_partition_dir

change_partition_settings

make_common_files_dir_and_move_files

move_files_inside_partiton_dir

