#!/bin/sh
# Name  : nsi_del_ip
# Author: Sanjay/Achint
# usage :
#       nsi_del_ip entity start_ip end_ip vlanid netbits exclude_ip netid gateway
# if  entity C (means clinet), command would be run locally, 
# if entity is S, run it for netocean.. In this case same cmd is 
# run on netocean with entity set to R and passing an extra argument of Load interface
# Assigns IP addresses in the range start-ip to end-ip (inclusive) excluding
# exclused ip (if not - ) on load interface with gie=ven vlan-id.
# netbits is the number of bits in netid.
# Modification History:
#   05/08/06  Initial version
#   05/14/06  Anil Reviewed and added Entity=R option
#   07/24/06  Achint added interface for the deletion. Now command will take 9 arrguments it will take interface as an argument.
HOME_DIR=/home/cavisson
CONFIG=`grep ^CONFIG $HOME_DIR/etc/cav.conf | awk  '{print $2}'`

USER=`whoami`
if [ "X$USER" != "Xcavisson" ];then
    echo "You must be logged in as cavisson user to execute this command"
    exit -1
fi

# in case $NS_WDIR is empty , setting it to $HOME_DIR/work 
if [ "X$NS_WDIR" = "X" ];then
  NS_WDIR=$HOME_DIR/work
fi


CHECK_FORMAT=$NS_WDIR/bin/nsi_check_format

if [ "$#" -ne 11 ];then
  echo "usage:nsi_del_ip entity start_ip end_ip vlanid netbits exclude_ip netid gateway interfac del_vlan IP_VERSION_TYPE"
  echo "del_vlan may be - "
  exit 1
fi
RLOGIN="ssh -n"
ENTITY=$1
start_ip=$2
end_ip=$3
VLANID=$4
netbits=$5
EXCLUDE_IP=$6
netid=$7
GATEWAY=$8
LOAD_INTERFACE=$9
DEL_VLAN=${10}
IP_VERSION_TYPE=${11}


#check ip version type i.e ipv4 and ipv6
if [ $IP_VERSION_TYPE = 1 ];then
  IP_CMD="sudo /sbin/ip"
  INET="inet"
elif [ $IP_VERSION_TYPE = 2 ];then
  IP_CMD="sudo /sbin/ip -6"
  INET="inet6"
else
  echo "invalid ip type"
  exit 1
fi

#Do Input validation
#Check start-ip and end-ip are valid
  $CHECK_FORMAT -v $IP_VERSION_TYPE -i $start_ip
  if [ $? -ne 0 ];then
    echo "start ip $2 not in valid format"
    exit 1
  fi
  $CHECK_FORMAT -v $IP_VERSION_TYPE -i $end_ip
  if [ $? -ne 0 ];then
    echo "End ip $end_ip not in valid format"
    exit 1
  fi

#check vlanid is either - or non-negative
  if [ $VLANID != "-" ];then
    if [ $VLANID -lt 0 ];then
      echo "Vlan Id can not be Negative"
      exit 1
    fi
  fi
#check netbits is more than 0 and less than 31
  if [ $netbits -le 0 -o $netbits -gt 31 -a $IP_VERSION_TYPE -eq 1 ];then
    echo "Netbits can not be less than 0 and greater than 31"
    exit 1
  fi
#check netbits is more than 0 and less than 128 (this is the case of IPV6)
  if [ $netbits -le 0 -o $netbits -gt 127 -a $IP_VERSION_TYPE -eq 2 ];then
    echo "Error: Netbits can not be less than 0 and greater than 127" 
    exit 1
  fi

#check exclude ip is either - or a valid IP
  if [ $EXCLUDE_IP != "-" ];then
   $CHECK_FORMAT -v $IP_VERSION_TYPE -i $EXCLUDE_IP
    if [ $? -ne 0 ];then
      echo "EXCLUDE IP $EXCLUDE_IP not in valid format"
      exit 1
    fi
  fi
#Check net id is in correct format
  if [ $netid != "-" ];then
    $CHECK_FORMAT -v $IP_VERSION_TYPE -i $netid
    if [ $? -ne 0 ];then
      echo "Net Id $netid not in valid format"
      exit 1
    fi
  fi
#check gateway is in correct format
  if [ $GATEWAY != "-" -a $GATEWAY != "SELF" ];then
    $CHECK_FORMAT -v $IP_VERSION_TYPE -i $GATEWAY
    if [ $? -ne 0 ];then
      echo "Gateway $GATEWAY not in valid format"
      exit 1
    fi
  fi

#Function to elete the route and gateway
#First argument is netid/netbits and second arg is gateway 
#example: del_route 3.0.0.0/24 3.0.0.1 
 del_route () 
{ 
  if [ $2 == "-" ];then 
    return 0 
  fi 

  #delete route 
  if [ $2 == "SELF" ];then 
      $IP_CMD route del default table cavisson
  else
      $IP_CMD route del default via $2 table cavisson 
  fi
  #delete same net rule if gateway is present 
  #if [ $2 != "-" ];then
  #  $IP_CMD rule del from $1 to $1 table main
  #fi
  #delete main rule 
  $IP_CMD rule del from $1 table cavisson
  #delete route tableid 
  #  cp /etc/iproute2/rt_tables /tmp/del_route.$$ 
  #  grep -v $1 /tmp/del_route.$$ >/etc/iproute2/rt_tables 
  #  rm /tmp/del_route.$$ 
  return 0
}

#changes for deletion of ip on NO machine
if [ "XX$CONFIG" != "XXNO" ];then 
  if [ "$ENTITY" == "S" ];then
    SR_ADDRESS=`cat $HOME_DIR/etc/cav.conf | grep "SRAdminIP" | cut -d" " -f2 | cut -d/ -f1`
    NS_ADDRESS=`cat $HOME_DIR/etc/cav.conf | grep "NSAdminIP" | cut -d" " -f2 | cut -d/ -f1`
    if [ "$SR_ADDRESS" != "$NS_ADDRESS" ];then
      # Run '$NS_WDIR/nsi_del_ip R $start_ip $end_ip $VLANID $netbits $EXCLUDE_IP $LOAD' on $SR_ADDRESS as root
      output_rlogin=`$RLOGIN $SR_ADDRESS $NS_WDIR/bin/nsi_del_ip R $start_ip $end_ip $VLANID $netbits $EXCLUDE_IP $netid $GATEWAY $LOAD_INTERFACE $DEL_VLAN $IP_VERSION_TYPE`
      echo $output_rlogin
      exit 0
    fi
  fi 
fi

#Call function to delete the route and gateway
#First argument is netid/netbits and second arg is gateway 
#example: del_route 3.0.0.0/24 3.0.0.1
del_route $netid/$netbits $GATEWAY

if [ "$VLANID" != "-" ];then
  del_interface=$LOAD_INTERFACE.$VLANID
else
  del_interface=$LOAD_INTERFACE
fi

#Delete IP $start_ip $end_ip
for x in `$NS_WDIR/bin/nsu_seq_ip $IP_VERSION_TYPE $start_ip $end_ip`
do
  if [ "$x" != $EXCLUDE_IP ];then
     `$IP_CMD address del $x/$netbits dev $del_interface` 1>/dev/null 2>&1
  fi
done
 


if [ "X$DEL_VLAN" = "X1" ];then
	/sbin/vconfig rem $del_interface
fi
sudo iptables --flush
exit 0
