#!/bin/bash

##############################################################################################
# Name    : nsi_db_txc_get_ctical_path_data
#
# Author  :  Manmeet
#
# Purpose : This shell script is for getting the critical path data
#           Which is called by DDR GUI for the critical path report
#
#           Currently it displays the dummy data
##############################################################################################

usage()
{
  echo
  echo "$*"
  echo
  echo "USAGE:"
  echo "====="
  echo
  echo "$0 --testrun <value> --status <value> --txcsignatureid <value> --txcindex <value> --txcinstance <value> --starttime <value> --endtime <value> --resptime <value> ----resptimeqmode <mode> --responsetime <time in ms> --responsetime2 <time in ms>"
  echo
  echo "Where"
  echo "  --testrun is test run number, which is mandatory argument."
  echo "  --txcindex is transaction component index, which is optional argument."
  echo "  --txcsignatureid is signature id, which is optional argument."
  echo "  --txcinstance is instance id, which is optional argument."
  echo "  --status is selecting particular staus (status is 0 for Success only, 1 the Failure code, -1 for all"
  echo "  --starttime and -endtime is for selecting result that comes under the given range, optional"
  echo "  --resptimeqmode is the selection of responsetime(1-lessthen, 2-greaterthen, 3-equal), which is mandatory argument."
  echo "  --responsetime is for giving perticular responsetime for different response time mode, which is optional argument."
  echo "  --responsetime2 is required in case --resptimeqmode 3. In this case the range is between --responsetime and --responsetime2."
  echo "  --get_count returns the number of rows of the query if it were called without this argumnent."  
  echo "  --limit for selecting fix number of result optional"
  echo "  --offset to set offset in case of limit optional"

  exit 1
}

chk_args()
{
  if [ "X$TRNUM" == "X" ]; then
    usage "Missing mandatory option --testrun."
  fi
}

ARGS=$*
if [ "X$1" == "X" ];then
  usage
fi

chk_args_of_option()
{
  if [ "X$2" == "X" ];then
    usage "Option $1 requires a value."
  fi
}

GET_COUNT=0

while [ "$1" != "" ];do
  case $1 in
    "--testrun")
        shift
        chk_args_of_option "--testrun" "$1"
        TRNUM=$1;;
    "--txcindex")
        shift
        chk_args_of_option "--txcindex" "$1"
        TXCINDEX=$1;;
    "--txcsignatureid")
        shift
        chk_args_of_option "--txcsignatureid" "$1"
        TXCSIGNATUREID=$1;;
    "--txcinstance")
        shift
        chk_args_of_option "--txcinstance" "$1"
        TXCINSTANCE=$1;;
    "--status")
        shift
        chk_args_of_option "--status" "$1"
        STATUS=$1;;
    "--starttime")
        shift
        chk_args_of_option "--starttime" "$1"
        STARTTIME=$1;;
    "--endtime")
        shift
        chk_args_of_option "--endtime" "$1"
        ENDTIME=$1;;
    "--abs_starttime")
        shift
        chk_args_of_option "--abs_starttime" "$1"
        ABS_STARTTIME=$1;;
    "--abs_endtime")
        shift
        chk_args_of_option "--abs_endtime" "$1"
        ABS_ENDTIME=$1;;
    "--responsetime")
        shift
        chk_args_of_option "--responsetime" "$1"
        RESPONSETIME=$1;;
    "--resptimeqmode")
        shift
        chk_args_of_option "--resptimeqmode" "$1"
        RESPTIMEQMODE=$1;;
    "--responsetime2")
        shift
        chk_args_of_option "--responsetime2" "$1"
        RESPONSETIME2=$1;;
    "--get_count")
        shift
        chk_args_of_option "--get_count" "$1"
        GET_COUNT=$1;;
    "--limit")
        shift
        chk_args_of_option "--limit" "$1"
        LIMIT=$1;;
    "--offset")
        shift
        chk_args_of_option "--offset" "$1"
        OFFSET=$1;;
    --*) usage "Invalid option $1";;
    *) usage ;;
  esac
  shift
done

if [ "$GET_COUNT" == "1" ];then
  echo "Rows"
  echo "1"
else
  if [ "X$TXCINDEX" == "X" ];then
    echo "CritPathSignatureId|CritPathName|Count|%Time|CritPathRespTime|SelfTime|TotalTime"
    echo "0|sp_get_ola_services&&getWSignOnAccountDetails_201109&&XAMGCST4_GetCustomer|10|60|271|28|299"
  fi
fi
