#! /bin/sh

# Basename is exported from nsi_upgrade shell
export WORK=$BASENAME

RELEASE_CMD="nsi_get_linux_release_ex"
DISTRO=`$RELEASE_CMD -d`
msgout_both "Uncompressing tar file - $GZ"
cp $NS_WDIR/.rel/$GZ .
tar xvzf $GZ >> $LOG_FILE_NAME
rm $GZ

if [ "$?" != 0 ];then
  msgout_both "Error: Error in uncompressing the $GZ"
  exit 1
fi

cp -r cdr/* .
rm -rf cdr

mkdir -p $NS_WDIR/logs/data_retention/cache/test_runs
mkdir -p $NS_WDIR/logs/data_retention/logs/
mkdir -p $NS_WDIR/logs/data_retention/cache/test_cycles/
mkdir -p $NS_WDIR/logs/data_retention/cache/nv/

$NS_WDIR/bin/cdr_create_default_config_json #To create default config json file 
exit 0
