#!/bin/sh


USER=`whoami`
if [ "X$USER" != "Xcavisson" ];then
    echo "You must be logged in as cavisson user to execute this command"
    exit -1
fi


# Source netstorm.env to set environemnt variables which are based on JDK and Tomcat version
# Also NS_WDIR and PATH is set
export NS_WDIR=/home/cavisson/work

CONFIG=`cat $HOME_DIR/etc/cav.conf | grep "^CONFIG" | awk '{print $2}'`
NSAdminIP=`cat $HOME_DIR/etc/cav.conf | grep "^NSAdminIP" | awk '{print $2}' | awk -F / '{print $1}'`
SRAdminIP=`cat $HOME_DIR/etc/cav.conf | grep "^SRAdminIP" | awk '{print $2}' | awk -F / '{print $1}'`

echo "Setting password less access for cavisson login between $NSAdminIP and $SRAdminIP"

if [ "X$CONFIG" == "X" ]; then
    echo "CONFIG is not set in $HOME_DIR/etc/cav.conf"
    exit -1
fi

if [ "X$NSAdminIP" == "X" ]; then
    echo "NSAdminIP is not set in $HOME_DIR/etc/cav.conf"
    exit -1
fi

if [ "X$SRAdminIP" == "X" ]; then
    echo "SRAdminIP is not set in $HOME_DIR/etc/cav.conf"
    exit -1
fi

echo "Creating files for password-less ssh"

mkdir -p /home/cavisson/.ssh
chmod 700 /home/cavisson/.ssh
rm -f /home/cavisson/.ssh/id_rsa /home/cavisson/.ssh/id_rsa.pub

echo "Create Keys for cavisson id"
ssh-keygen -t rsa -P "" -f /home/cavisson/.ssh/id_rsa

echo "Copying ssh keys files to other machine for password-less ssh"
if [ $CONFIG == 'NS>NO' ];then
    ping -c 1 $SRAdminIP >/dev/null 2>&1
    if [ $? -ne 0 ];then
        echo "Unable to connect to Server Admnin IP $SRAdminIP"
        echo "Please make sure server is up before running post_install.sh"
        exit 1
    fi
    echo "Copying /home/cavisson/.ssh/id_rsa.pub to netocean machine as /home/cavisson/.ssh/authorized_keys2"
    echo ""
    echo "You may be prompted for confirmation and netstorm id password of netocean machine  - ${SRAdminIP}"
    echo "" 
    # scp /home/cavisson/.ssh/id_rsa.pub cavisson@${SRAdminIP}:/home/cavisson/.ssh/authorized_keys2
    #Bug-16606 this command will copy key to the server's authorized_keys file. 
    ssh-copy-id -o NumberOfPasswordPrompts=1 -f -i /home/cavisson/.ssh/id_rsa.pub cavisson@$SRAdminIP 
    #Must run ssh once so that it can ask for confirmation
    echo "Checking password-less ssh using cavisson id by running pwd command"
    ssh ${SRAdminIP} pwd

elif [ $CONFIG == 'NS+NO' ];then
    echo "No need for password-less ssh for NS+NO configuration"
elif [ $CONFIG == 'NS' -o $CONFIG == 'ED' ];then
    echo "No need for password-less ssh for NS/ED configuration"
elif [ $CONFIG == 'NV' ];then
    echo "No need for password-less ssh for NV configuration"
elif [ $CONFIG == 'NCH' ];then
    echo "No need for password-less ssh for NCH configuration"
elif [ $CONFIG == 'NO' ];then
    ping -c 1 $NSAdminIP >/dev/null 2>&1
    if [ $? -ne 0 ];then
        echo "Unable to connect to Netstorm Admnin IP $NSAdminIP"
        echo "Please make sure Netstorm is up before running post_install.sh"
        exit 1
    fi
    echo "Copying /home/cavisson/.ssh/id_rsa.pub to netstorm machine as /home/cavisson/.ssh/authorized_keys2"
    echo ""
    echo "You may be prompted for confirmation and cavisson id password of netstorm machine  - ${NSAdminIP}"
    echo ""
    #scp /home/cavisson/.ssh/id_rsa.pub cavisson@${NSAdminIP}:/home/cavisson/.ssh/authorized_keys2
    #Bug-16606 this command will copy key to the server's authorized_keys file.
    ssh-copy-id -o NumberOfPasswordPrompts=1 -f -i /home/cavisson/.ssh/id_rsa.pub cavisson@$NSAdminIP 
    #Must run ssg once so that it can ask for confirmation
    echo "Checking password-less ssh using netstorm id by running pwd command"
    ssh ${NSAdminIP} pwd
else
    echo "Invalid Cavisson Config: $CONFIG. Valid values are NS, NCH, NO, NS+NO or NS>NO"
    exit 1
fi

exit 0

