#!/bin/sh
# Name  : nsi_get_controller_type 
# Author: Naveen 
# usage :
#        nsi_get_controller_type  

CONF_FILE=$HOME/etc/cav.conf
controller_type=Internal

#If not present, then use cav.conf
if [ ! -f $CONF_FILE ]; then
  echo "$CONF_FILE does not exist"
  exit -1
fi

#Find the last occurrence of CONTROLLER_TYPE in cav.conf file
controller_type=`awk '/^CONTROLLER_TYPE/ { lines[last] = $0 } END { print lines[last] } ' $CONF_FILE | cut -d" " -f2`

if [ "X$controller_type" == "X" ]; then
  controller_type=Internal
fi

if [ "X$controller_type" != "XInternal" -a "X$controller_type" != "XExternal" ]; then
  echo "Invalid controller type $controller_type given in $CONF_FILE file"
  exit -1
fi

echo $controller_type

exit 0
