#! /bin/sh

# Basename is exported from nsi_upgrade shell
HOME_DIR=/home/cavisson
export WORK=$BASENAME
RELEASE_CMD="nsi_get_linux_release_ex"
DISTRO=`$RELEASE_CMD -d`

if [ "X$NS_WDIR" = "X" ];then
  export NS_WDIR="$HOME_DIR/work"
fi

NETHAVOC_DIR=$NS_WDIR/netHavoc
NH_DEFAULT_SCENARIO_DIR=$NETHAVOC_DIR/scenarios/default/default/default_scenario

echo "Removing files from directory of old version."
rm -rf $NETHAVOC_DIR/bin/* $NETHAVOC_DIR/etc/* $NETHAVOC_DIR/samples/*

echo "Copying and Uncompressing tar file - $GZ"
cp $NS_WDIR/.rel/$GZ .
tar xvzf $GZ 

if [ $? -ne 0 ];then
  echo "Error: Error in uncompressing the $GZ"
  rm -rf $GZ $NS_WDIR/.rel/$GZ
  exit 1
fi

mkdir -p $NETHAVOC_DIR/logs


#make conf dir if not exist and copy files from samples dir
if [ ! -d $NETHAVOC_DIR/conf ];then
  mkdir -p $NETHAVOC_DIR/conf
  if [ ! -f $NETHAVOC_DIR/conf/netHavoc.conf ];then
    cp $NETHAVOC_DIR/samples/netHavoc.conf $NETHAVOC_DIR/conf
  fi
fi

#make default scenario dir if not exist and copy file if necessary
if [ ! -d $NH_DEFAULT_SCENARIO_DIR ];then
  mkdir -p $NH_DEFAULT_SCENARIO_DIR
fi

if [ ! -f $NH_DEFAULT_SCENARIO_DIR/fault.conf ];then
  if [ ! -f $NETHAVOC_DIR/conf/fault.conf ];then
    cp $NETHAVOC_DIR/samples/fault.conf $NETHAVOC_DIR/conf
  else
    mv $NETHAVOC_DIR/conf/fault.conf $NH_DEFAULT_SCENARIO_DIR/
  fi 
else
  if [ -f $NETHAVOC_DIR/conf/fault.conf ];then
    rm -f $NETHAVOC_DIR/conf/fault.conf 
  fi
fi

rm -rf $GZ $NS_WDIR/.rel/$GZ
exit 0
