#!/bin/sh

#args: TR-NUM child-id user-id wan-env

if [ $# -lt 4 ];then
    	echo "Usage: nsi_get_7x TR-NUM child-id user-id wan-env"
	echo "TR-NUM is the test run number"
	echo "child-id and user-id togather detrrmines uniq user-id"
	echo "wan-env can be 0 or 1"
	echo "location-slectection: All for all otherwise location name"
	echo "access-slectection: All for all otherwise access name"
	echo "run-time-flag is 1 for run-time phase only, otherwise 0"
	exit 1
fi

TRNUM=$1

if [ "XX" == "XX$NS_WDIR" ]
then
  NS_WDIR=/home/cavisson/work
fi

. $NS_WDIR/bin/nsi_db_utils
set_query_files $TRNUM

if [ $# -eq 4 ];then
	RPO=0
else
	RPO=$5
fi

if [ $4 -eq 1 ];then
	SELECT="SELECT ChildIndex AS \"Child Index\", SessionInstance AS \"Session Id\", location AS \"User Location\", access AS \"User Access\", SessionName AS \"Session Name\", StartTime AS \"Start Time\", (EndTime-StartTime) As \"Total Time\", Status AS \"Status\""
	FROM="FROM SessionRecord_$1, SessionTable_$1"
	WHERE="WHERE EndTime <> 0 AND SessionRecord_$1.SessionIndex = SessionTable_$1.SessionIndex
	    AND ChildIndex = $2 AND UserIndex = $3"
	ORDER="ORDER BY StartTime"
elif [ $4 -eq 0 ];then
    	SELECT="SELECT ChildIndex AS \"Child Index\", SessionInstance AS \"Session Id\", SessionName AS \"Session Name\", StartTime AS \"Start Time\", (EndTime-StartTime) As \"Total Time\", Status AS \"Status\""
	FROM="FROM SessionRecord_$1, SessionTable_$1"
	WHERE="WHERE EndTime <> 0 AND SessionRecord_$1.SessionIndex = SessionTable_$1.SessionIndex
	    AND ChildIndex = $2 AND UserIndex = $3"
	ORDER="ORDER BY StartTime"
else 
	echo "ERROR: Valid values of wan-env 0 or 1"
fi

if [ $RPO -eq 1 ];then
	WHERE="$WHERE AND isRunPhase = true"
fi

log_query
run_nd_query
show_query_result

exit 0
