#!/bin/sh

# Name  : nsi_show_gateway_config

# Author: Achint
# usage :
#         nsi_show_gateway_config
#Script will show the Entity, Interface and Gateway.
#Output will be in following format
# entity interface gateway-address 
#  C|eth0|20.0.0.1
#  C|eth1|20.0.0.1
#  S|eth0|10.0.0.1
#  S|eth0|20.0.0.1
#  S|eth1|10.0.0.1
# Modification History:
#   07/28/06  Initial version

#IP entries file is now no longer Controller specific . It will now only be created in /home/cavisson/work
IP_ENTRIES=/home/cavisson/work/sys/ip_entries
TEMP=/tmp/temp.$$

get_ip_fields()
{
  ENTITY=`echo $1 | cut -d "|" -f1`
  GATEWAY=`echo $1 | cut -d "|" -f8`
  INTERFACE=`echo $1 | cut -d "|" -f10`
}

while read line
do
  #Extracting the Entity,Gateway and Interface from particular line of IP Entries file.
  get_ip_fields $line
  if [ $GATEWAY != "-" ];then
    echo "$ENTITY|$INTERFACE|$GATEWAY" >>$TEMP
  fi  
done <$IP_ENTRIES
echo "Entity|Interface|Gateway-Address"
if [ -f $TEMP ];then
  sort -u $TEMP
  rm -f $TEMP
fi
exit 0



