#!/bin/bash

#args: TR-NUM Parent-obj-type obj-name loc-selection acc-selection run-time-flag
if [ $# -lt 5 ];then
    	echo "Usage: nsi_get_5a TR-NUM parent-obj-type parent-obj-name loc-selection acc-selection run-time_flag"
	echo "TR-NUM is the test run number"
	echo "parent-obj-type can be 2: Tx 3:Sess"
	echo "obj-name : Tx or Session name"
	echo "location-slectection: All for all otherwise location name"
	echo "access-slectection: All for all otherwise access name"
	echo "run-time-flag is 1 for run-time phase only, otherwise 0"
	exit 1
fi

TRNUM=$1

if [ "XX" == "XX$NS_WDIR" ]
then
  NS_WDIR=/home/cavisson/work
fi

. $NS_WDIR/bin/nsi_db_utils
set_query_files $TRNUM

if [ $# -eq 5 ];then
	RPO=0
else
	RPO=$6
fi

NEED_SESS_REC=1
if [ $4 = "All" -a $5 = "All" ];then
	NEED_SESS_REC=0
fi

#To exclude failed records. URLs are always excluded, aggrgates are excluded
#based on config
if [ -f $NS_WDIR/logs/TR$1/exclude_failed_aggregate ];then
	EXCLUDE=1
else
	EXCLUDE=0
fi

#Add obj name
if [ $2 -eq 2 ];then
    SELECT="SELECT round(avg(TransactionRecord_$1.ThinkDuration)) AS \"Avg Think Time\", count(*) AS Total"
    WHERE="WHERE TransactionTable_$1.TransactionName = ""'"$3"'"
    WHERE="$WHERE AND TransactionRecord_$1.TransactionIndex = TransactionTable_$1.TransactionIndex"
    FROM="FROM  TransactionTable_$1, TransactionRecord_$1"
    if [ $EXCLUDE -eq 1 ];then
        WHERE="$WHERE AND TransactionRecord_$1.Status = 0"
    fi
elif [ $2 -eq 3 ];then
    SELECT="SELECT round(avg(ThinkDuration)) AS \"Avg Think Time\", count(*) AS Total"
    WHERE="WHERE SessionTable_$1.SessionName = ""'"$3"'"
    WHERE="$WHERE AND SessionRecord_$1.SessionIndex = SessionTable_$1.SessionIndex"
    FROM="FROM  SessionTable_$1, SessionRecord_$1"
    if [ $EXCLUDE -eq 1 ];then
        WHERE="$WHERE AND SessionRecord_$1.Status = 0"
    fi
    NEED_SESS_REC=0
else
    echo "Invalid object-type (valid values 2 or 3)"
    exit 1
fi

if [ $RPO -eq 1 ];then
	WHERE="$WHERE AND isRunPhase = true"
	if [ $2 -eq 2 ];then
    	    NEED_SESS_REC=1
	fi
fi

if [ $NEED_SESS_REC -eq 1 ];then
        WHERE="$WHERE AND TransactionRecord_$1.SessionInstance = SessionRecord_$1.SessionInstance
        AND TransactionRecord_$1.ChildIndex = SessionRecord_$1.ChildIndex" 
        FROM="$FROM,  SessionRecord_$1"
fi

#Add Location/Access
if [ $4 != "All" ];then
    WHERE="$WHERE AND Location = ""'"$4"'"
fi

if [ $5 != "All" ];then
    WHERE="$WHERE AND Access = ""'"$5"'"
fi


log_query
run_nd_query
show_query_result
exit 0
