#! /bin/sh

# Basename is exported from nsi_upgrade shell
export WORK=$BASENAME

RELEASE_CMD="nsi_get_linux_release_ex"
DISTRO=`$RELEASE_CMD -d`
msgout_both "Uncompressing tar file - $GZ"
cp $NS_WDIR/.rel/$GZ .
tar xvzf $GZ >> $LOG_FILE_NAME
rm $GZ

if [ "$?" != 0 ];then
  msgout_both "Error: Error in uncompressing the $GZ"
  exit 1
fi

cp -r ndp/* .
rm -rf ndp

#chown -R cavisson. $NS_WDIR/bin

#Change the directory owner:group
#chown -R cavisson. ndp

exit 0
