#!/bin/bash

#Taking input from c program
TEST_RUN=$1

GEN_DATA_FILE="$NS_WDIR/etc/.netcloud/generators.dat"
DEBUG_LOG_FILE="$NS_WDIR/logs/TR$TEST_RUN/NetCloud/gen_inst.netstorm.log"
CAV_GEN_USED_FILE="$NS_WDIR/logs/TR$TEST_RUN/NetCloud/cav_gen.used"
TMP_FILE=/tmp/gen_file.$$
GEN_DATA_TEMP_FILE="$NS_WDIR/etc/.netcloud/.generators.dat.temp"

export gen_name=""
debug_log()
{
  echo "`date "+%D %H:%M:%S"`|$*" >> $DEBUG_LOG_FILE
}

Lockfd=10
ns_release_lock()
{
  #Release lock only if it is acquired earlier
  flock -u $Lockfd
  eval "exec $Lockfd<&-"
}

ns_get_lock()
{
  retry_count=12
  ctrl_name=`basename $NS_WDIR`
  mkdir -p $HOME_DIR/.tmp/
  Lockfile=$HOME_DIR/.tmp/.nc_gen_lock_${ctrl_name}
  if [ ! -e "$Lockfile" ] ; then
      touch "$Lockfile"
  fi
  eval "exec $Lockfd<$Lockfile"
  for((i=0;i<$retry_count;i++))
  {
    flock -eno $Lockfd || { debug_log "File '$Lockfile' is locked. Will try again after 5 second"; sleep 5;continue; }
    return 0;
  }
  return 1;
}

while read gen_name
do
   #stop generators using nsi_stop_generator shell
   debug_log "Stopping generator $gen_name"
   nsi_stop_generator -t $TEST_RUN -g $gen_name >>$DEBUG_LOG_FILE 2>&1 &
done <$CAV_GEN_USED_FILE

sleep 30
ns_get_lock
if [ $? -eq 0 ];then
  debug_log "Checking test on generators is running or not"
  while read gen_name
  do
     awk 'BEGIN{FS=OFS="|"} $1==ENVIRON["gen_name"]{$13=1} 0' $GEN_DATA_FILE > $GEN_DATA_TEMP_FILE
     mv $GEN_DATA_TEMP_FILE $GEN_DATA_FILE
  done < $CAV_GEN_USED_FILE 
else
  debug_log "Failed to aquired lock"
fi
ns_release_lock

