#!/bin/bash

#args: TR-NUM Parent-tx pgidx loc-selection acc-selection url-tye

. $NS_WDIR/bin/nsi_db_utils

NEED_SESS_REC=1
if [ $4 = "All" -a $5 = "All" ];then
	NEED_SESS_REC=0
fi

SELECT="SELECT UrlName AS \"URL\", 
	round(avg(ConnectStartTime-UrlRecord_$1.StartTime)) AS \"DNS Lookup\",
	round(avg(ConnectDoneTime-ConnectStartTime)) AS \"Connection Time\",
	round(avg(SSLHandShakeDone-ConnectDoneTime)) AS \"SSL Handshake\",
	round(avg(WriteCompleTime-SSLHandShakeDone)) AS \"Send Time\",
	round(avg(FirstByteRcdTime-WriteCompleTime)) AS \"First Byte\",
	round(avg(RequestCompletedTime-FirstByteRcdTime)) AS \"Download Time\",
 	URLTable_$1.UrlIndex AS \"UrlIndex\""
FROM="FROM UrlRecord_$1, UrlTable_$1"
WHERE="WHERE UrlRecord_$1.Status = 0 AND UrlRecord_$1.PageIndex = $3
	AND UrlRecord_$1.UrlIndex = UrlTable_$1.UrlIndex"
GROUP="GROUP BY UrlName , URLTable_$1.UrlIndex"
ORDER="ORDER BY UrlName , URLTable_$1.UrlIndex"

if [ $RPO -eq 1 ];then
	WHERE="$WHERE AND isRunPhase = true"
	NEED_SESS_REC=1
fi

if  [ $6 -eq 1 ];then
	WHERE="$WHERE AND UrlType = 1"
elif  [ $6 -eq 2 ];then
	WHERE="$WHERE AND UrlType = 2"
elif  [ $6 -eq 3 ];then
	WHERE="$WHERE AND UrlType = 3"
else
	echo "ERROR: url type can be 1-3"
	exit 1
fi

if [ $NEED_SESS_REC -eq 1 ];then
        WHERE="$WHERE AND UrlRecord_$1.SessionInstance = SessionRecord_$1.SessionInstance
        AND UrlRecord_$1.ChildIndex = SessionRecord_$1.ChildIndex" 
        FROM="$FROM,  SessionRecord_$1"
fi

#Add obj name
if [ $2 != "All" ];then
    WHERE="$WHERE AND TransactionTable_$1.TransactionName = ""'"$2"'"
    WHERE="$WHERE AND UrlRecord_$1.TransactionIndex = TransactionTable_$1.TransactionIndex"
    FROM="$FROM,  TransactionTable_$1"
fi

#Add Location/Access
if [ $4 != "All" ];then
    WHERE="$WHERE AND Location = ""'"$4"'"
fi

if [ $5 != "All" ];then
    WHERE="$WHERE AND Access = ""'"$5"'"
fi

log_query
run_query
show_query_result

exit 0
