#!/bin/bash


#######################################################################################################
# Name   : nsi_db_get_page_status
# Example:
# Initial version :It gives the status of page, GUI will use it in screen.
#   Author: Nikita Pandey
#   Date: 25/08/2012
#              nsi_db_get_page_status --testrun <value> --childidx <value> --object <value> --sessioninst <value> --pageinst <value> --urlidx <value>
#     (2) Example
#        nsi_db_get_page_status --testrun 9805 --childidx 2 --object 1 --sessioninst 0 --pageinst 3
#     (3) Output Format
#pageinstance|pagename|errorname
#########################################################################################################

. $NS_WDIR/bin/nsi_db_utils
TRNUM=$1
DEBUG=0
STARTTIME_SEL=0
debug_logs()
{
  if [ "X$DEBUG" != "X0" ];then
    echo "$*"
  fi
}
usage()
{
  echo "$*"
  echo "$0 --testrun <value> --object <value> --pageinst <value> --childidx <value> --sessioninst <value> --urlidx <value>
        --txinst <value>"
  echo ""
  echo "WHERE"
  echo "  --testrun is test run number, which is mandatory argument."
  echo "  --object is object selection(0-URL, 1-Page, 2-Transaction, 3-Session), which is mandatory argument."
  echo "  --childidx is the child index, which is mendatory argument."
  echo "  --sessioninst is the session instance, which is mendatory argument."
  echo "  --pageinst is the page instance, which is mendatory argument."
  echo "  --txinst is the transaction instance, which is mendatory argument."
  echo "  --urlidx  the urlindx, which is mendatory argument."
  exit 1
}


chk_args_for_url()
{
  #debug_logs "Method debug_logs called."
  if [ $OBJECT -eq 0 ]; then

    if [ "X$TRNUM" == "X" ]; then
      usage "Test run argument is missing"
    fi
    if [ "X$PAGEINST" == "X" ]; then
      usage "page instance is missing"
    fi
    if [ "X$SESSIONINST" == "X" ]; then
      usage "sesion instance is missing"
    fi
    if [ "X$CHILDIDX" == "X" ]; then
      usage "child index is missing"
    fi
    if [ "X$OBJECT" == "X" ]; then
      usage "object type is missing"
    fi
  fi
}

chk_args_for_page()
{
  #debug_logs "Method debug_logs called."
  if [ $OBJECT -eq 1 ]; then

    if [ "X$TRNUM" == "X" ]; then
      usage "Test run argument is missing"
    fi
    if [ "X$PAGEINST" == "X" ]; then
      usage "page instance is missing"
    fi
    if [ "X$SESSIONINST" == "X" ]; then
      usage "sesion instance is missing"
    fi
    if [ "X$CHILDIDX" == "X" ]; then
      usage "child index is missing"
    fi
    if [ "X$OBJECT" == "X" ]; then
      usage "object type is missing"
    fi
  fi
}


chk_args_for_transaction()
{
  #debug_logs "Method debug_logs called."
  if [ $OBJECT -eq 2 ]; then

    if [ "X$TRNUM" == "X" ]; then
      usage "Test run argument is missing"
    fi
    if [ "X$TXINST" == "X" ]; then
      usage "transaction instance is missing"
    fi
    if [ "X$SESSIONINST" == "X" ]; then
      usage "sesion instance is missing"
    fi
    if [ "X$CHILDIDX" == "X" ]; then
      usage "child index is missing"
    fi
    if [ "X$OBJECT" == "X" ]; then
      usage "object type is missing"
    fi
  fi
}


chk_args_for_session()
{
  #debug_logs "Method debug_logs called."
  if [ $OBJECT -eq 3 ]; then

    if [ "X$TRNUM" == "X" ]; then
      usage "Test run argument is missing"
    fi
    if [ "X$SESSIONINST" == "X" ]; then
      usage "sesion instance is missing"
    fi
    if [ "X$CHILDIDX" == "X" ]; then
      usage "child index is missing"
    fi
    if [ "X$OBJECT" == "X" ]; then
      usage "object type is missing"
    fi
  fi
}

if [ "X$1" == "X" ];then
  usage
fi

while [ "$1" != "" ];do
  #debug_logs "ARGS=$TRNUM"
  case $1 in
    "--testrun")
        shift
        TRNUM=$1;;
    "--object")
        shift
        OBJECT=$1;;
    "--pageinst")
        shift
        PAGEINST=$1;;
    "--sessioninst")
        shift
        SESSIONINST=$1;;
    "--txinst")
        shift
        TXINST=$1;;
    "--urlidx")
        shift
        URLIDX=$1;;
    "--childidx")
        shift
        CHILDIDX=$1;;
    "--starttime")
        shift
        STARTTIME_SEL=1
        STARTTIME=$1;;
    "--abs_starttime")
        shift
        ABS_STARTTIME=$1;;
    --*) usage "Invalid options";;
    *) usage ;;
  esac
  shift
done



if [ "XX" == "XX$NS_WDIR" ]
then
  NS_WDIR=/home/cavisson/work
fi

set_query_files $TRNUM

if [ "X$STARTTIME" != "X" -o "X$ABS_STARTTIME" != "X" ]; then
  handle_time_filters $TRNUM
fi

#Add obj name
if [ $OBJECT -eq 0 ];then

  OBJ="UrlRecord_$TRNUM"
  WHERE="WHERE  UrlRecord_$TRNUM.PageInstance = $PAGEINST AND"

  if [ $STARTTIME_SEL -eq 1 ];then
    WHERE="$WHERE  $OBJ.StartTime = $STARTTIME AND"
  fi
  if [ "X$ABS_STARTTIME" == "X1" ];then
    WHERE="$WHERE  $OBJ.StartTime = $ABS_STARTTIME AND"
  fi

  INST="UrlIndex"


elif [ $OBJECT -eq 1 ];then

  OBJ="PageRecord_$TRNUM"
  WHERE="WHERE  UrlRecord_$TRNUM.PageInstance = $PAGEINST AND"
  INST="PageIndex"

  if [ $STARTTIME_SEL -eq 1 ];then
    WHERE="$WHERE  $OBJ.StartTime = $STARTTIME AND"
    WHERE="$WHERE  UrlRecord_$TRNUM.StartTime = $STARTTIME AND"
  fi
  if [ "X$ABS_STARTTIME" == "X1" ];then
    WHERE="$WHERE  $OBJ.StartTime = $ABS_STARTTIME AND"
    WHERE="$WHERE  UrlRecord_$TRNUM.StartTime = $ABS_STARTTIME AND"
  fi


elif [ $OBJECT -eq 2 ];then

  OBJ="TransactionRecord_$TRNUM"
  if [  -f $NS_WDIR/logs/TR$TRNUM/reports/csv/tprc.csv ];then
    WHERE="WHERE  TransPageRecord_$TRNUM.TransactionIndex = $OBJ.TransactionIndex AND $OBJ.TxInstance = $TXINST AND $OBJ.TransactionIndex IS NOT NULL AND"
    #FROM="$FROM , TransPageRecord_$TRNUM"
  else
    WHERE="WHERE  URLRecord_$TRNUM.TransactionIndex = $OBJ.TransactionIndex AND UrlRecord_$TRNUM.TxInstance = $TXINST AND UrlRecord_$TRNUM.TransactionIndex IS NOT NULL AND"
  fi
  INST="TransactionIndex"

  if [ $STARTTIME_SEL -eq 1 ];then
    WHERE="$WHERE  $OBJ.StartTime = $STARTTIME AND"
    WHERE="$WHERE  UrlRecord_$TRNUM.StartTime = $STARTTIME AND"
  fi
  if [ "X$ABS_STARTTIME" == "X1" ];then
    WHERE="$WHERE  $OBJ.StartTime = $ABS_STARTTIME AND"
    WHERE="$WHERE  UrlRecord_$TRNUM.StartTime = $ABS_STARTTIME AND"
  fi


elif [ $OBJECT -eq 3 ];then

  OBJ="SessionRecord_$TRNUM"
  WHERE="WHERE "
  INST="SessionIndex"

  if [ $STARTTIME_SEL -eq 1 ];then
    WHERE="$WHERE  $OBJ.StartTime = $STARTTIME AND"
  fi
  if [ "X$ABS_STARTTIME" == "X1" ];then
    WHERE="$WHERE  $OBJ.StartTime = $ABS_STARTTIME AND"
  fi

else

  echo "Invalid object-type (valid values 0-3)"
  exit 1

fi


#case 1: When ND is disable and ect.csv file is not present in TR
if [ -f $NS_WDIR/logs/TR$TRNUM/reports/csv/ect.csv ];then
  ECT_FLAG=1
fi

check_is_nd_enabled
#ISND=`cat $NS_WDIR/logs/TR$TRNUM/sorted_*.conf | grep G_ENABLE_NET_DIAGNOSTICS | cut -d ' ' -f3`

if [ $ISND -ne 1 -a $ECT_FLAG -ne 1 ];then

  SELECT="SELECT PageInstance, PageName, PageRecord_$TRNUM.Status"

  FROM="FROM  URLRecord_$TRNUM, PageTable_$TRNUM, URLTable_$TRNUM"
  WHERE="$WHERE UrlRecord_$TRNUM.PageIndex = PageTable_$TRNUM.PageIndex
      AND URLRecord_$TRNUM.URLIndex = URLTable_$TRNUM.URLIndex
      AND $OBJ.ChildIndex = $CHILDIDX
      AND $OBJ.SessionInstance = $SESSIONINST
      AND UrlRecord_$TRNUM.pageindex = PageTable_$TRNUM.pageindex"

  if [ $OBJECT -eq 1 ];then
    WHERE="$WHERE AND PageRecord_$TRNUM.ChildIndex = UrlRecord_$TRNUM.ChildIndex AND"
    WHERE="$WHERE $NEWLINE PageRecord_$TRNUM.SessionInstance = UrlRecord_$TRNUM.SessionInstance AND"
    WHERE="$WHERE $NEWLINE UrlRecord_$TRNUM.PageInstance = PageRecord_$TRNUM.PageInstance"
    FROM="$FROM, $OBJ"
  fi

  if [ $OBJECT -eq 2 ];then
    WHERE="$WHERE $NEWLINE AND TransactionRecord_$TRNUM.ChildIndex = PageRecord_$TRNUM.ChildIndex"
    WHERE="$WHERE $NEWLINE AND TransactionRecord_$TRNUM.SessionInstance = UrlRecord_$TRNUM.SessionInstance"
    WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.PageIndex = PageTable_$TRNUM.PageIndex"
    FROM="$FROM, $OBJ"

    if [  -f $NS_WDIR/logs/TR$TRNUM/reports/csv/tprc.csv ];then
      WHERE="$WHERE $NEWLINE AND TransPageRecord_$TRNUM.pageinstance = PageRecord_$TRNUM.pageinstance"
      WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.childindex = TransPageRecord_$TRNUM.childindex"
      WHERE="$WHERE $NEWLINE AND TransPageRecord_$TRNUM.sessioninstance = PageRecord_$TRNUM.sessioninstance"
      WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.PageIndex = PageTable_$TRNUM.PageIndex"
      FROM="$FROM, TransPageRecord_$TRNUM"
    fi
  fi

  if [ $OBJECT -eq 3 ];then
    WHERE="$WHERE $NEWLINE AND SessionRecord_$TRNUM.SessionInstance = PageRecord_$TRNUM.SessionInstance"
    WHERE="$WHERE $NEWLINE AND SessionRecord_$TRNUM.ChildIndex = pageRecord_$TRNUM.ChildIndex"
    WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.PageIndex = PageTable_$TRNUM.PageIndex"
    FROM="$FROM, $OBJ"
  fi
fi

#Case2: When ND is disable but ect.csv file is present in TR

StatusFlag=0

if [ $ECT_FLAG -eq 1  -a $ISND -ne 1 ];then

  SELECT="SELECT URLRecord_$TRNUM.PageInstance, PageName, 
        ErrorName"
  FROM="FROM  URLRecord_$TRNUM, PageTable_$TRNUM, URLTable_$TRNUM, ErrorCodes_$TRNUM,PageRecord_$TRNUM"
  if [ $OBJECT -eq 0 ];then
    WHERE="$WHERE UrlRecord_$TRNUM.PageIndex = PageTable_$TRNUM.PageIndex"
    WHERE="$WHERE $NEWLINE AND URLRecord_$TRNUM.URLIndex = URLTable_$TRNUM.URLIndex"
    WHERE="$WHERE $NEWLINE AND URLRecord_$TRNUM.ChildIndex = $CHILDIDX"
    WHERE="$WHERE $NEWLINE AND URLRecord_$TRNUM.SessionInstance = $SESSIONINST"
    WHERE="$WHERE $NEWLINE AND ErrorCodes_$TRNUM.errorcode =  PageRecord_$TRNUM.Status"
    WHERE="$WHERE $NEWLINE AND ErrorCodes_$TRNUM.ObjectType = 1"
    WHERE="$WHERE $NEWLINE AND UrlRecord_$TRNUM.pageindex = PageTable_$TRNUM.pageindex"
  fi

if [ $OBJECT -eq 1 ];then
#  FROM="$FROM, $OBJ"
  WHERE="$WHERE PageRecord_$TRNUM.ChildIndex = $CHILDIDX"
  WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.SessionInstance = $SESSIONINST"
  WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.PageIndex = UrlRecord_$TRNUM.PageIndex"
  WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.PageInstance = UrlRecord_$TRNUM.PageInstance"
  WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.ChildIndex = UrlRecord_$TRNUM.ChildIndex"
  WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.SessionInstance = UrlRecord_$TRNUM.SessionInstance"
  WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.PageIndex = PageTable_$TRNUM.PageIndex"
  WHERE="$WHERE $NEWLINE AND URLRecord_$TRNUM.URLIndex = URLTable_$TRNUM.URLIndex"
  WHERE="$WHERE $NEWLINE AND ErrorCodes_$TRNUM.errorcode = PageRecord_$TRNUM.Status"
  WHERE="$WHERE $NEWLINE AND ErrorCodes_$TRNUM.ObjectType = 1"
  WHERE="$WHERE $NEWLINE AND UrlRecord_$TRNUM.pageindex = PageTable_$TRNUM.pageindex"
fi

if [ $OBJECT -eq 2  ];then
  FROM="$FROM, $OBJ"
  WHERE="$WHERE $OBJ.ChildIndex = $CHILDIDX"
  WHERE="$WHERE $NEWLINE AND $OBJ.SessionInstance = $SESSIONINST"
  WHERE="$WHERE $NEWLINE AND $OBJ.ChildIndex = PageRecord_$TRNUM.ChildIndex"
  WHERE="$WHERE $NEWLINE AND $OBJ.SessionInstance = PageRecord_$TRNUM.SessionInstance"
  WHERE="$WHERE $NEWLINE AND ErrorCodes_$TRNUM.errorcode = PageRecord_$TRNUM.Status"
  WHERE="$WHERE $NEWLINE AND ErrorCodes_$TRNUM.ObjectType = 1"
  WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.pageindex = PageTable_$TRNUM.pageindex"

  if [  -f $NS_WDIR/logs/TR$TRNUM/reports/csv/tprc.csv ];then
    WHERE="$WHERE AND TransPageRecord_$TRNUM.pageinstance = PageRecord_$TRNUM.pageinstance"
    WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.childindex = TransPageRecord_$TRNUM.childindex"
    WHERE="$WHERE $NEWLINE AND TransPageRecord_$TRNUM.sessioninstance = PageRecord_$TRNUM.sessioninstance"
    WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.PageIndex = PageTable_$TRNUM.PageIndex"
    FROM="$FROM, TransPageRecord_$TRNUM"
  fi
fi

if [ $OBJECT -eq 3  ];then
  FROM="$FROM, $OBJ"
  WHERE="$WHERE $OBJ.ChildIndex = $CHILDIDX"
  WHERE="$WHERE $NEWLINE AND $OBJ.SessionInstance = $SESSIONINST"
  WHERE="$WHERE $NEWLINE AND $OBJ.ChildIndex = PageRecord_$TRNUM.ChildIndex"
  WHERE="$WHERE $NEWLINE AND $OBJ.SessionInstance = PageRecord_$TRNUM.SessionInstance"
  WHERE="$WHERE $NEWLINE AND ErrorCodes_$TRNUM.errorcode = PageRecord_$TRNUM.Status"
  WHERE="$WHERE $NEWLINE AND ErrorCodes_$TRNUM.ObjectType = 1"
  WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.PageIndex = PageTable_$TRNUM.PageIndex"
fi

 GROUP="GROUP BY  URLRecord_$TRNUM.PageInstance,PageName,ErrorName"
 ORDER="ORDER BY URLRecord_$TRNUM.PageInstance,PageName"

fi

#Case3: When Nd is enable and ect.csv is not present in TR

if [ $ISND -eq 1 -a $ECT_FLAG -eq 0 ];then

  SELECT="SELECT URLRecord_$TRNUM.PageInstance, PageName, PageRecord_$TRNUM.Status"
  FROM="FROM  URLRecord_$TRNUM, PageTable_$TRNUM, URLTable_$TRNUM, Flowpath_$TRNUM"
  WHERE="$WHERE UrlRecord_$TRNUM.PageIndex = PageTable_$TRNUM.PageIndex"
  WHERE="$WHERE $NEWLINE AND URLRecord_$TRNUM.URLIndex = URLTable_$TRNUM.URLIndex"
  WHERE="$WHERE $NEWLINE AND $OBJ.ChildIndex = $CHILDIDX"
  WHERE="$WHERE $NEWLINE AND $OBJ.SessionInstance = $SESSIONINST"
  WHERE="$WHERE $NEWLINE AND Flowpath_$TRNUM.FlowPathInstance = URLRecord_$TRNUM.FlowPathInstance"
  WHERE="$WHERE $NEWLINE AND UrlRecord_$TRNUM.pageindex = PageTable_$TRNUM.pageindex"

  if [ $OBJECT -eq 1 ];then
    WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.ChildIndex = UrlRecord_$TRNUM.ChildIndex"
    WHERE="$NEWLINE AND PageRecord_$TRNUM.SessionInstance = UrlRecord_$TRNUM.SessionInstance"
    WHERE="$NEWLINE AND UrlRecord_$TRNUM.PageInstance = PageRecord_$TRNUM.PageInstance"
    FROM="$FROM, $OBJ"
  fi

  if [ $OBJECT -eq 2 ];then
    WHERE="$WHERE $NEWLINE AND TransactionRecord_$TRNUM.ChildIndex = PageRecord_$TRNUM.ChildIndex"
    WHERE="$WHERE $NEWLINE AND TransactionRecord_$TRNUM.SessionInstance = PageRecord_$TRNUM.SessionInstance"
    WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.PageIndex = PageTable_$TRNUM.PageIndex"
    FROM="$FROM, $OBJ"

    if [  -f $NS_WDIR/logs/TR$TRNUM/reports/csv/tprc.csv ];then
      WHERE="$WHERE $NEWLINE AND TransPageRecord_$TRNUM.pageinstance = PageRecord_$TRNUM.pageinstance"
      WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.childindex = TransPageRecord_$TRNUM.childindex"
      WHERE="$WHERE $NEWLINE AND TransPageRecord_$TRNUM.sessioninstance = PageRecord_$TRNUM.sessioninstance"
      WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.PageIndex = PageTable_$TRNUM.PageIndex"
      FROM="$FROM, TransPageRecord_$TRNUM"
    fi

  fi

  if [ $OBJECT -eq 3 ];then
    WHERE="$WHERE $NEWLINE AND SessionRecord_$TRNUM.SessionInstance = PageRecord_$TRNUM.SessionInstance"
    WHERE="$WHERE $NEWLINE AND SessionRecord_$TRNUM.ChildIndex = PageRecord_$TRNUM.ChildIndex"
    WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.PageIndex = PageTable_$TRNUM.PageIndex"
    FROM="$FROM, $OBJ"
  fi

  GROUP="GROUP BY  URLRecord_$TRNUM.PageInstance,PageName,ErrorName"
  ORDER="ORDER BY URLRecord_$TRNUM.PageInstance,PageName"
fi

#Case4: When Nd is enable and ect.csv is  present in TR

if [ $ISND -eq 1 -a $ECT_FLAG -eq 1 ];then
  SELECT="SELECT URLRecord_$TRNUM.PageInstance, PageName, ErrorName"
  FROM="FROM  PageTable_$TRNUM, Flowpath_$TRNUM,ErrorCodes_$TRNUM,PageRecord_$TRNUM,URLRecord_$TRNUM"

  if [ $OBJECT -eq 0 ];then
      WHERE="$WHERE UrlRecord_$TRNUM.PageIndex = PageTable_$TRNUM.PageIndex"
      WHERE="$WHERE $NEWLINE AND UrlRecord_$TRNUM.ChildIndex = $CHILDIDX"
      WHERE="$WHERE $NEWLINE AND UrlRecord_$TRNUM.SessionInstance = $SESSIONINST"
      WHERE="$WHERE $NEWLINE AND Flowpath_$TRNUM.FlowPathInstance = URLRecord_$TRNUM.FlowPathInstance"
      WHERE="$WHERE $NEWLINE AND ErrorCodes_$TRNUM.errorcode =  PageRecord_$TRNUM.Status"
      WHERE="$WHERE $NEWLINE AND ErrorCodes_$TRNUM.ObjectType = 1"
      WHERE="$WHERE $NEWLINE AND UrlRecord_$TRNUM.pageindex = PageTable_$TRNUM.pageindex"
  fi

  if [ $OBJECT -eq 1 ];then
  #FROM="$FROM, $OBJ"
  WHERE="$WHERE PageRecord_$TRNUM.ChildIndex = $CHILDIDX"
  WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.SessionInstance = $SESSIONINST"
  WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.PageIndex = UrlRecord_$TRNUM.PageIndex"
  WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.PageInstance = UrlRecord_$TRNUM.PageInstance"
  WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.ChildIndex = UrlRecord_$TRNUM.ChildIndex"
  WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.SessionInstance = UrlRecord_$TRNUM.SessionInstance"
  WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.PageIndex = PageTable_$TRNUM.PageIndex"
  WHERE="$WHERE $NEWLINE AND ErrorCodes_$TRNUM.errorcode = PageRecord_$TRNUM.Status"
  WHERE="$WHERE $NEWLINE AND ErrorCodes_$TRNUM.ObjectType = 1"
  WHERE="$WHERE $NEWLINE AND Flowpath_$TRNUM.FlowPathInstance = URLRecord_$TRNUM.FlowPathInstance"
  WHERE="$WHERE $NEWLINE AND UrlRecord_$TRNUM.pageindex = PageTable_$TRNUM.pageindex"
  fi

  if [ $OBJECT -eq 2 ];then
    FROM="$FROM, $OBJ"
    WHERE="$WHERE $OBJ.ChildIndex = $CHILDIDX"
    WHERE="$WHERE $NEWLINE AND $OBJ.SessionInstance = $SESSIONINST"
    WHERE="$WHERE $NEWLINE AND $OBJ.ChildIndex = PageRecord_$TRNUM.ChildIndex"
    WHERE="$WHERE $NEWLINE AND $OBJ.SessionInstance = PageRecord_$TRNUM.SessionInstance"
    WHERE="$WHERE $NEWLINE AND ErrorCodes_$TRNUM.errorcode = PageRecord_$TRNUM.Status"
    WHERE="$WHERE $NEWLINE AND ErrorCodes_$TRNUM.ObjectType = 1"
    WHERE="$WHERE $NEWLINE AND Flowpath_$TRNUM.FlowPathInstance = URLRecord_$TRNUM.FlowPathInstance"
    WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.pageindex = PageTable_$TRNUM.pageindex"
      #AND UrlRecord_$TRNUM.PageIndex = PageTable_$TRNUM.PageIndex"

    if [  -f $NS_WDIR/logs/TR$TRNUM/reports/csv/tprc.csv ];then
      WHERE="$WHERE $NEWLINE AND TransPageRecord_$TRNUM.pageinstance = PageRecord_$TRNUM.pageinstance"
      WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.childindex = TransPageRecord_$TRNUM.childindex"
      WHERE="$WHERE $NEWLINE AND TransPageRecord_$TRNUM.sessioninstance = PageRecord_$TRNUM.sessioninstance"
      WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.PageIndex = PageTable_$TRNUM.PageIndex"
      FROM="$FROM, TransPageRecord_$TRNUM"
    fi

  fi

  if [ $OBJECT -eq 3 ];then
    FROM="$FROM, $OBJ"
    WHERE="$WHERE $OBJ.ChildIndex = $CHILDIDX"
    WHERE="$WHERE $NEWLINE AND $OBJ.SessionInstance = $SESSIONINST"
    WHERE="$WHERE $NEWLINE AND $OBJ.ChildIndex = PageRecord_$TRNUM.ChildIndex"
    WHERE="$WHERE $NEWLINE AND $OBJ.SessionInstance = PageRecord_$TRNUM.SessionInstance"
    WHERE="$WHERE $NEWLINE AND ErrorCodes_$TRNUM.errorcode = PageRecord_$TRNUM.Status"
    WHERE="$WHERE $NEWLINE AND ErrorCodes_$TRNUM.ObjectType = 1"
    WHERE="$WHERE $NEWLINE AND Flowpath_$TRNUM.FlowPathInstance = URLRecord_$TRNUM.FlowPathInstance"
    WHERE="$WHERE $NEWLINE AND PageRecord_$TRNUM.pageindex = PageTable_$TRNUM.pageindex"
      #AND UrlRecord_$TRNUM.PageIndex = PageTable_$TRNUM.PageIndex"
  fi
  GROUP="GROUP BY  URLRecord_$TRNUM.PageInstance,PageName,ErrorName"
  ORDER="ORDER BY URLRecord_$TRNUM.PageInstance,PageName"
fi

chk_args_for_session
chk_args_for_transaction
chk_args_for_page
chk_args_for_url
# Setting query files
set_query_files $TRNUM
log_query
run_nd_query
show_query_result

exit 0
