#!/bin/sh
#This shell is used to migrate scenario from 4.1.11 to 4.1.10 release. 
#Five keywords will be migrated : G_USE_SRC_IP, G_SERVER_HOST, G_SRC_IP_LIST, G_IP_VERSION_MODE, G_USE_SAME_NETID_SRC
SCENARIO_FILE_LIST="/tmp/scenario.list.$$"
SITE_KEYWORD_FILE="$NS_WDIR/sys/site_keywords.default"
#WORKSPACE+PROFILE
WORKSPACE=$2
NS_RTA_DIR="workspace/$WORK_SPACE/cavisson"

migrate_4111()
{
  while read SCENARIO
  do
    PREV_SCENARIO=`dirname ${SCENARIO}`"/."`basename ${SCENARIO}".post4.1.11"`
    cp $SCENARIO $PREV_SCENARIO
    sed -i "s/^G_USE_SRC_IP[ ]*ALL/USE_SRC_IP/g" $SCENARIO
    sed -i "s/^G_SERVER_HOST[ ]*ALL/SERVER_HOST/g" $SCENARIO
    sed -i "s/^G_SRC_IP_LIST[ ]*ALL/SRC_IP_LIST/g" $SCENARIO
    sed -i "s/^G_IP_VERSION_MODE[ ]*ALL/IP_VERSION_MODE/g" $SCENARIO
    sed -i "s/^G_USE_SAME_NETID_SRC[ ]*ALL/USE_SAME_NETID_SRC/g" $SCENARIO

    sed -i "/^G_USE_SRC_IP /d" $SCENARIO
    sed -i "/^G_SERVER_HOST/d" $SCENARIO
    sed -i "/^G_SRC_IP_LIST/d" $SCENARIO
    sed -i "/^G_IP_VERSION_MODE/d" $SCENARIO
    sed -i "/^G_USE_SAME_NETID_SRC/d" $SCENARIO
  done < $SCENARIO_FILE_LIST
}

find $NS_WDIR/$NS_RTA_DIR -not -name ".*" -name "*.conf" >$SCENARIO_FILE_LIST
if [ -f $SITE_KEYWORD_FILE ];then
  echo $SITE_KEYWORD_FILE >>$SCENARIO_FILE_LIST
fi

migrate_4111

rm -f $SCENARIO_FILE_LIST
