#!/bin/sh
                                                                                                                                 
sed 's/^[[:space:]]*$//g' log >log1
sed '/^$/{
        N
        /^\n$/D
}' log1 >log2
exit 0
