#
# Name: NSPostProcScen.sh
# Author: Neeraj Jain
# Purpsose: To post process Scenario Configuration file generated by GUI
#    - Add Header
#    - Add date/time of update
#    - Copy all keywords in the required sequence
#    - Add trailer at the end
#
# Usage:  NSPostProcScen.sh <Scenario Name> <User_name> <Profile_name>
#   e.g.  NSPostProcScen.sh TestScenario admin default
#
# Modification History:
#   08/31/04: Neeraj - Initial Version
#   15/03/21: Somin  - Change for Multiple Workspace
#

if [ "XX" = "XX$NS_WDIR" ]
then
  NS_WDIR=/home/cavisson/work
fi

if [ $# != 3 ]
then
  echo "Usage:"
  echo "NSPostProcScen.sh <Scenario Name>"
  echo "    e.g.  NSPostProcScen.sh TestScenario"
  exit -1
fi

WORK_PROFILE=`echo $1 | cut -d '/' '-f1-2'`
NS_RTA_DIR="workspace/$WORK_PROFILE/cavisson"
PROJ_SUBPOJ=`dirname $1`
SCEN_NAME=`basename $1`
ScenPath=$NS_WDIR/$NS_RTA_DIR/$PROJ_SUBPOJ/scenarios
ScenControlFile=$NS_WDIR/bin/ScenControl.dat
ScenFileName=$ScenPath/$SCEN_NAME.conf
ScenBakFileName=$ScenPath/$SCEN_NAME.conf.bak
ScenSaveFileName=$ScenPath/$SCEN_NAME.conf.save
ScenTmpFileName=$ScenPath/$SCEN_NAME.conf.bak.tmp$$
TmpFileName=$ScenPath/$SCEN_NAME.conf.tmp1$$

if [ ! -f  $ScenFileName ]
then
  echo "Scenario file not found, $ScenFileName"
  exit -1
fi

egrep -v "^#|^$"  $ScenFileName | sort > $ScenBakFileName

cp $ScenBakFileName $ScenSaveFileName

> $ScenFileName

AddHeader()
{
  echo "# Scenario File Name = $ScenFileName" >> $ScenFileName
  egrep HDR $ScenControlFile > $TmpFileName
  while read line 
  do
    set $line > /dev/null
    shift
    echo "# $*" >> $ScenFileName
  done < $TmpFileName
  echo "# Last updated on `date`" >> $ScenFileName

}

AddTrailer()
{
  egrep TRL $ScenControlFile > $TmpFileName
  while read line 
  do
    set $line > /dev/null
    shift
    echo "# $*" >> $ScenFileName
  done < $TmpFileName
}

CopyKeywords()
{

  while read line
  do
#    echo "Control file line is $line"
    set $line > /dev/null
    controlId=$1
    if [ $controlId != "KEYWORD" ]
    then
#      echo "Skipping Control file line $line"
      continue
    fi
    shift
    keyword=$1
    shift
    comment=$*
    echo "# $comment" >> $ScenFileName
    
    egrep "^$keyword" $ScenBakFileName > $TmpFileName
    while read line
    do
      echo $line >> $ScenFileName
    done < $TmpFileName
    
    egrep -v "^$keyword" $ScenBakFileName > $ScenTmpFileName
    mv $ScenTmpFileName $ScenBakFileName

  done < $ScenControlFile

  cat $ScenBakFileName  >> $ScenFileName

}


AddHeader
CopyKeywords
AddTrailer

rm -f $ScenTmpFileName $TmpFileName $ScenBakFileName

exit 0
