#!/bin/bash

if [ $# -lt 1 ];then
    echo "usage: $0 -s|-a interface1 interface2 .. |-d"
    echo " -s to show boinding"
    echo " -a to add boinding"
    echo " -d to delete boinding"
    exit 1
fi

if [ "XX$NS_WDIR" == "XX" ];then
	export NS_WDIR=/home/cavisson/work
fi

IP_BONDING=$NS_WDIR/sys/ip_bonding
IP_PROP=$NS_WDIR/sys/ip_properties

if [ $1 == "-s" ];then
    cat /proc/net/bonding/bond0
elif [ $1 == "-a" ];then
    if [ $# -lt 3 ];then
        echo "For adding a bond, atleast two interfaces must be specified"
	exit 1
    fi
    USERID=`id -u`
    if [ $USERID -ne 0 ];then
    	echo "You must be root to execute this command"
    	exit 1
    fi
    /sbin/modprobe bonding mode=2 miimon=100 xmit_hash_policy=layer3+4
    /sbin/ifconfig bond0 up

    shift
    while [ $# -ge 1 ]
    do
	/sbin/ifenslave bond0 $1
	echo "$1" >> $IP_BONDING
	shift
    done
    R_NETID=`cat  $IP_PROP | grep RESERVED_NETID | awk '{print $2}'`
    if [ ! -f $HOME_DIR/etc/cav.conf ];then
	echo "nsi_hpd_upgrade: Missing $HOME_DIR/etc/cav.conf"
	exit 1
    fi
    CONFIG=`cat $HOME_DIR/etc/cav.conf | grep CONFIG | awk '{print $2}'`
    if [ $CONFIG == 'NS' -o $CONFIG == 'NS>NO' -o $CONFIG == 'NC' ];then
       BONDIP=`${NS_WDIR}/bin/nsu_seq_ip ${R_NETID} 1`
    elif [ $CONFIG == 'NO' ];then
       BONDIP=`${NS_WDIR}/bin/nsu_seq_ip ${R_NETID} 2`
    else
       exit 0
    fi
    /sbin/ip addr add ${BONDIP}/24 dev bond0
    
elif [ $1 == "-d" ];then
    USERID=`id -u`
    if [ $USERID -ne 0 ];then
    	echo "You must be root to execute this command"
    	exit 1
    fi
    while read line
    do
	/sbin/ifenslave -d bond0 $line
	/sbin/ifup $line
    done <$IP_BONDING
    /sbin/ifconfig bond0 down
    /sbin/rmmod bonding
    > $IP_BONDING
else
    echo "usage: $0 -s|-a interface1 interface2 .. |-d"
    exit 1
fi

exit 0
