#!/bin/sh
# Name            : nsu_show_server 
# Purpose         : To show server
# Usage           : nsu_show_server [-a|-s <server1> <server2>..]
# Initial Version : Monday, April 27 2009 
#


usage()
{
  echo "nsu_show_server [-a | -s <Server1> <Server2>...|-i]"
  exit 1
}

validate_server()
{
  GIVEN_SERVER=$1

  echo "$GIVEN_SERVER" | grep '^\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}$' >/dev/null
  if [ $? -eq 0 ];then
    #Check if dotted part of IP is between 0-255

    XSPART=`echo "$GIVEN_SERVER" | cut -d. -f1`
    YSPART=`echo "$GIVEN_SERVER" | cut -d. -f2`
    ZSPART=`echo "$GIVEN_SERVER" | cut -d. -f3`
    WSPART=`echo "$GIVEN_SERVER" | cut -d. -f4`

    if [ $XSPART -gt 255 -o $YSPART -gt 255 -o $ZSPART -gt 255 -o $WSPART -gt 255 ];then
      return 1 
    fi
    if [ $XSPART -lt 0 -o $YSPART -lt 0 -o $ZSPART -lt 0 -o $WSPART -lt 0 ];then
      return 1 
    fi
  fi
  return 0
}

SHOW_ALL=1
RAW=0
SHOW_STATUS=0
STATUS=""
SERVER_FILE="$NS_WDIR/server/servers.dat"

while getopts airs:? arg 
do
  case $arg in
    a) SHOW_ALL="1";;
    s) SERVER_LIST="$OPTARG"
       SHOW_ALL="0";;
    i) SHOW_STATUS="1"
       HEADER="$HEADER STATUS";;
    r) RAW="1";;
    ?) usage;;
  esac
done

if [ ! -f $SERVER_FILE ];then
   echo "$SERVER_FILE does not exist"
   exit 1
fi

if [ $SHOW_ALL == 1 ];then
   SERVER_LIST=`cat $SERVER_FILE | awk -F'|' '!/^#/  {print $1}' | sort -u`
fi

if [ $SHOW_STATUS == 1 ];then
   if [ $RAW == 1 ];then
      echo "Server|Ssh|User|Password|Java Home|Installation Dir|Agentless|Machine Type|Status"
   else
      printf "%-20s %-4s %-20s %-20s %-30s %-30s %-6s %-15s %-4s\n" Server Ssh User Password "Java Home" "Installation Dir" Agentless "Machine Type" Status 
      printf "%-20s %-4s %-20s %-20s %-30s %-30s %-6s %-15s %-4s\n" ------ --- ---- -------- --------- ---------------- --------- ------------ ------ 
   fi
else
   if [ $RAW == 1 ];then
      echo "Server|Ssh|User|Password|Java Home|Installation Dir|Agentless|Machine Type"
   else
      printf "%-20s %-4s %-20s %-20s %-30s %-30s %-6s %-15s %-4s\n" Server Ssh User Password "Java Home" "Installation Dir" Agentless "Machine Type" 
      printf "%-20s %-4s %-20s %-20s %-30s %-30s %-6s %-15s %-4s\n" ------ --- ---- -------- --------- ---------------- --------- ------------
   fi
fi


for show in $SERVER_LIST
do
  if [ $SHOW_ALL == 0 ];then
    validate_server $show
    if [ $? != 0 ];then
      continue;
    fi 
  fi
  OUTPUT=`cat $SERVER_FILE | grep "^$show|" | sed 's/|/ /g'`

  if [ "XX$OUTPUT" != "XX" ];then
    if [ $SHOW_STATUS == 1 ];then
      ping -c 1 -W 1 $show >/dev/null 2>&1
      if [ $? == 0 ];then
        STATUS="UP"
      else
        STATUS="DOWN"
      fi
    fi
  else
    STATUS="NA"
    OUTPUT="NA NA NA NA NA NA NA NA"   
  fi
  set $OUTPUT
  if [ $RAW == 1 ];then
    if [ "XX$STATUS" == "XX" ];then
      echo "$1|$2|$3|$4|$5|$6|$7|$8"
    else
      echo "$1|$2|$3|$4|$5|$6|$7|$8|$STATUS"
    fi
  else
    printf "%-20s %-4s %-20s %-20s %-30s %-30s %-6s %-15s %-4s\n" $1 $2 $3 $4 $5 $6 $7 $8 $STATUS
  fi
done

exit 0
