#! /bin/sh

#Here we are creating indexes for tables
#Index will enhance database performance (indexes can be used to obtain fast access)

if [ -d $PWD/TR$1 ]; then
  BASE_DIR=$PWD
elif [ -d $NS_WDIR/logs/TR$1 ]; then
  BASE_DIR=$NS_WDIR/logs
else
  echo "Error: Test run number $1 is not a valid test run number"
  exit -1
fi

echo "nsu_drop_index: Please wait indexes will be dropped ..."
START=`date +%s`

psql test cavisson <<+
DROP INDEX IF EXISTS urc_start_time_$1; 
DROP INDEX IF EXISTS urc_end_time_$1; 
DROP INDEX IF EXISTS urc_urlidx_start_time_$1; 
DROP INDEX IF EXISTS urc_urlidx_end_time_$1; 
DROP INDEX IF EXISTS urc_url_index_$1;  
DROP INDEX IF EXISTS urc_page_index_$1; 
DROP INDEX IF EXISTS urc_session_index_$1; 
DROP INDEX IF EXISTS urc_tx_index_$1; 
DROP INDEX IF EXISTS urc_fpi_$1; 
DROP INDEX IF EXISTS urc_phase_index_$1;
DROP INDEX IF EXISTS urc_status_$1; 
DROP INDEX IF EXISTS urc_all_index_$1; 
DROP INDEX IF EXISTS urc_response_time_$1;
DROP INDEX IF EXISTS urc_generator_id_$1;

DROP INDEX IF EXISTS prc_start_time_$1; 
DROP INDEX IF EXISTS prc_end_time_$1; 
DROP INDEX IF EXISTS prc_pageidx_start_time_$1; 
DROP INDEX IF EXISTS prc_pageidx_end_time_$1; 
DROP INDEX IF EXISTS prc_all_index_$1; 
DROP INDEX IF EXISTS prc_all_trans_index_$1;
DROP INDEX IF EXISTS prc_response_time_$1; 
DROP INDEX IF EXISTS prc_generator_id_$1;
DROP INDEX IF EXISTS prc_phase_index_$1; 

DROP INDEX IF EXISTS trc_start_time_$1; 
DROP INDEX IF EXISTS trc_end_time_$1; 
DROP INDEX IF EXISTS trc_transidx_start_time_$1; 
DROP INDEX IF EXISTS trc_transidx_end_time_$1; 
DROP INDEX IF EXISTS trc_session_index_$1; 
DROP INDEX IF EXISTS trc_transaction_index_$1; 
DROP INDEX IF EXISTS trc_status_$1; 
DROP INDEX IF EXISTS trc_all_index_$1; 
DROP INDEX IF EXISTS trc_response_time_$1; 
DROP INDEX IF EXISTS trc_generator_id_$1;
DROP INDEX IF EXISTS trc_phase_index_$1; 

DROP INDEX IF EXISTS src_start_time_$1; 
DROP INDEX IF EXISTS src_end_time_$1; 
DROP INDEX IF EXISTS src_sessionidx_start_time_$1; 
DROP INDEX IF EXISTS src_sessionidx_end_time_$1; 
DROP INDEX IF EXISTS src_session_index_$1; 
DROP INDEX IF EXISTS src_status_$1; 
DROP INDEX IF EXISTS src_response_time_$1; 
DROP INDEX IF EXISTS src_generator_id_$1;
DROP INDEX IF EXISTS src_phase_index_$1; 

DROP INDEX IF EXISTS tprc_start_time_$1; 
DROP INDEX IF EXISTS tprc_end_time_$1; 
DROP INDEX IF EXISTS tprc_transidx_start_time_$1; 
DROP INDEX IF EXISTS tprc_transidx_end_time_$1; 
DROP INDEX IF EXISTS tprc_status_$1; 
DROP INDEX IF EXISTS tprc_all_index_$1;
DROP INDEX IF EXISTS tprc_response_time_$1; 
DROP INDEX IF EXISTS tprc_generator_id_$1;
DROP INDEX IF EXISTS tprc_phase_index_$1; 

DROP INDEX IF EXISTS urt_url_idx_$1; 
DROP INDEX IF EXISTS pgt_page_idx_$1; 
DROP INDEX IF EXISTS trt_trans_idx_$1; 
DROP INDEX IF EXISTS sst_session_idx_$1;

DROP INDEX IF EXISTS log_phase_table_phase_index_$1; 

DROP INDEX IF EXISTS page_dump_starttime_idx_$1;
DROP INDEX IF EXISTS page_dump_endtime_idx_$1;
DROP INDEX IF EXISTS page_dump_generatorid_idx_$1;
DROP INDEX IF EXISTS page_dump_pageindex_idx_$1;
DROP INDEX IF EXISTS page_dump_sessionindex_idx_$1;
DROP INDEX IF EXISTS page_dump_pagestatus_idx_$1;
DROP INDEX IF EXISTS page_dump_groupnum_idx_$1;

DROP INDEX IF EXISTS error_codes_objecttype_idx_$1;
DROP INDEX IF EXISTS error_codes_errorcode_idx_$1;
DROP INDEX IF EXISTS error_codes_errorname_idx_$1;

DROP INDEX IF EXISTS alert_history_key_idx_$1;
DROP INDEX IF EXISTS alert_history_timestamp_idx_$1;
DROP INDEX IF EXISTS alert_history_type_idx_$1;
DROP INDEX IF EXISTS alert_history_status_idx_$1;
DROP INDEX IF EXISTS alert_history_state_idx_$1;
DROP INDEX IF EXISTS alert_history_severity_idx_$1;
DROP INDEX IF EXISTS alert_history_prev_severity_idx_$1;
DROP INDEX IF EXISTS alert_history_rulename_idx_$1;
DROP INDEX IF EXISTS alert_history_baseline_idx_$1;

+

TR_DIR_PATH=$NS_WDIR/logs/TR$1
#READER_RUN_MODE=`grep "READER_RUN_MODE" $TR_DIR_PATH/sorted_scenario.conf | cut -d' ' -f2`
#if [ $READER_RUN_MODE -eq 0 ];then
if [ -f $TR_DIR_PATH/.oracle_sql_report ];then
  nsu_orl_drop_index $1 
elif [ -f $TR_DIR_PATH/common_files/.oracle_sql_report ];then
  nsu_orl_drop_index $1
fi
#fi

END=`date +%s`
#echo $END
#echo $START
DIFF=`expr $END - $START`
#echo $DIFF
echo "nsu_drop_index: Deletion of indexes took $DIFF seconds"
