#! /bin/bash

if [ "x$1" == "x" ];then
  echo "Testrun is not provided"
  echo "Usage : <Name Of The Shell> '<TR Number> "
  exit
fi

#check NS_WDIR is set or Not
if [ "X$NS_WDIR" == "X" ];then
    echo "NS_WDIR not set. Exiting"
    exit 1
fi

#check for existance of Testrun provided in the machine
if [ ! -d "$NS_WDIR/.recyclebin/" ]; then
    echo "Recycle Bin doesn't exists; Hence Exitting."
    exit 1
fi

IFS='| ' read -r -a array <<< $1
for i in ${array[@]}; do
        rm -rf $NS_WDIR/.recyclebin/TR$i/.remove_info
        mv $NS_WDIR/.recyclebin/TR$i $NS_WDIR/logs/
        if [ $? == 0 ];then
                echo "TR$i is restored successfully"
        else
                echo "TR$i is failed to restore"
        fi
done
