#!/bin/sh
#   03/03/21:Anup - Support new dir struct $NS_WDIR/workspace/<user_name>/<profile_name>/cavisson/<proj>/<sub_proj>/scripts
display_help_and_exit() 
{
  echo "Usage:"
  echo "sampleTest -p <project> -s <sub-project> -j <JMX script file path> -t <script type (c or java)> -a <acl_user_name> -w <work_profile_name>"
  exit 1
}

#usage
SCRIPT_DIR=$NS_WDIR

ACL_USER_NAME=admin
PROFILE_NAME=default
NS_TA_DIR=
#check if a dir exists
check_if_dir_exists()
{
 if [ ! -d $SCRIPT_DIR/$NS_TA_DIR/$1 ]; then
    echo "Project" $1 "is not present in $SCRIPT_DIR/$NS_TA_DIR directory. Provide a valid dir name."
    exit -1
 fi
}

#set NS_TA_DIR
NS_TA_DIR=workspace/$ACL_USER_NAME/$PROFILE_NAME/cavisson
#check if $PROJECT dir exists 
check_if_dir_exists $PROJECT
#check if $SUB_PROJECT dir exists 
check_if_dir_exists $SUB_PROJECT
 
echo "XXX $@ XXX" | grep "\-p" | grep "\-s" | grep "\-j" | grep "\-t" 2>/dev/null 1>&2

java -Djava.awt.headless=true -cp $JMETER_HOME/lib/*:$JMETER_HOME/lib/ext/*:$NS_WDIR/webapps/netstorm/lib/runlogic.jar:$NS_WDIR/webapps/netstorm/lib/swingx-all-1.6.4.jar:$NS_WDIR/webapps/netstorm/lib/netstorm_bean.jar:$NS_WDIR/webapps/netstorm/lib/jmeter-plugins-manager-0.19.jar:$NS_WDIR/webapps/netstorm/lib/json_simple-1.1.jar:$NS_WDIR/webapps/netstorm/lib/scriptconverter.jar:/home/cavisson/monitors/lib/java-getopt-1.0.9.jar:$NS_WDIR/thirdparty/gui_signed_jars/log4j-core-2.12.1.jar:$NS_WDIR/thirdparty/gui_signed_jars/log4j-api-2.12.1.jar:$NS_WDIR/thirdparty/gui_signed_jars/disruptor-3.4.2.jar -DNS_WDIR=$NS_WDIR -Dlog4j2.configurationFile=$NS_WDIR/webapps/.tomcat/log4j2/log4j2.xml com.cavisson.JmeterToNs.JmeterToNsScriptConverter $*

