#!/bin/sh

# Purpsose  : To delete script dir.
# Usage     : nsu_delete_script <Project/Subproject/Script Name>
#   e.g.  nsu_delete_script proj/sub_proj/test_ut_test
#
# Modification History:
#   02/06/09:3.2.2 Archana - Usage fix
#   02/10/09:3.2.3 Archana - To implement Project and Subprojects features

if [ $# -ne 1 ];then
  echo "Usage: nsu_delete_script <workspace_name/profile_name>/<Project/Subproject/Script Name>"
  exit 1
fi

if [ "XX$NS_WDIR" = "XX" ];then
  echo "NS_WDIR must be defined"
  exit 1
fi

exit_if_empty()
{
  if [ "X$1" == "X" ];then
   echo "Usage: nsu_delete_script <workspace_name/profile_name>/<Project/Subproject/Script Name>"
   exit 1
  fi
}
WORKSPACE=`echo $1 |cut -d  '/' -f1`
PROFILE=`echo $1 |cut -d  '/' -f2`
PROJ=`echo $1 |cut -d  '/' -f3`
SUB_PROJ=`echo $1 |cut -d  '/' -f4`
SCRIPT_NAME=`echo $1 |cut -d  '/' -f5`
exit_if_empty $WORKSPACE
exit_if_empty $PROFILE
exit_if_empty $PROJ
exit_if_empty $SUB_PROJ
DIR_NAME=$WORKSPACE/$PROFILE/cavisson/$PROJ/$SUB_PROJ
#DIR_NAME=`dirname $1`
#SCRIPT_NAME=`basename $1`
#SCRIPT_NAME=`basename $1`
NS_TA_DIR=workspace/$DIR_NAME
SCRIPT_PATH=$NS_WDIR/$NS_TA_DIR/scripts/$SCRIPT_NAME
if [ ! -d $SCRIPT_PATH ];then
  echo "script $1 does not exist"
  exit 1
fi

rm -rf $SCRIPT_PATH
if [ $? != 0 ];then
  echo "Unable to delete  script $1 "
  exit 1
fi

echo "script $1 deleted"
exit 0
