#!/bin/sh
#
# Name: nsu_ntlm_decoder
# Author: Ayush Kumar [03/09/2021]
# Purpsose: To decode ntlm authrization key 
#
#Refrence: https://gist.github.com/aseering/829a2270b72345a1dc42

if [ "$#" -ne 1 ];then
  echo "Error: Invaid number of argument"
  echo "Usage:"
  echo -e "\tnsu_ntlm_decoder \"<NTLM Key>\""
  exit 1
fi

cd $NS_WDIR
echo "$1" | ./bin/ntlmdecoder.py
cd -
exit 0
