#!/bin/bash
#header for printing header in output
ST=Status
OW=Owner
PR=Project/Subproject/Scenario
SD="Start Date and Time"
DR="Elapsed Time"
LONGLIST=0
exitstatus=0

if [ "XX" = "XX$NS_WDIR" ];then
	echo "ERROR: NS_WDIR env must be defined"
	exit 1
fi

Usage()
{
  echo "Usage:"
  echo "nsu_show_netstorm [-n <TR>] [-l]"
  echo "or"
  echo "nsu_show_netstorm <Tr> "
  echo "This command is used for getting list of all running test runs"
  echo "Where:"
  echo "      -n To show status of given test run. Default is all running tests"
  echo "      -l For long listing "
  exit 1
}

#Option argument parsing
if [ $# -eq 0 ];then
  ALL=1
else
  ALL=0 
  if [ "$1" != "-l" -a "$1" != "-n" ]; then
     TRNUM=$1
  fi

  while getopts ln:? c
  do
    case $c in
      l) LONGLIST=1;;
      n) TRNUM=$OPTARG;;
      ?) Usage;;
      *) Usage;;
    esac
  done


  #If test run is given, then make sure it is integer value
  if [ "X$TRNUM" != "X" ]; then
    #to check TRNUM is an integer or not
    echo $TRNUM |egrep '^[0-9]+$' >/dev/null
    if [ $? -ne 0 ];then
      echo "Test Run Number ($TRNUM) can be Integer only."
      exit 1
    fi
  fi
fi

if [ $ALL -eq 1 ];then   ## if no argument given
  nsu_show_test_logs -RL | awk '!/TestRun/{printf("%-10s%-10s%-20s%-s\n",$1,$2,$6,$7)}' >/tmp/nsu_show_netstorm.$$ 
  if [ -s /tmp/nsu_show_netstorm.$$ ]; then
    printf "%-10s%-10s%-20s%-s\n" "TestRun" "$ST" "$OW" "$PR"
    cat /tmp/nsu_show_netstorm.$$
  else
    exitstatus=1
  fi 
else
  if [ "X$LONGLIST" == "X1" -a "X$TRNUM" != "X" ]; then   ## if -l -n given
    ROW=`nsu_show_test_logs -RL|grep -w $TRNUM 2>/dev/null`
    if [ "X$ROW" != "X" ];then 
      printf "%-10s%-22s%-15s%-20s%-s\n" "$ST" "$SD" "$DR" "$OW" "$PR"
      echo $ROW |awk '{printf("%-10s%-10s%12-s%-15s%-20s%-s\n",$2,$3,$4,$5,$6,$7)}'
    else
      echo "Inactive"
      exitstatus=1
    fi
  elif [ "X$LONGLIST" == "X0" -a "X$TRNUM" != "X" ];then  ## if -n given
    nsi_show_test_logs -R -t $TRNUM >/dev/null 2>&1
    STATUS=$?
    if [ $STATUS -eq 1 ];then
      echo "Inactive"
      exitstatus=1
    else
      echo "Active"
      exitstatus=0
    fi
  else                                                  ## if -l given    
    nsu_show_test_logs -RL >/tmp/nsu_show_netstorm.$$
     if [ -s /tmp/nsu_show_netstorm.$$ ]; then
       cat /tmp/nsu_show_netstorm.$$
     else
       rm -f /tmp/nsu_show_netstorm.$$
      exitstatus=1
      fi
  fi
fi

rm -f /tmp/nsu_show_netstorm.$$ 

##To remove .tmp directories older than 7 days
#In Kohls we are running a NetCloud test for a month, hence need to comment this piece of code as it deletes inst file of running test.
#find $NS_WDIR/.tmp/* -type d -user `id -u -n` -mtime +6 -exec rm -rf {} \;  >/dev/null 2>&1

if [ $exitstatus -eq 1 ];then ##exit status of this shell should be 1 if no test run is running and 0 if running
  exit 1
else 
  exit 0
fi 
