#! /bin/sh

if [ -d $PWD/TR$1 ]; then
  BASE_DIR=$PWD
elif [ -d $NS_WDIR/logs/TR$1 ]; then
  BASE_DIR=$NS_WDIR/logs
else
  echo "Error: Test run number $1 is not a valid test run number"
  echo "Usage: nsu_orl_drop_table <testrun>"
  echo "Example:"
  echo "  nsu_orl_drop_table 127331"
  exit 1
fi

echo "nsu_orl_drop_table: Please wait table will be dropped ..."
START=`date +%s`

psql test cavisson <<+
drop table if exists orlStatsSQLIDTable_$1 cascade;
drop table if exists orlStatsSnapTable_$1 cascade;
drop table if exists orlStatsSQLStmtOrdByElapsedTime_$1 cascade;
drop table if exists orlStatsSQLStmtOrdByCPUTime_$1 cascade;
drop table if exists orlStatsSQLStmtOrdByUsrIOTime_$1 cascade;
drop table if exists orlStatsSQLStmtOrdByGets_$1 cascade;
drop table if exists orlStatsSQLStmtOrdByReads_$1 cascade;
drop table if exists orlStatsSQLStmtOrdByPhyReadsUnopt_$1 cascade;
drop table if exists orlStatsSQLStmtOrdByExec_$1 cascade;
drop table if exists orlStatsSQLStmtOrdByParseCalls_$1 cascade;
drop table if exists orlStatsSQLStmtOrdBySharableMemory_$1 cascade;
drop table if exists orlStatsSQLStmtOrdByVersionCount_$1 cascade;
drop table if exists orlStatsSQLStmtOrdByClusterWaitTime_$1 cascade;
+

END=`date +%s`
#echo $END
#echo $START
DIFF=`expr $END - $START`
#echo $DIFF
echo "nsu_orl_drop_table: Deletion of table took $DIFF seconds"

