#!/bin/sh

#Check and get login user name
USER_NAME=`whoami 2>/dev/null`
if [ $? != 0 ];then
  echo "Error: Unable to get the real user name"
  exit 1
fi

java -cp $NS_WDIR/webapps/DashboardServer/WEB-INF/lib/dashboardserver.jar:$NS_WDIR/webapps/DashboardServer/WEB-INF/lib/* -DNS_WDIR=$NS_WDIR com.cavisson.gui.server.webdashboard.utils.ImportJsonToDTOConverter $* 
exit $?
