#!/bin/sh

################################################################################################
#
# tomcat_restart
#
#     Purpose : To restart tomcat instaces for a particular controller
#    
#     Author  : Abhishek Mittal
#    
#     Date    : March 7, 2013
#    
#     History : 
#
################################################################################################


usage()
{
  echo "$*"
  echo 
  echo "USAGE:"
  echo "======"
  echo "$0 <Controller Name>"
  echo
  echo "Must be run as cavisson user"
  exit -1
}

USER=`whoami`
if [ "X$USER" != "Xcavisson" ];then
    echo "You must be logged in as cavisson user to execute this command"
    exit -1
fi

if [ "X$1" = "X" ]; then
  usage "Need controller name to restart"
fi

CMD=`basename $0`

BUF=(`ps -ef | grep tomcat | grep -w $1 | grep -v $CMD | awk -F ' ' '{print $2}'`)

if [ "X$BUF" != "X" ]; then 
  for((i = 0 ; i < ${#BUF[@]} ; i++))
  do
    PID=${BUF[$i]}
    echo "Stopped tomcat instance with PID=$PID successfully."
    kill -9 $PID 
  done
fi
  


if [ "$1" == "work" ]; then
  /etc/init.d/tomcat start
elif [ "$1" == "work2" ]; then 
  /etc/init.d/tomcat2 start
elif [ "$1" == "work3" ]; then
  /etc/init.d/tomcat3 start
else
  /etc/init.d/tomcat_$1 start
fi

BUF=(`ps -ef | grep tomcat | grep -w $1 | grep -v $CMD | awk -F ' ' '{print $2}'`)
if [ "X$BUF" == "X" ]; then 
  echo "Error in starting tomcat."
  exit -1
fi

PID=${BUF[@]}

echo "Newly started tomcat instance PID=$PID."

exit 0
