#!/bin/sh
#Resets IP configuration as dictated by sys_ip_entries file
#Needed after reboot

if [ "XX" = "XX$NS_WDIR" ];then
	echo "ERROR: NS_WDIR env must be defined"
	exit 1
fi

USER=`whoami`
if [ "X$USER" != "Xcavisson" ];then
    echo "You must be logged in as cavisson user to execute this command"
    exit -1
fi

# Due to multiple controllers, it was decided to keep ip_entries file in work
cp /home/cavisson/work/sys/ip_entries /home/cavisson/work/sys/ip_entries.save

echo "Deleting Earlier assigned address at Client"
$NS_WDIR/bin/nsu_del_ip -a
echo "Deleting Earlier assigned address at Server"
$NS_WDIR/bin/nsu_del_ip -s -a


echo "Re-assigning all addresses"

>/home/cavisson/work/sys/ip_entries

IP_ENTRIES=/home/cavisson/work/sys/ip_entries.save

get_ip_fields()
{
  ENTITY=`echo $1 | cut -d "|" -f1`
  NETID=`echo $1 | cut -d "|" -f2`
  NETBITS=`echo $1 | cut -d "|" -f3`
  START_IP=`echo $1 | cut -d "|" -f4`
  NUM_IP=`echo $1 | cut -d "|" -f6`
  VLAN=`echo $1 | cut -d "|" -f7`
  GATEWAY=`echo $1 | cut -d "|" -f8`
  if [ "$GATEWAY" = "0.0.0.0" ];then
	GATEWAY="-"
  fi
}

if [ -f $IP_ENTRIES ];then
    #i while read line
    for line in `cat $IP_ENTRIES` 
    do
      get_ip_fields $line
      if [ "$ENTITY" == "S" ];then
#	echo 'nsu_assign_ip -s "${NETID}/${NETBITS}|${START_IP}:${NUM_IP}|${VLAN}|${GATEWAY}"'
	$NS_WDIR/bin/nsu_assign_ip -s "${NETID}/${NETBITS}|${START_IP}:${NUM_IP}|${VLAN}|${GATEWAY}"
      else
#	echo 'nsu_assign_ip "${NETID}/${NETBITS}|${START_IP}:${NUM_IP}|${VLAN}|${GATEWAY}"'
	$NS_WDIR/bin/nsu_assign_ip "${NETID}/${NETBITS}|${START_IP}:${NUM_IP}|${VLAN}|${GATEWAY}"
      fi
    done 
    #done <$IP_ENTRIES
fi
echo "Resysnc Completed"
#for line in `cat sys/ip_entries`
#do
#echo $line
#done
