#!/bin/bash

#include sendmail_utils shell
. $NS_WDIR/bin/sendmail_utils
export RM_LOG=0
export TEST_DURATION=""

###Function to send mail if EMAIL_SUMMARY_REPORT keyword is in scenario#####
#Subject line will be “Test run <number> for scenario “<scenario>” completed”
#Body message will be as follows
# Team,

# 	Following are the test details
# 	TR number			:
# 	Machine and Controller	:
# 	Scenario			:
# 	Start time of test_run	:
# 	Duration of test_run		:

# Cavisson Team
#using sendmail and configure sendmail according to manual provided

# if enhance number of argument from calling shell then please do not forget to change condition here 
#if [ $# -lt 1 -o $# -gt 6 ]; then  
if [ $# -lt 1 -o $# -gt 8 ]; then
  echo "usage:  nsu_post_proc_always <test number> <WORKSPACE_PROFILE> [RM_LOG] [test duration(HH:MM:SS)]"
  exit 1
fi

#At least Test Run is required
while getopts t:r:d:w:? c
do
  case $c in
    t) TEST_RUN=$OPTARG;;
    r) RM_LOG=$OPTARG;;
    d) TEST_DURATION=$OPTARG;;
    w) WORKSPACE_PROFILE=$OPTARG;;
    ?) Usage "Invalid arguments";;
    *) Usage "Invalid arguments";;
  esac
done

#Update summary.top
TRNumDir="logs/TR$TEST_RUN"
Unavailable="Unavailable"
Available="Available"
TFILE="/tmp/nsu_post_proc.$$"

    export PgDump=$Unavailable
    export RptDet=$Unavailable
    export RptUser=$Unavailable
    export RptFail=$Unavailable
    export RptPgBrDown=$Unavailable

CONFIG=`$NS_WDIR/bin/nsi_show_config`
if [ "X$CONFIG" != "XNS" -a "X$CONFIG" != "XNC" -a "X$CONFIG" != "XNS>NO" -a "X$CONFIG" != "XNS+NO" ];then
   echo "Summary report only generated in case of NS or NC" >>$TRNumDir/ns_logs/email_report.logs
   exit 0
fi
#In release 3.9.7, page dump feature has been redesign now page_dump.txt file is not created 
#therefore check value of environment variable $PAGE_SNAPSHOTS, if set then assign PgDump variable with Available_New
    if [ $PAGE_SNAPSHOTS -eq 1 ];then
      export PgDump="Available_New"
    fi
    if [ -f $TRNumDir/detail.report ];then
      export RptDet=$Available
    fi
    if [ -f $TRNumDir/users.report ];then
      export RptUser=$Available
    fi
    if [ -f $TRNumDir/fail.report ];then
      export RptFail=$Available
    fi
    if [ -f $TRNumDir/pagedetail.report ];then
      export RptPgBrDown=$Available
    fi

if [ -f $TRNumDir/summary.top ];then
  cat $TRNumDir/summary.top | awk -F\| '{ printf "%s|%s|%s|%s|%s|%s|%s|%s|%s|%s|%s|%s|%s|%s|%s|%s\n", $1, $2, $3, $4, ENVIRON["PgDump"], $6, ENVIRON["RptDet"], ENVIRON["RptUser"], ENVIRON["RptFail"], ENVIRON["RptPgBrDown"], $11, $12, $13, $14, ENVIRON["TEST_DURATION"], $16 }' >$TFILE
  mv $TFILE $TRNumDir/summary.top
else
  echo "$1|-|-|-|$PgDump|-|$RptDet|$RptUser|$RptFail|$RptPgBrDown|-|-|$1|W|$TEST_DURATION|-" >$TRNumDir/summaryTRNumDir/summary.top
fi

DateTime=`cat $TRNumDir/summary.top | cut -d"|" -f3`
#USER_NAME=`whoami`
USER_NAME=`cat $TRNumDir/summary.top | cut -d"|" -f6`
if [ "X$USER_NAME" -eq "X" ];then
  USER_NAME="cavisson"
fi

nsi_update_user_test_times $USER_NAME "$TEST_DURATION" "$DateTime"

$NS_WDIR/bin/nsi_gen_rep_set $TEST_RUN $USER_NAME $DateTime $TEST_DURATION $WORKSPACE_PROFILE>$NS_WDIR/logs/TR$TEST_RUN/nsi_gen_rep_set.log 2>&1
$NS_WDIR/bin/nsi_update_usages_report $TEST_RUN >$NS_WDIR/logs/TR$TEST_RUN/nsi_update_usages_report.log 2>&1

####if EMAIL_SUMMARY_REPORT keyword is there in mprof then call function to send mail########
declare -a arg
line=$(grep -v "#EMAIL_SUMMARY_REPORT" $TRNumDir/scenario|grep -m 1 "EMAIL_SUMMARY_REPORT")

echo " Keyword for email found in scenario are :- [ $line ] " >>$TRNumDir/ns_logs/email_report.logs
SUMMARY_RPT_FILE=_SummaryReport
i=0
for ar in $line
 do
  arg[${i}]=$ar
  i=`expr $i + 1`
done
if [ "X${arg[0]}" == "XEMAIL_SUMMARY_REPORT" ]; then
  if [ ${arg[1]} -gt 0 ];then
    send_mail $TEST_RUN $TEST_DURATION ${arg[1]} $NS_WDIR 1 $SUMMARY_RPT_FILE 80 ${arg[2]} ${arg[3]} ${arg[4]}
  fi
fi
exit 0
