#!/bin/bash
export NS_WDIR=$1
LOGS=/tmp/nsu_check_test_running_on_generator.$$
$NS_WDIR/bin/nsu_show_netstorm >$LOGS
if [ $? -eq 0 ];then
  GEN_TR=`cat $LOGS |grep -v 'TestRun' |awk '{print $1}'`
  echo "$GEN_TR"
else
  echo "false"
fi
rm $LOGS 2>/dev/null
