#!/bin/sh
# Name       : nsu_delete_url_based_script
# Author     : Achint/Atul
# Purpsose   : To Delete the script file genrated through URLs.
# Usage      : nsu_delete_url_based_script [-f] | [-t TR#] | [-t TR# -g GR# ]
# Exit Values:
#    0 - Sucessfull
#    1 - Validation failure
#   -1 - Bad Arguments
#
#  Modification History:
#   12/08/06: Achint/Atul - Initial Version
#

if [ "XX$NS_WDIR" == "XX" ];then
  NS_WDIR=/home/cavisson/work
fi

script=.UrlBasedScript_
SUCCESS=0
FAILURE=-1

usage()
{
  echo "nsu_delete_url_based_script [-f ] | [-t <TestRun#>] | [-t <TestRun#> -g <GroupId#> ]"
  exit 1
}

isdigit ()    # Tests whether *entire string* is numerical.
{             # In other words, tests for integer variable.
  [ $# -eq 1 ] || return $FAILURE

  case $1 in
  *[!0-9]*|"") return $FAILURE;;
            *) return $SUCCESS;;
  esac
}

delete_script ()
{
  dFile="$NS_WDIR/$DELETE_SCRIPT"
  rm  -rf $dFile > /dev/null 2>&1
}

is_test=0
is_group=0
is_full=0
is_proj_sub_proj=0
DELETE_SCRIPT=""


if [ $# -lt 1 ];then
  echo "Do you want to delete all URL based scripts:(y/n)"
  read ans
  if [ $ans == y  -o $ans == Y ];then
    is_full=1  
  else
    echo "Action Canceled"
    exit 1
  fi
fi


while getopts :ft:g:p: argu
do
  case "$argu" in
    f)
        is_full=1;;
    t)
       is_test=1
       if isdigit "$OPTARG"
       then 
         TR=$OPTARG
       else
         usage
       fi
       ;;  
    g)
       if [ $is_test == 0 ];then
         echo "Group number can not be specified without Test run number."
         exit 1
       fi
       SCRPT=_$OPTARG
       is_group=1;;         
    p) 
       PROJ_SUB_PROJ=$OPTARG
       is_proj_sub_proj=1;;
     *)
       usage;;
     ?)
       usage;;
  esac
done

if [ $is_full == 1 ];then
  #** is for Project Subproject
  DELETE_SCRIPT=*/*/$script*
else 
  if [ $is_proj_sub_proj == 1 ];then
    DELETE_SCRIPT=${PROJ_SUB_PROJ}/
  fi
  if [ $is_group == 0 -a $is_test == 1 ];then
    DELETE_SCRIPT=${DELETE_SCRIPT}${script}$TR*
  elif [ $is_group == 1  -a $is_test == 1 ];then
    DELETE_SCRIPT=${DELETE_SCRIPT}${script}$TR
    DELETE_SCRIPT=${DELETE_SCRIPT}$SCRPT
  else
    usage
  fi
fi
delete_script
exit 0
