#!/bin/sh
#
# Name      : nsu_copy_scenario
# Author    : Sudhir
# Purpsose  : To make copy scenario file.
#
# Usage     : nsu_copy_scenario <workspace>/<profile_name>/<proj>/<sub_proj>/<oldScenName>  <workspace>/<profile_name>/<newScenName> <user_name>  <profile_name>
#   e.g.  nsu_copy_scenario tours newtours
#
# Modification History:
#   01/16/06: Sudhir - Initial Version
#   02/05/09:3.2.3 Archana - To implement Project and Subprojects features
#

USER_NAME=admin
PROFILE_NAME=default
oldScenName="$1.conf"
newScenName="$2.conf"


if [ $# -lt 2 ];then
  echo "Usage: nsu_copy_scenario <source> <dest>"
        exit 1
fi

if [ "XX$NS_WDIR" = "XX" ];then
        echo "NS_WDIR must be defined"
        exit 1
fi

if [ "X$3" == "X" ];then
  USER_NAME=$3
fi

if [ "X$4" == "X" ];then
  PROFILE_NAME=$4
fi

#To get project, sub-project and file name separately for old scenario name
OWORKSPACE_NAME=`echo $oldScenName | cut -d"/" -f1`
OPROFILE_NAME=`echo $oldScenName | cut -d"/" -f2`
OPROJ_NAME=`echo $oldScenName | cut -d"/" -f3`
OSUBPOJ_NAME=`echo $oldScenName | cut -d"/" -f4`
OFILE_NAME=`echo $oldScenName | cut -d"/" -f5`
OSCEN_DIR=`echo $OFILE_NAME | cut -d "." -f1`
#To get project, sub-project and file name separately for old scenario name
OSCEN_NAME="$OPROJ_NAME/$OSUBPOJ_NAME/$OSCEN_DIR"

ONS_TA_DIR=$NS_WDIR/workspace/$OWORKSPACE_NAME/$OPROFILE_NAME/cavisson
#reset newScenName, as per new dir struc
oldScenName=$ONS_TA_DIR/$OPROJ_NAME/$OSUBPOJ_NAME/scenarios/$OFILE_NAME
oldScenDir=$ONS_TA_DIR/$OPROJ_NAME/$OSUBPOJ_NAME/scenarios/$OSCEN_DIR


#To get project, sub-project and file name separately for new scenario name
NWORKSPACE_NAME=`echo $newScenName | cut -d"/" -f1`
NPROFILE_NAME=`echo $newScenName | cut -d"/" -f2`
NPROJ_NAME=`echo $newScenName | cut -d"/" -f3`
NSUBPOJ_NAME=`echo $newScenName | cut -d"/" -f4`
NFILE_NAME=`echo $newScenName | cut -d"/" -f5`
NSCEN_DIR=`echo $NFILE_NAME | cut -d "." -f1`
#To get project, sub-project and file name separately for new scenario name
NSCEN_NAME="$NPROJ_NAME/$NSUBPOJ_NAME/$NSCEN_DIR"

#reset newScenName, as per new dir struc
NNS_TA_DIR=$NS_WDIR/workspace/$NWORKSPACE_NAME/$NPROFILE_NAME/cavisson
newScenName=$NNS_TA_DIR/$NPROJ_NAME/$NSUBPOJ_NAME/scenarios/$NFILE_NAME
newScenDir=$NNS_TA_DIR/$NPROJ_NAME/$NSUBPOJ_NAME/scenarios/$NSCEN_DIR

if [ ! -f $oldScenName ];then
        echo "Source scenario $oldScenName does not exist"
        exit 1
fi

if [ -f $newScenDir.conf -o -f $newScenDir.wzrd.conf -o -f $newScenDir.yaml.conf ];then
        echo "Destination scenario-name $newScenDir already exist"
        exit 1
fi

cp $oldScenName $newScenName
if [ ! -f $newScenName ];then
        echo "Unable to create  scenario-dir $newScenName "
        exit 1
fi

if [ -d $oldScenDir ];then
  mkdir -p $newScenDir 
  cp -r $oldScenDir/* $newScenDir/
  if [ -f $newScenDir/scenario.yaml ];then
    sed -i "s|$OSCEN_NAME|$NSCEN_NAME|g" $newScenDir.yaml.conf 
    sed -i "s|$OSCEN_NAME|$NSCEN_NAME|g" $newScenDir/scenario.yaml
    sed -i "s/$OSCEN_DIR/$NSCEN_DIR/g" $newScenDir/scenario.yaml
  elif [ -f $newScenDir/scenario.wzrd ];then
    sed -i "s|$OSCEN_NAME|$NSCEN_NAME|g" $newScenDir.wzrd.conf 
    sed -i "s|$OSCEN_NAME|$NSCEN_NAME|g" $newScenDir/scenario.wzrd 
    sed -i "s/$OSCEN_DIR/$NSCEN_DIR/g" $newScenDir/scenario.wzrd
  fi
fi

# IF replay profile is present for the scenaio we are copying, create dir for replay profile
OLD_REPLAY_PROFILE_PATH=$ONS_TA_DIR/$OPROJ_NAME/$OSUBPOJ_NAME/replay_profiles/$OSCEN_DIR
NEW_REPLAY_PROFILE_PATH=$NNS_TA_DIR/$NPROJ_NAME/$NSUBPOJ_NAME/replay_profiles/$NSCEN_DIR

if [ -d $OLD_REPLAY_PROFILE_PATH ]; then
  if [ ! -d $NEW_REPLAY_PROFILE_PATH ]; then
    mkdir -p $NEW_REPLAY_PROFILE_PATH
    cp $OLD_REPLAY_PROFILE_PATH/*.*  $NEW_REPLAY_PROFILE_PATH
  fi
fi

echo "Scenario $oldScenName copied to $newScenName."
exit 0
