#!/bin/sh
# Name            : nsu_del_server 
# Purpose         : To delete server (for monitors or upgrade)
# Usage           : nsu_add_server "Server Name or Server IP|User name|Password|SSH Y/N |JAVA_HOME|Installation Directory|Server Agent Y/N" 
# Initial Version : Monday, April 27 2009 
#

usage()
{
  echo "nsu_del_server [-a | -s <Server1> <Server2>...]"
  exit 1
}

USER=`whoami`
if [ "X$USER" != "Xcavisson" ];then
    echo "You must be logged in as cavisson user to execute this command"
    exit -1
fi

is_server_already_exist()
{
  SEARCH=$1
  EXIST=`cat $NS_WDIR/server/servers.dat | awk -F'|' '{print $1}' | grep -cw $SEARCH`
}

validate_server()
{
  GIVEN_SERVER=$1
#(100.67.78.98)
  echo "$GIVEN_SERVER" | grep '^\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}$' >/dev/null
  if [ $? -eq 0 ];then
    #Check if dotted part of IP is between 0-255

    XSPART=`echo "$GIVEN_SERVER" | cut -d. -f1`
    YSPART=`echo "$GIVEN_SERVER" | cut -d. -f2`
    ZSPART=`echo "$GIVEN_SERVER" | cut -d. -f3`
    WSPART=`echo "$GIVEN_SERVER" | cut -d. -f4`

    if [ $XSPART -gt 255 -o $YSPART -gt 255 -o $ZSPART -gt 255 -o $WSPART -gt 255 ];then
      echo "Server IP $GIVEN_SERVER is not valid."
      exit 1  
    fi
    if [ $XSPART -lt 0 -o $YSPART -lt 0 -o $ZSPART -lt 0 -o $WSPART -lt 0 ];then
      echo "Server IP $GIVEN_SERVER is not valid."
      exit 1  
    fi
  fi
}

delete_all_servers()
{
  if [ ! -f $SERVER_FILE ];then
    echo "$SERVER_FILE does not exist."
    exit 1
  else
    cp $SERVER_FILE $TEMP_SERVER_FILE 
    grep ^"#" $TEMP_SERVER_FILE >$SERVER_FILE
    echo "All Servers deleted."
  fi
}

delete_specified_servers()
{

  for DEL in $SERVER_LIST
  do
    cp $SERVER_FILE $TEMP_SERVER_FILE 
    validate_server $DEL
    is_server_already_exist $DEL
    if [ $EXIST == 0 ];then
       echo "Can not delete server($DEL) as it does not exist"
       RET=2
       continue;
    fi

    grep -v ^$DEL $TEMP_SERVER_FILE >$SERVER_FILE
    echo "Server '$DEL' deleted successfully."
  done
  rm -f $TEMP_SERVER_FILE
}


if [ $# -lt 1 ];then
  usage
fi

SERVER_FILE="$NS_WDIR/server/servers.dat"
TEMP_SERVER_FILE="/tmp/server.dat"

if [ ! -f $SERVER_FILE ];then
  echo "$SERVER_FILE does not exist"
  exit 1
fi

RET=0

if [ "$1" == "-a" ];then
  delete_all_servers
elif [ "$1" == "-s" ];then
  if [ $# -lt 2 ];then
    echo "At least one server must be given."
    exit 1
  fi
  shift 1
  SERVER_LIST="$@"
  delete_specified_servers
else
  usage
fi

rm -f $TEMP_SERVER_FILE
exit $RET 
