#!/bin/sh
#----------------------------------------------------------------------
# Name    :    nsu_add_cert
# Author  :    Ankur Nath Mishra
# Purpose :    This is a tool to add details of digital ceritificates and keys to certificate list file
# USage   :    nsu_add_cert <key file name| cert file name> <certficate type PEM DER PFX, for certificates only> <Pass phrase, for PFX type certificates only>  
# Format  :    FILE|TYPE|ISSUER|CN|DIV|ORG|LOC|STATE|COUNTRY|EMAIL|EXP|KEYSIZE
#Modification History:
#   04/11/2012:  Ankur Nath Mishra - Initial Version
#----------------------------------------------------------------------
CERT_DIR=$NS_WDIR/cert
CERT_FILE=cert_list.dat
if [ ! -f $CERT_DIR/$CERT_FILE ];then
  echo "cert_list.dat file not found"
  exit -1
fi
usage()
{
 echo "usage:"
 echo "nsu_add_cert <key file name| cert file name> <certficate type PEM DER PFX, for certificates only> <Pass phrase, for PFX type certificates only>"
 echo "Example:"
 echo "nsu_add_cert server_key.pem"
 echo "nsu_add_cert server_cert.pem PEM"
 echo "nsu_add_cert server_cert.pfx PFX password" 
 exit -1
}
get_cert_data()
{
  SET_CERT=`grep 'BEGIN CERTIFICATE' $CERT_DIR/$1`
  if [ "XX$SET_CERT" == "XX" ];then
    echo "File $1 is not a valid Certificate file"
    exit -1
  fi
  ISSUER=`openssl verify $CERT_DIR/$1 | grep error | cut -d ':' -f2`
  SUBJECT=`openssl x509 -inform $2 -in $CERT_DIR/$1 -noout -subject` 
  ORG=`echo $SUBJECT| grep -o "O=[a-zA-Z0-9., -]*" | cut -d '=' -f2`
  CN=`echo $SUBJECT| grep -o "CN=[a-zA-Z0-9.-]*" | cut -d '=' -f2`
  LOC=`echo $SUBJECT| grep -o "L=[a-zA-Z0-9., -]*" | cut -d '=' -f2`
  COUNTRY=`echo $SUBJECT| grep -o "C=[A-Z][A-Z]" | cut -d '=' -f2`
  STATE=`echo $SUBJECT| grep -o "ST=[a-zA-Z0-9., -]*"| cut -d '=' -f2`
  EMAIL=`echo $SUBJECT| grep -o "emailAddress=[a-zA-Z0-9.@_-]*"| cut -d '=' -f2`
  DIV=`echo $SUBJECT| grep -o "OU=[a-zA-Z0-9., -]*" | cut -d '=' -f2`  
  EXP_DATE=`openssl x509 -inform $2 -in $CERT_DIR/$1 -noout -enddate|cut -d '=' -f2` 
}
get_key_size()
{
  Start=`grep -n "BEGIN RSA" $CERT_DIR/$1 | cut -d ':' -f1`
  End=`grep -n "END RSA" $CERT_DIR/$1 | cut -d ':' -f1`
  if [ "XX$Start" == "XX" ];then
    Start=`grep -n "BEGIN PRIVATE KEY" $CERT_DIR/$1 | cut -d ':' -f1`
    End=`grep -n "END PRIVATE KEY" $CERT_DIR/$1 | cut -d ':' -f1`
  fi
  if [ "XX$Start" == "XX" ];then
    KEY_SIZE=0
  else
    start_mod=`expr $End - 1`
    end_mod=`expr $start_mod - $Start`
    #echo "$Start $End $start_mod $end_mod"
    KEY_SIZE=`head -$start_mod $CERT_DIR/$1 | tail -$end_mod | wc -c`
  fi
}
get_pfx_data()
{
  CHECK=`openssl pkcs12 -in $1 -out $CERT_DIR/.$1.temp.pem -passin pass:"$3" -passout pass:"Free" 2>&1 | grep unable`
  if [ "XX$CHECK" == "XXunable to load certificate" ];then
    echo "Unable to read file $1"
    exit -1
  else
    get_cert_data .$1.temp.pem pem
    get_key_size .$1.temp.pem
  fi
}
if [ $# -gt 3 -o $# == 0 ];then
 usage
fi
if [ -f $CERT_DIR/$1 ];then
  echo "Adding $1 to repository"
else
  echo "File $1 not imported on the Machine"
  exit -1
fi

 for file in `awk -F "|" '{print $1}' $CERT_DIR/$CERT_FILE | grep -v "#"` 
 do
    if [ "XX$file" == "XX$1" ];then
      echo "File $1 already exists"
      exit -1
    fi
 done
KEY_SIZE=0
KEY_SET=`egrep -c 'PRIVATE KEY' $CERT_DIR/$1`
if [ $KEY_SET != 0 ];then
  get_key_size $1
fi
if [ $# -gt 1 ];then
  TYPE=$2
  if [ "XX$2" == "XXPFX" ];then
    get_pfx_data $1 $3
  else
    if [ "XX$2" == "XXDER" ];then
      CHECK=`openssl x509 -inform DER -in $CERT_DIR/$1 -out $CERT_DIR/.$1.temp.pem -outform pem 2>&1 | grep unable`
      if [ "XX$CHECK" == "XXunable to load certificate" ];then
        echo "Unable to read file $1"
        exit -1
      else
        get_cert_data .$1.temp.pem pem
        get_key_size .$1.temp.pem
      fi
    else 
      get_cert_data $1 $2
      get_key_size $1
    fi
  fi
else
  TYPE='-'
fi
if [ $KEY_SIZE -gt 1024 ];then
  KEY_SIZE="2048"
else
  if [ $KEY_SIZE -gt 0 ];then
    KEY_SIZE="1024"
  else
    KEY_SIZE='-'
  fi
fi
  if [ "XX$ISSUER" == "XX" ];then
    ISSUER='-'
  else
    if [ "XX$ISSUER" == "XXself signed certificate" ];then
      ISSUER="Self"
    else
      ISSUER="CA"
    fi
  fi
  if [ "XX$ORG" == "XX" ];then
    ORG='-'
  fi
  if [ "XX$CN" == "XX" ];then
    CN='-'
  fi
  if [ "XX$DIV" == "XX" ];then
    DIV='-'
  fi
  if [ "XX$LOC" == "XX" ];then
    LOC='-'
  fi
  if [ "XX$COUNTRY" == "XX" ];then
    COUNTRY='-'
  fi
  if [ "XX$STATE" == "XX" ];then
    STATE='-'
  fi
  if [ "XX$EMAIL" == "XX" ];then
    EMAIL='-'
  fi
  if [ "XX$EXP_DATE" == "XX" ];then
    EXP_DATE='-'
  fi
#FILE|TYPE|ISSUER|CN|DIV|ORG|LOC|STATE|COUNTRY|EMAIL|EXP|KEYSIZE
  echo "$1|$TYPE|$ISSUER|$CN|$DIV|$ORG|$LOC|$STATE|$COUNTRY|$EMAIL|$EXP_DATE|$KEY_SIZE" >> $CERT_DIR/$CERT_FILE
  echo "File $1 Successfully added to repository"
exit 0
