#!/bin/sh
#----------------------------------------------------------------------
# Name    :    nsu_import_file
# Author  :    Ankur Nath Mishra
# Purpose :    This is a tool to files from remote machines
# USage   :    nsu_import_file -t <protocol used http|https|scp|ftp|tftp > -h <host name> -l <location of file on serevr> [-p <port> -u <user-name> -x <password>] -o <filepath where you want to save the imported file>   
#Modification History:
#   04/23/2012:  Ankur Nath Mishra - Initial Version
#----------------------------------------------------------------------
usage()
{
  echo "Error:"
  echo "nsu_import_file -t <protocol used http|https|scp|ftp|tftp > -h <host name> -l <location of file on serevr> [-p <port> -u <user-name> -x <password>] -o <filepath where you want to save the imported file>"
  exit -1
}
while getopts t:h:l:p:u:x:o: opt 
do
  case $opt in
    t) PROTO=$OPTARG
       if [ "XX$PROTO" == "XX" ];then
         PROTO="http"
       fi
       ;;
    h) HOST=$OPTARG
       if [ "XX$HOST" == "XX" ];then
         echo "Error: host name '-h' is a mandatory field"
         exit -1
       fi
       ;; 
    l) RLOC=$OPTARG
       if [ "XX$RLOC" == "XX" ];then
         echo "-l is a mandatory argument"
         exit -1
       fi
       ;;
    p) HOST="$HOST:$OPTARG" ;;
    u) USER_ARG="-u $OPTARG:" ;;
    x) USER_ARG="$USER_ARG$OPTARG" ;;
    o) OUT_FILE=$OPTARG
       if [ "XX$OUT_FILE" == "XX" ];then
         echo "Error: Destination file -o is a mandatory argument"
         exit -1
       fi
       ;;
    *) usage ;;
    ?) usage ;;
  esac
done
case $PROTO in
  "http") curl -f $PROTO://$HOST/$RLOC $USER_ARG  -o $OUT_FILE ;;
  "https") curl -k -f $PROTO://$HOST/$RLOC $USER_ARG -o $OUT_FILE ;;
  "ftp") curl $PROTO://$HOST/$RLOC $USER_ARG -o $OUT_FILE ;;
  "scp") curl $PROTO://$HOST/$RLOC $USER_ARG -o $OUT_FILE ;;
  "tftp") curl $PROTO://$HOST/$RLOC $USER_ARG -o $OUT_FILE ;;
  *) echo "Error $PROTO not supported"
     exit -1
     ;;
esac
if [ $? != 0 ];then
   echo "Error: Import from $HOST Failed"
   exit -1
fi

if [ -f $OUT_FILE ];then
  echo "File $OUT_FILE sucessfully imported from $HOST"
  exit 0
else
  echo "Failed to import file $OUT_FILE"
  exit -1
fi
