#!/bin/sh
# Name            : nsu_add_server 
# Purpose         : To add server (for monitors or upgrade)
# Usage           : nsu_add_server "Server Name or Server IP|SSH Y/N |User name|Password|JAVA_HOME|Installation Directory|Agentless Y/N|Machine Type" 
# Initial Version : Monday, April 27 2009 
#

usage()
{
  echo "Usage: nsu_add_server [-f] 'Server Name or Server IP' 'SSH Y/N' 'User name' 'Password' 'JAVA_HOME' 'Installation Directory' 'Agentless Y/N' 'Machine Type'"
  exit 1
}

USER=`whoami`
if [ "X$USER" != "Xcavisson" ];then
    echo "You must be logged in as cavisson user to execute this command"
    exit -1
fi

PING_SERVER="0"

SERVER=""
USER=""
PASSWORD=""
SSH=""
JAVAHOME=""
INSTALL_DIR=""
AGENTLESS=""
MACHINETYPE=""
FUTURE1="NA"
FUTURE2="NA"
FUTURE3="NA"

is_server_already_exist()
{
  SEARCH=$1
 
  EXIST=`cat $NS_WDIR/server/servers.dat | awk -F'|' '{print $1}' | grep -cw ^$SEARCH`
  if [ $EXIST != 0 ];then
    echo "Server $SERVER already exist." 
    exit 1
  fi
}

validate_server()
{
  echo "$SERVER" | grep '^\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}$' >/dev/null
  if [ $? -eq 0 ];then
    #Check if dotted part of IP is between 0-255

    XSPART=`echo "$SERVER" | cut -d. -f1`
    YSPART=`echo "$SERVER" | cut -d. -f2`
    ZSPART=`echo "$SERVER" | cut -d. -f3`
    WSPART=`echo "$SERVER" | cut -d. -f4`

    if [ $XSPART -gt 255 -o $YSPART -gt 255 -o $ZSPART -gt 255 -o $WSPART -gt 255 ];then
      echo "Server IP $SERVER is not valid."
      exit 1  
    fi
    if [ $XSPART -lt 0 -o $YSPART -lt 0 -o $ZSPART -lt 0 -o $WSPART -lt 0 ];then
      echo "Server IP $SERVER is not valid."
      exit 1  
    fi
  fi
  is_server_already_exist $SERVER
  if [ "$PING_SERVER" == "0" ];then
    ping -c 1 -W 1 $SERVER >/dev/null 2>&1 
    if [ $? -ne 0 ];then
      echo "Server '$SERVER' is not pingable. Do you still want to add ? (y/n)"
      ADD=`get_input`
      if [ "X$ADD" != "XY" -a "X$ADD" != "Xy" ];then
        exit 1  
      fi
    fi
  fi
}

validate_user()
{
  USER_NAME_LENGTH=`echo $USER | wc -c`
  if [ $USER_NAME_LENGTH -gt 20 ];then
    echo "Max user name length(20) exceeded !"
    exit 1
  fi
}

validate_password()
{
  PASSWORD_LENGTH=`echo $PASSWORD | wc -c`
  if [ $PASSWORD_LENGTH -gt 20 ];then
    echo "Max password length(20) exceeded !"
    exit 1
  fi
}

validate_ssh()
{
  if [ $SSH == "Y" -o  $SSH == "y" ];then
    SSH="Y"
  else
    SSH="N"
  fi
}

validate_java_home()
{
  START_WITH_SLASH=`echo "$JAVAHOME" | grep -c ^/`
  if [ $START_WITH_SLASH == 0 -a $JAVAHOME != "NA" ];then
    echo "JAVA HOME must be absolute path."
    exit 1
  fi
}

validate_install_dir()
{
  START_WITH_SLASH=`echo "$INSTALL_DIR" | grep -c ^/`
  if [ $START_WITH_SLASH == 0 ];then
    echo "cmon packege installation dir must be absolute path."
    exit 1
  fi
}

validate_server_agent() 
{
  if [ $AGENTLESS == "Y" -o  $AGENTLESS == "y" ];then
    AGENTLESS="Y"
  else
    AGENTLESS="N"
  fi
}

validate_machine_type() 
{
  if [ $MACHINETYPE != "Linux" -a $MACHINETYPE != "LinuxEx" -a $MACHINETYPE != "Solaris" -a $MACHINETYPE != "AIX_Shared_LPAR" -a $MACHINETYPE != "AIX_Dedicated_LPAR" -a $MACHINETYPE != "Windows" -a $MACHINETYPE != "HPUX" -a $MACHINETYPE != "NA" ];then
    echo "Machine type must be among Linux, LinuxEx, Solaris, AIX_Shared_LPAR, AIX_Dedicated_LPAR, Windows, HPUX or NA"
    exit 1
  fi
}

get_input()
{
  INPUT=""
  while [ "X$INPUT" == "X" ]
  do
    read INPUT
  done
  echo $INPUT
}

touch $NS_WDIR/server/servers.dat

if [ $# == 0 ];then
  echo -n "Enter Server Name/IP: "
  SERVER=`get_input`
  echo -n "Enter ssh (Y/N): "
  SSH=`get_input`
  if [ $SSH == "Y" -o $SSH == "y" ];then
    echo -n "Enter User Name: "
    USER=`get_input`
    echo -n "Enter Password: "
    PASSWORD=`get_input`
  else
    USER="NA"
    PASSWORD="NA"
  fi
  echo -n "Enter Java Home: "
  JAVAHOME=`get_input`
  echo -n "Enter cmon packege Installation Dir: "
  INSTALL_DIR=`get_input`
  echo -n "Enter Server Agentless (Y/N): "
  AGENTLESS=`get_input`
  echo -n "Enter Machine type: "
  MACHINETYPE=`get_input`
else
  if [ $# -lt 8 ];then
    echo "$#"
    usage
  elif [ $# == 9 ];then
    if [ "$1" == "-f" ];then
      PING_SERVER="1"
      shift 1
    else
      usage
    fi
  fi
  SERVER="$1"
  SSH="$2"
  USER="$3"
  PASSWORD="$4"
  JAVAHOME="$5"
  INSTALL_DIR="$6"
  AGENTLESS="$7"
  MACHINETYPE="$8"
fi

validate_server
validate_ssh
validate_user
validate_password
validate_java_home
validate_install_dir
validate_server_agent  
validate_machine_type  

echo "$SERVER|$SSH|$USER|$PASSWORD|$JAVAHOME|$INSTALL_DIR|$AGENTLESS|$MACHINETYPE|$FUTURE1|$FUTURE2|$FUTURE3" >>$NS_WDIR/server/servers.dat
echo "Server '$SERVER' added successfully."

exit 0
