#!/bin/bash

# Name  : nsu_reboot_eth 
# Author: Atul
# Usage : nsu_reboot_eth [eth0 eth1 ... ]
# This shell is used to reboot interfaces.If User will provide the Interfaces it will compare and  only reboot to thoes, if  argument is not givin it will search in cav.conf and reboot all interfaces.

if [ `id -u` -ne 0 ];then
    echo "Command must be run through root"
    echo "run this command as 'su -c ./nsu_reboot_eth [eth0 eth1 ... ]"
    exit 1
fi
declare -a array1
old_ifs=$IFS
IFS="|"
NS_TYPE=`${NS_WDIR}/bin/nsi_show_config`
if [ "X$NS_TYPE" = "XNO" -o "X$NS_TYPE" = "XNF" ];then
  LOAD_NAME=`$NS_WDIR/bin/nsi_get_load_interfaces -s`
else
  LOAD_NAME=`$NS_WDIR/bin/nsi_get_load_interfaces`
fi
array1=($LOAD_NAME)

reboot_and_assigned_on_eth()
{
  
  echo "Deleting IP addresses for Load interface{$1} ..."
  su cavisson -c "$NS_WDIR/bin/nsi_del_ip_all $1"
  echo "Bringing Load interface{$1} down ..."
  ifdown $1
  echo "Bringing Load interface{$1} up ..."
  ifup   $1
  echo "Assigning IP addresses for Load interface{$1} ..."
  su cavisson -c "$NS_WDIR/bin/nsi_add_ip_all $1"
  echo "IP assignment is complete for Load interface {$1}"  
  echo ""
}

if [ $# -le 0 ];then
  for(( i = 0 ; i < ${#array1[*]} ; i++ ))
  do
    reboot_and_assigned_on_eth ${array1[$i]}
  done
else
  for Load in $@
  do
     echo $LOAD_NAME | grep -w $Load > /dev/null 2>&1
     if [ $? -ne 0 ];then
       echo "Error: Load Interface($Load) is invalid."
       exit -1
     fi 
  done
  for Load in $@
  do
    reboot_and_assigned_on_eth $Load
  done  
fi
IFS=$old_ifs
