#!/bin/sh
# Name      : nsu_get_jmeter_version
# Author    : Ayush

if [ "XX$NS_WDIR" == "XX" ];then
  echo "NS_WDIR not set"
fi

HOME_DIR=/home/cavisson
JMETER_VERSION_PATH=$NS_WDIR/jmeter


if [ -d $JMETER_VERSION_PATH ];then
  JMETER_VERSION=$(ls -ltr $JMETER_VERSION_PATH | grep ^d | awk '{print $9}' | grep ^apache-jmeter- | cut -d '-' -f 3 | cut -d '.' -f 1,2 | sort -r | head -1)

  if [ -d $JMETER_VERSION_PATH/apache-jmeter-5.0 ];then
    export JMETER_HOME=$JMETER_VERSION_PATH/apache-jmeter-5.0
  elif [ -d $JMETER_VERSION_PATH/apache-jmeter-4.0 ];then
    export JMETER_HOME=$JMETER_VERSION_PATH/apache-jmeter-4.0
  elif [ -d $JMETER_VERSION_PATH/apache-jmeter-3.3 ];then
    export JMETER_HOME=$JMETER_VERSION_PATH/apache-jmeter-3.3
  elif [ -d $JMETER_VERSION_PATH/apache-jmeter-3.2 ];then
    export JMETER_HOME=$JMETER_VERSION_PATH/apache-jmeter-3.2
  elif [ -d $JMETER_VERSION_PATH/apache-jmeter-3.1 ];then
    export JMETER_HOME=$JMETER_VERSION_PATH/apache-jmeter-3.1
  elif [ -d $JMETER_VERSION_PATH/apache-jmeter-3.0 ];then
    export JMETER_HOME=$JMETER_VERSION_PATH/apache-jmeter-3.0
  else
    echo "There is no jmeter version directory in $JMETER_VERSION_PATH . Env variable JMETER_HOME will not be set."
  fi

if [ "$#" == "1" -a "$1" == "-v" ];then
  echo $JMETER_VERSION
fi
fi

if [ -d $HOME_DIR/apps/jdk1.8.0_301 ];then
  export JMETER_JAVA_HOME=$HOME_DIR/apps/jdk1.8.0_301
elif [ -d $HOME_DIR/apps/jdk1.8.0_281 ];then
  export JMETER_JAVA_HOME=$HOME_DIR/apps/jdk1.8.0_281
elif [ -d $HOME_DIR/apps/jdk1.8.0_271 ];then
  export JMETER_JAVA_HOME=$HOME_DIR/apps/jdk1.8.0_271
elif [ -d $HOME_DIR/apps/jdk1.8.0_261 ];then
  export JMETER_JAVA_HOME=$HOME_DIR/apps/jdk1.8.0_261
elif [ -d $HOME_DIR/apps/jdk1.8.0_251 ];then
  export JMETER_JAVA_HOME=$HOME_DIR/apps/jdk1.8.0_251
elif [ -d $HOME_DIR/apps/jdk1.8.0_241 ];then
  export JMETER_JAVA_HOME=$HOME_DIR/apps/jdk1.8.0_241
elif [ -d $HOME_DIR/apps/jdk1.8.0_231 ];then
  export JMETER_JAVA_HOME=$HOME_DIR/apps/jdk1.8.0_231
elif [ -d $HOME_DIR/apps/jdk1.8.0_221 ];then
  export JMETER_JAVA_HOME=$HOME_DIR/apps/jdk1.8.0_221
elif [ -d $HOME_DIR/apps/jdk1.8.0_211 ];then
  export JMETER_JAVA_HOME=$HOME_DIR/apps/jdk1.8.0_211
elif [ -d $HOME_DIR/apps/jdk1.8.0_201 ];then
  export JMETER_JAVA_HOME=$HOME_DIR/apps/jdk1.8.0_201
elif [ -d $HOME_DIR/apps/jdk1.8.0_191 ];then
  export JMETER_JAVA_HOME=$HOME_DIR/apps/jdk1.8.0_191
elif [ -d $HOME_DIR/apps/jdk1.8.0_181 ];then
  export JMETER_JAVA_HOME=$HOME_DIR/apps/jdk1.8.0_181
elif [ -d $HOME_DIR/apps/jdk1.8.0_161 ];then
  export JMETER_JAVA_HOME=$HOME_DIR/apps/jdk1.8.0_161
elif [ -d $HOME_DIR/apps/jdk1.8.0_144 ];then
  export JMETER_JAVA_HOME=$HOME_DIR/apps/jdk1.8.0_144
elif [ -d $HOME_DIR/apps/jdk1.8.0_121 ];then
  export JMETER_JAVA_HOME=$HOME_DIR/apps/jdk1.8.0_121
elif [ -d $HOME_DIR/apps/jdk1.8.0_112 ];then
  export JMETER_JAVA_HOME=$HOME_DIR/apps/jdk1.8.0_112
else
  echo "There is no jdk directory in $HOME_DIR/apps . Env variable JMETER_JAVA_HOME will not be set."
fi
