#!/bin/bash
# Name: nsu_import_and_gen_rep
# Purpsose: This command is called by GUI in case DB is not loaded etc
# Usage: nsu_import_and_gen_rep <test number>
# Example:
# nsu_import_and_gen_rep 1109


if [ $# -ne 1 ]; then
  echo "Usage nsu_import_and_gen_rep <test run number>"
  exit -1
fi

TEST_RUN=$1

TEST_RUN_DIR=$NS_WDIR/logs/TR$TEST_RUN

if [ ! -d $TEST_RUN_DIR ]; then
  echo "Test run $TEST_RUN is not a valid test run number"
  exit -1
fi

NSU_IMPORT_AND_GEN_REP_LOG=$NS_WDIR/logs/TR$TEST_RUN/nsu_import_and_gen_rep.log

> $NSU_IMPORT_AND_GEN_REP_LOG

show_error_and_exit()
{
  echo "$*" >> $NSU_IMPORT_AND_GEN_REP_LOG
  cat $NSU_IMPORT_AND_GEN_REP_LOG
  exit -1
}

echo "Running nsu_import_and_gen_rep at `date` " 
echo "Running nsu_import_and_gen_rep at `date` " >>$NSU_IMPORT_AND_GEN_REP_LOG

echo "Checking number of CSV files" >>$NSU_IMPORT_AND_GEN_REP_LOG
#check for cvs files creation
TOTAL_CSV=`ls -1 $NS_WDIR/logs/TR$TEST_RUN/reports/csv/*.csv 2>/dev/null | wc -l` 
echo "$TOTAL_CSV csv file found" >>$NSU_IMPORT_AND_GEN_REP_LOG

#Atleat 13 files are needed
if [ "$TOTAL_CSV" -lt "13" ]; then
  echo "All CSV files are not present. At least 13 CVS files are required. Total number of CSV files are $TOTAL_CSV" >>$NSU_IMPORT_AND_GEN_REP_LOG
  show_error_and_exit "nsu_import_and_gen_rep aborted due to above error" >>$NSU_IMPORT_AND_GEN_REP_LOG
  exit -1
fi

echo "Starting nsu_import at `date`" >>$NSU_IMPORT_AND_GEN_REP_LOG
nsu_import $TEST_RUN >>$NSU_IMPORT_AND_GEN_REP_LOG 2>&1

echo "Starting nsu_gen_rep at `date`" >>$NSU_IMPORT_AND_GEN_REP_LOG
nsu_gen_rep $TEST_RUN >>$NSU_IMPORT_AND_GEN_REP_LOG 2>&1

echo "Removing dlog and slog" >>$NSU_IMPORT_AND_GEN_REP_LOG
rm -f logs/TR$TEST_RUN/reports/raw_data/dlog logs/TR$1/reports/raw_data/slog >>$NSU_IMPORT_AND_GEN_REP_LOG 2>&1

echo "nsu_import_and_gen_rep is completed at `date`" >>$NSU_IMPORT_AND_GEN_REP_LOG
echo "nsu_import_and_gen_rep is completed at `date`" 

exit 0
