#! /bin/sh

#Here we are creating indexes for tables
#Index will enhance database performance (indexes can be used to obtain fast access)

if [ -d $PWD/TR$1 ]; then
  BASE_DIR=$PWD
elif [ -d $NS_WDIR/logs/TR$1 ]; then
  BASE_DIR=$NS_WDIR/logs
else
  echo "Error: Test run number $1 is not a valid test run number"
  echo "Usage: nsu_orl_drop_index <testrun>"
  echo "Example:"
  echo "  nsu_orl_drop_index 127331"
  exit 1
fi

echo "nsu_orl_drop_index: Please wait indexes will be dropped ..."
START=`date +%s`

psql test cavisson <<+
DROP INDEX IF EXISTS orlStatsSQLIDTable_NormSQLID_$1;
DROP INDEX IF EXISTS orlStatsSQLIDTable_SQLID_$1;
DROP INDEX IF EXISTS orlStatsSQLIDTable_SQLText_$1;

DROP INDEX IF EXISTS orlStatsSnapTable_SnapBeginID_$1;

DROP INDEX IF EXISTS orlStatsSQLStmtOrdByElapsedTime_SnapID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByElapsedTime_InstNum_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByElapsedTime_DBID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByElapsedTime_NormSQLID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByElapsedTime_ElapsedTime_$1;

DROP INDEX IF EXISTS orlStatsSQLStmtOrdByCPUTime_SnapID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByCPUTime_InstNum_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByCPUTime_DBID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByCPUTime_NormSQLID_$1;

DROP INDEX IF EXISTS orlStatsSQLStmtOrdByUsrIOTime_SnapID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByUsrIOTime_InstNum_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByUsrIOTime_DBID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByUsrIOTime_NormSQLID_$1;

DROP INDEX IF EXISTS orlStatsSQLStmtOrdByGets_SnapID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByGets_InstNum_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByGets_DBID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByGets_NormSQLID_$1;

DROP INDEX IF EXISTS orlStatsSQLStmtOrdByReads_SnapID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByReads_InstNum_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByReads_DBID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByReads_NormSQLID_$1;

DROP INDEX IF EXISTS orlStatsSQLStmtOrdByPhyReadsUnopt_SnapID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByPhyReadsUnopt_InstNum_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByPhyReadsUnopt_DBID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByPhyReadsUnopt_NormSQLID_$1;

DROP INDEX IF EXISTS orlStatsSQLStmtOrdByExec_SnapID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByExec_InstNum_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByExec_DBID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByExec_NormSQLID_$1;

DROP INDEX IF EXISTS orlStatsSQLStmtOrdByParseCalls_SnapID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByParseCalls_InstNum_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByParseCalls_DBID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByParseCalls_NormSQLID_$1;

DROP INDEX IF EXISTS orlStatsSQLStmtOrdBySharableMemory_SnapID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdBySharableMemory_InstNum_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdBySharableMemory_DBID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdBySharableMemory_NormSQLID_$1;

DROP INDEX IF EXISTS orlStatsSQLStmtOrdByVersionCount_SnapID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByVersionCount_InstNum_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByVersionCount_DBID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByVersionCount_NormSQLID_$1;

DROP INDEX IF EXISTS orlStatsSQLStmtOrdByClusterWaitTime_SnapID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByClusterWaitTime_InstNum_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByClusterWaitTime_DBID_$1;
DROP INDEX IF EXISTS orlStatsSQLStmtOrdByClusterWaitTime_NormSQLID_$1;
+

END=`date +%s`
#echo $END
#echo $START
DIFF=`expr $END - $START`
#echo $DIFF
echo "nsu_orl_drop_index: Deletion of indexes took $DIFF seconds"
