#!/bin/sh
#####################################################################
# Name    :    nsu_ship_build
# Author  :    Anuj Sharma
# Purpose :    This is a shell which calls the sub shell nsu_ship_build.expect
#              which is used to copy builds on different machines by
#              
# Usage   :    nsu_ship_build <FILE_NAME> <PASSWORD>
#
#
# Modification History:
# 03/27/08 : Anuj Sharma - Initial Version
#####################################################################
CUR_DIR=`pwd`
INPUT_FILE=$CUR_DIR/machines.lst
#PATH_WHERE_TO_COPY_BUILD=/home/cavisson/test/
PATH_WHERE_TO_COPY_BUILD=/home/cavisson/work/upgrade/

FILE_NAME=$1
PASSWORD=$2

if [ "XX$FILE_NAME" == "XX" -o  "XX$PASSWORD" == "XX" ];then
   echo "usage: nsu_ship_build.sh <file_name> <root_password>"
   exit 0
fi 

echo "current directory is $CUR_DIR"

#This function is used to copy the builds to different machines whose ip's are 
#given in machines.lst in the path $NS_WDIR/sys
copy_builds_to_machines()
{ 
 if [ ! -f $INPUT_FILE ];then
   echo "nsu_ship_build: The file [machines.lst] is not present in $NS_WDIR/sys"
   exit 0
 fi
 for line in `cat $INPUT_FILE`
 do
   echo $line | egrep "^#" > /dev/null
   #Ignore commented lines
   if [ $? == 0 ];then
     continue
   fi
   NO_IP=`echo $line`
   echo "NO_IP=$NO_IP FILE_NAME=$FILE_NAME PASSWORD=$PASSWORD"
   echo "PATH_WHERE_TO_COPY_BUILD=$PATH_WHERE_TO_COPY_BUILD"
   ./nsu_ship_build.expect $NO_IP $FILE_NAME $PASSWORD $PATH_WHERE_TO_COPY_BUILD
 done
}

#########################################################################
copy_builds_to_machines
exit 0
