#! /bin/sh

BASE_DIR=""
count=0

function Usage()
{
  echo $*
  echo "Usage: nsu_orlstats_create_table <Test Run Number>"
  echo "Example:"
  echo "  nsu_orl_create_table 1234"
  exit -1
}

if [ $# -ne 1 ]; then
  Usage "Test run number argument is missing"
fi

#Checking if test number is numeric
echo $1 | egrep '^[0-9]+$' >/dev/null 2>&1
if [ "$?" -eq "1" ]; then
  Usage "Test run number is not numeric"
fi

#Checking Test number is valid or not
if [ -d $PWD/TR$1 ]; then
  BASE_DIR=$PWD
elif [ -d $NS_WDIR/logs/TR$1 ]; then
  BASE_DIR=$NS_WDIR/logs
else
  echo "Error: Test run number $1 is not a valid test run number"
  exit -1
fi

#echo "Deleting existing tables and indexes, if any present and creating tables and indexes ..."
echo 
echo "nsu_orl_create_table: Deleting existing indexes ..."
#. nsu_orl_drop_index $1
echo "nsu_orl_create_table: ... Done deleting indexes."
echo
echo "nsu_orl_create_table: Dropping existing tables and creating afresh for this test run ..."

#nsu_orl_drop_table $1

ORL_TABLE_ARRAY=("orlstatssqlidtable_$1" "orlstatssnaptable_$1" "orlstatssqlstmtordbyelapsedtime_$1" "orlstatssqlstmtordbycputime_$1" "orlstatssqlstmtordbyusriotime_$1" "orlstatssqlstmtordbygets_$1" "orlstatssqlstmtordbyreads_$1" "orlstatssqlstmtordbyphyreadsunopt_$1" "orlstatssqlstmtordbyexec_$1" "orlstatssqlstmtordbyparsecalls_$1" "orlstatssqlstmtordbysharablememory_$1" "orlstatssqlstmtordbyversioncount_$1" "orlstatssqlstmtordbyclusterwaittime_$1")

while [ $count -lt ${#ORL_TABLE_ARRAY[@]} ] ; do
    ORL_TABLE_NAME=`echo ${ORL_TABLE_ARRAY[$count]}`
    CHECK_TABLE=`psql --user=cavisson -d test -t -c "SELECT table_name from information_schema.tables where  table_name ~ '^$ORL_TABLE_NAME$';"` 
    if [ "X$CHECK_TABLE" == "X" ];then 
      case $count in
      0) echo "creating orlStatsSQLIDTable_$1 table"
        psql test cavisson <<+

          create table orlStatsSQLIDTable_$1 (
            NormSQLID		int,
            SQLID		text,
            SQLText		text 
          );
+
      ;;
      1) echo  "Creating table orlStatsSnapTable_$1 "
         psql test cavisson <<+
           create table orlStatsSnapTable_$1 (
             DBName			text,
             DBID			text,
             InstanceName		text,
             InstNum			int,
             InstanceStartTime		bigint, --Seconds
             InstanceRelease		text,
             RAC			text,
             HostName			text,
             Platform			text,
             NumCPU			smallint,
             NumCores			smallint,
             NumSockets			smallint,
             MemoryGB			float,
             SnapBeginID		int,
             StartTime			bigint, --Seconds
             SnapBeginSessionNum	int,
             SnapBeginCursorsPerSession	float,
             SnapBeginInstances		int,
             SnapEndID			int,
             EndTime			bigint, --Seconds
             SnapEndSessionNum		int,
             SnapEndCursorsPerSession	float,
             SnapEndInstances		int,
             SnapElapsedTimeMS		bigint,
             SnapDBTimeMS		numeric,
             TotalDBTimeMS		numeric,
             TotalCPUTimeMS		numeric, --Used by CPU time query 
             TotalUserIOWaitTimeMS      numeric, --Used by User IO time query
             TotalBufferGets		numeric, --Read from Order By Gets report
             TotalDiskReads		numeric, --read from order by reads report
             TotalPhyReadReqs		numeric, --read from ord by phy read report
             TotalUnOptReadReq		numeric, --read from ord by phy read report
             TotalOptReadReq		int, --read from ord by phy read report
             TotalExecutions		int, --read from ord by execution report
             TotalParseCalls		numeric, --read from ord by parse calls report
             TotalSharedmem		numeric, --read from ord by shared mem report
             TotalClusterWaitTimeMS	numeric --read from ord by cluster wait time report
);
+
       ;;
      2) echo  "Creating Table orlStatsSQLStmtOrdByElapsedTime_$1"
         psql test cavisson <<+
           create table orlStatsSQLStmtOrdByElapsedTime_$1 (
             SnapID		int,
             InstNum		int,
             DBID		text,
             ElapsedTimeMS	numeric,
             Executions		int,
             CPUTimeMS		bigint,
             IOTimeMS		bigint,
             NormSQLID		int,
             SQLModule		text
           );
+
         ;;
      3) echo  "Creating Table orlStatsSQLStmtOrdByCPUTime_$1"
         psql test cavisson <<+
          create table orlStatsSQLStmtOrdByCPUTime_$1 (
            SnapID		int,
            InstNum		int,
            DBID		text,
            CPUTimeMS		numeric,
            Executions		int,
            CPUTimePerExecMS	bigint,
            ElapsedTimeMS	numeric,
            IOTimeMS		bigint,
            NormSQLID		int,
            SQLModule		text
          );
+
      ;;
      4) echo  "Creating Table orlStatsSQLStmtOrdByUsrIOTime_$1"
         psql test cavisson <<+
          create table orlStatsSQLStmtOrdByUsrIOTime_$1 (
            SnapID		int,
            InstNum		int,
            DBID		text,
            UserIOTimeMS	numeric,
            Executions		int,
            ElapsedTimeMS	numeric,
            CPUTimeMS		bigint,
            IOTimeMS		bigint,
            NormSQLID		int,
            SQLModule		text
          );
+
      ;; 
      5) echo  "Creating Table orlStatsSQLStmtOrdByGets_$1"
         psql test cavisson <<+
           create table orlStatsSQLStmtOrdByGets_$1 (
             SnapID		int,
             InstNum		int,
             DBID		text,
             BufferGets		numeric,
             Executions		numeric,
             TotalElapsedTimeMS	bigint,
             ElapsedTimeMS	numeric,
             CPUTimeMS		bigint,
             IOTimeMS		bigint,
             NormSQLID		int,
             SQLModule		text
           );
+
      ;;
      6) echo  "Creating Table orlStatsSQLStmtOrdByReads_$1"
           psql test cavisson <<+
            create table orlStatsSQLStmtOrdByReads_$1 (
              SnapID		int,
              InstNum		int,
              DBID		text,
              PhysicalReads	numeric,
              Executions	numeric,
              PhyReads		int,
              ElapsedTimeMS	numeric,
              CPUTimeMS		numeric,
              IOTimeMS		numeric,
              NormSQLID		int,
              SQLModule		text
            );
+
      ;;
      7) echo  "Creating Table orlStatsSQLStmtOrdByPhyReadsUnopt_$1"
           psql test cavisson <<+
            create table orlStatsSQLStmtOrdByPhyReadsUnopt_$1 (
              SnapID		int,
              InstNum		int,
              DBID		text,
              UnOptReadReqs	numeric,	
              PhyReadReqs	numeric,
              Executions	numeric,
              OptReadRequests	numeric, 
              NormSQLID		int,	
              SQLModule		text
           );

+
      ;;
      8) echo  "Creating Table orlStatsSQLStmtOrdByExec_$1"
         psql test cavisson <<+
          create table orlStatsSQLStmtOrdByExec_$1 (
            SnapID		int,
            InstNum		int,
            DBID		text,
            Executions		numeric,
            RowsProcessed	numeric,
            ElapsedTimeMS	numeric,
            CPUTimeMS		numeric,
            IOTimeMS		numeric,
            NormSQLID		int,	
            SQLModule		text
          );
+
      ;;
      9) echo  "Creating Table orlStatsSQLStmtOrdByParseCalls_$1"
         psql test cavisson <<+

          create table orlStatsSQLStmtOrdByParseCalls_$1 (
            SnapID		int,
            InstNum		int,
            DBID		text,
            ParseCalls		numeric,
            Executions		bigint,
            NormSQLID		int,	
            SQLModule		text
          );
+
      ;;
      10) echo  "Creating Table orlStatsSQLStmtOrdBySharableMemory_$1"
         psql test cavisson <<+
           create table orlStatsSQLStmtOrdBySharableMemory_$1 (
             SnapID		int,
             InstNum		int,
             DBID		text,
             ShareableMemory    numeric,
             Executions		int,
             NormSQLID		int,	
             SQLModule		text
           );
+
      ;;
      11) echo  "Creating Table orlStatsSQLStmtOrdByVersionCount_$1"
          psql test cavisson <<+
            create table orlStatsSQLStmtOrdByVersionCount_$1 (
              SnapID		int,
              InstNum		int,
              DBID	        text,
              VersionCount	int,
              Executions	int,
              NormSQLID		int,	
              SQLModule		text
            );
+
      ;;
      12) echo  "Creating Table orlStatsSQLStmtOrdByClusterWaitTime_$1"
         psql test cavisson <<+
          create table orlStatsSQLStmtOrdByClusterWaitTime_$1 (
            SnapID		int,
            InstNum		int,
            DBID		text,
            ClusterWaitTimeMS	numeric,
            Executions		int,
            ElapsedTimeMS	numeric,
            CPUTimeMS		numeric,
            IOTimeMS		numeric,
            NormSQLID		int,	
            SQLModule		text
         );
+
      ;;
      *) echo "only 13 tables are allowed for Oracle Stats report"
        ;;
      esac
    fi
count=`expr $count + 1`
done

echo "nsu_orl_create_table: ... Done dropping and creating tables."
