#!/bin/sh

if [ -f index.html ]

then
	rm -f index*
fi
#echo -e "\nPlease enter the URL:-\n"
#read web
wget -O index.html  -q $1

if [ $1 == "www.macys.com" ]
then
	out=`grep -m 1 "release" index.html | cut -c 10-12`
else

	out=`grep -m 1 performance index.html | cut -d '"' -f 2`
fi


if [ -z "$out" ]
then
	echo "String not found..!!"
else 
	echo -e "$out\n"
fi
exit $?
