/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 * Updated by Neeraj Jain. Following changes are made:
 *   - Removed version2 and version1 methods
 *   - Added rstatproc_stats_3x - To allow passing of timeout as argument
 */

#include <memory.h> /* for memset */
#include "rstat.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 2, 0 };

statstime *
rstatproc_stats_3(void *argp, CLIENT *clnt)
{
	static statstime clnt_res;

	// printf("Setting timeout to 0\n");
#if 0
	TIMEOUT.tv_sec = 0;
	if(clnt_control(clnt, CLSET_TIMEOUT, (char *)&TIMEOUT) == FALSE)
	{
		fputs("Can't delay time-out\n", stderr);
		exit(1);
	}
	// printf("Making RPC call \n");
	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RSTATPROC_STATS,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_statstime, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		// return (NULL);
	}
#endif
	// printf("Setting timeout to 2 secs\n");
	TIMEOUT.tv_sec = 2;
	if(clnt_control(clnt, CLSET_TIMEOUT, (char *)&TIMEOUT) == FALSE)
	{
		fputs("Can't delay time-out\n", stderr);
		exit(1);
	}
	// printf("Getting RPC reply \n");
	if (clnt_call (clnt, RSTATPROC_STATS,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_statstime, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

statstime *
rstatproc_stats_3x(void *argp, CLIENT *clnt, struct timeval *timeout)
{
static statstime clnt_res;

	// printf("Setting timeout to 0\n");
	if(clnt_control(clnt, CLSET_TIMEOUT, (char *)timeout) == FALSE)
	{
		fputs("Can't delay time-out\n", stderr);
		return (NULL);
	}
	// printf("Making RPC call \n");
	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RSTATPROC_STATS,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_statstime, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL); // If timeout is passed as 0, it will be NULL or in case of error
	}
	return (&clnt_res);
}

u_int *
rstatproc_havedisk_3(void *argp, CLIENT *clnt)
{
	static u_int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RSTATPROC_HAVEDISK,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_u_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
