#!/bin/sh

postgres_show_log()
{
  #need to handle permission check  
   day=`date|awk '{print $1}'` 
   FILE=`ls -ltr /var/lib/pgsql/data/pg_log/ |grep $day|awk '{print $NF}'`
   if [ ! -f "/var/lib/pgsql/data/pg_log/$FILE" ];then
     echo "ERROR:Postgres log file doesnt exist for $day"
   else
     #create_file_link_path "$FILE"
     tail -1000 "/var/lib/pgsql/data/pg_log/$FILE"
   fi
}

postgres_show_log
