#!/bin/sh
# bin/nsi_page_dump_post_proc
# It will execute sys/site_page_dump_post_proc if present

#After recording and after generating page dump
# Called after saving script and after page dump
# Input will be path e.g. logs/TR$1/docs or scripts/<proj>/<subproj>/<script name>/dump
# This shell MUST run from work dir

if [ $# -lt 2 -o $# -gt 4 ];then
 
  echo "Usage: $0 <Test Run>|Proj/SubProj/ScriptName"
  exit -1
fi

SEARCH_PATH=""
TESTRUN=""
PAGE_PATH=""

if [ "XX" = "XX$NS_WDIR" ];then
  echo "ERROR: NS_WDIR env must be defined"
  exit -1
fi

cd $NS_WDIR

FLOW_NAME=""
while getopts s:t:p:f: arg
do
  case $arg in
    s)SEARCH_PATH=$OPTARG
      WORK_PROFILE=`echo $SEARCH_PATH| cut -d '/' '-f1-2'`
      PROJ_SUBPROJ=`echo $SEARCH_PATH| cut -d '/' '-f3-4'`
      SEARCH_PATH=`nsi_get_work_space_path.sh $WORK_PROFILE $PROJ_SUBPROJ/scripts`
      ;;
    t)TESTRUN=$OPTARG
      ;;
    p)PAGE_PATH=$OPTARG
      ;;
    f)FLOW_NAME=$OPTARG
      ;;
  esac
done

#Must check for FLOWNAMEA and SEARCH PATH here (Before the TESTRUN)
if [ "XX$FLOW_NAME" != "XX" ];then
  if [ "XX$SEARCH_PATH" == "XX" ];then
    echo "Script is not given but flow is given. Use -s option to give the workspace/profile/project/subproject/script with -f flow name"
    exit 1
  else
    SEARCH_PATH=$SEARCH_PATH/dump/$FLOW_NAME
  fi
fi


if [ "XX$TESTRUN" != "XX" ];then
#In case of partition find scripts in common_files 
  if [ -d $NS_WDIR/logs/TR$TESTRUN/common_files ];then
    SEARCH_PATH=$NS_WDIR/logs/TR$TESTRUN/common_files/scripts
  else
    SEARCH_PATH=$NS_WDIR/logs/TR$TESTRUN/scripts
  fi
fi


TMP_FILE=/tmp/changed.$$
run_command()
{
  f=$1
  sed -e 's/\<top\s*!=\s*self\>/top == self/' $f >$TMP_FILE
  mv $f ${f}.changed; mv $TMP_FILE $f
  sed -e 's/self\s*!=\s*top/self == top/' $f >$TMP_FILE
  mv $f ${f}.changed; mv $TMP_FILE $f
  sed -e 's/self\s*===\s*top/self = top/' $f >$TMP_FILE
  mv $f ${f}.changed; mv $TMP_FILE $f
  sed -e 's/top\.location\s*!=\s*location/top\.location == location/' $f >$TMP_FILE
  mv $f ${f}.changed; mv $TMP_FILE $f
  sed -e 's/top\.location\s*!=\s*self\.location/top\.location == self\.location/' $f >$TMP_FILE
  mv $f ${f}.changed; mv $TMP_FILE $f
  sed -e 's/self\.location\s*!=\s*top\.location/self\.location == top\.location/' $f >$TMP_FILE
  mv $f ${f}.changed; mv $TMP_FILE $f
  sed -e 's/topLocation\s*=\s*top\.location/topLocation=self\.location/' $f >$TMP_FILE
  mv $f ${f}.changed; mv $TMP_FILE $f
  sed -e 's/window\.top\s*!=\s*window\.self/window\.top==window\.self/' $f >$TMP_FILE
  mv $f ${f}.changed; mv $TMP_FILE $f
}

if [ "XX$PAGE_PATH" != "XX" ];then
  if [ -f $PAGE_PATH ];then
	egrep -wl "top\s*!=\s*self|self\s*!=\s*top|self\s*===\s*top|top\.location\s*!=\s*self\.location|top\.location\s*!=\s*location|self\.location\s*!=\s*top\.location|topLocation\s*=\s*self\.location|window\.top\s*!=\s*window\.self" $PAGE_PATH >/dev/null 2>&1
    if [ $? -eq 0 ];then
      run_command $PAGE_PATH
    fi 
  fi
else
  if [ -d $SEARCH_PATH ];then
    
    for f in `find $SEARCH_PATH -type f -name *.orig -prune -o -exec egrep -wl "top\s*!=\s*self|self\s*!=\s*top|self\s*===\s*top|top\.location\s*!=\s*self\.location|top\.location\s*!=\s*location|self\.location\s*!=\s*top\.location|topLocation\s*=\s*self\.location|window\.top\s*!=\s*window\.self" {} \;`
    do
      run_command $f
    done
  fi
fi

exit 0
