#!/bin/sh

. ../../../../.cav.build &>/dev/null

BRANCH=`git branch | grep '^*'| sed 's/* //'`
DiffDir=sync_repo

syn_repo()
{
  cd $1
  mkdir -p $DiffDir

  DiffFile=$DiffDir/sync_repo.`date +%d-%m-%Y`.log

  echo "###############################################################" >>$DiffFile
  echo "RepoPath: `pwd`" >>$DiffFile
  echo "DateTime: `date`" >>$DiffFile
  echo "Start: Checking list of changed files"  >> $DiffFile
  echo "====================================="  >> $DiffFile

  git status -uno >> $DiffFile

  echo "Start: Taking diff files"  >> $DiffFile
  echo "====================================="  >> $DiffFile

  git branch >>$DiffFile
  git diff $BRANCH origin/$BRANCH >>$DiffFile

  echo "Start: Updating "  >> $DiffFile
  echo "====================================="  >> $DiffFile

  git pull  >> $DiffFile

  echo "Done"  >> $DiffFile
  echo "====================================="  >> $DiffFile

  # Check for non-pushed files
  chk_commit_but_notpushed $1
}

# Get unpushed data
chk_commit_but_notpushed()
{
  UNPUSHED_FILE="$1/sync_repo/unpushed.diff"
  git status -uno | grep "Your branch is ahead of" >/dev/null 2>&1
  if [ $? -eq 0 ];then
    git diff origin/$BRANCH HEAD >$UNPUSHED_FILE
    echo -e "\033[0;31m\nYour branch has some files which are committed but not pushed.\nFor detail please see the file: \033[1;34m\n  ${UNPUSHED_FILE}\033[0m\n\033[0m"
    echo -e "Push your changes by running command:\n  git push -u origin $BRANCH\n"
  fi
}

# Update Repository: cavisson
syn_repo ${__top_dir}

# Update Repository: prod-src
syn_repo ${__prod_src_dir}


exit 0
