#! /bin/sh
#
# chkconfig: 2345 98 02
# description: system_health server
# system_health   Start up system_health
### BEGIN INIT INFO
# Provides:             system_health
# Required-Start:       
# Required-Stop:        
# Should-Start:         
# Should-Stop:          
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    system_health
### END INIT INFO
system_health_service()
{
export NS_CONTROLLER_NAME=work
export NS_WDIR=/home/cavisson/$NS_CONTROLLER_NAME
. $NS_WDIR/bin/system_health.sh $1
}

USERID=`id -u`
if [ $USERID -ne 0 ];then
  system_health_service $1
else
  export -f system_health_service
  su cavisson -c "system_health_service $1"
fi

