#!/bin/sh

usage()
{
  echo "Usage: ts_assign_ip6 StartIP/netbits-NumIPs|eth"
  exit -1
}

check_user_id()
{
  USERID=`id -u`
  if [ $USERID -ne 0 ];
  then
    echo "You must be root to execute this command !"
    exit 1
  fi
}

validate_ip()
{
  NUM_OCTET=`echo $IP | awk -F":" '{ print NF }'`
  if [ $NUM_OCTET != 8 ];then
   echo "IP is not valid"
   exit -1
  fi
}


assign_ips()
{
  IP_DEC=$( printf "%d" 0x$LAST_OCTET)
  for (( i=0; $i < $NUM_IP;))
  do
    IP_HEX=$( printf "%x" $IP_DEC)
    /sbin/ip -6 addr add  $REM_OCTET:$IP_HEX/$NETBITS dev $INTERFACE
    if [ $? == 0 ];then
      echo $REM_OCTET:$IP_HEX
    fi
    ((IP_DEC=IP_DEC + 1))
    ((i=i + 1))
  done
 
}

ARGS=$1
NUM_ARGS=`echo "$ARGS" | awk -F"|" '{ print NF }'`
if [ $NUM_ARGS -ne 2 ];then
  usage
fi

TEMP=`echo "$ARGS"  | awk -F"|" '{ print $1 }'`
INTERFACE=`echo "$ARGS" | awk -F"|" '{ print $2 }'`
IP=`echo "$TEMP" | awk -F"-" '{ print $1 }'`
NUM_IP=`echo "$TEMP" | awk -F"-" '{ print $2 }'`
StartIP=`echo "$IP" | awk -F"/" '{ print $1 }'`
NETBITS=`echo "$IP" | awk -F"/" '{ print $2 }'`

LAST_OCTET=`echo "$StartIP" | cut -d":" -f8`
REM_OCTET=`echo "$StartIP" | cut -d":" -f1-7`

#echo "TEMP=$TEMP INTERFACE=$INTERFACE IP=$IP NUM_IP=$NUM_IP StartIP=$StartIP NETBITS=$NETBITS LAST_OCTET=$LAST_OCTET REM_OCTET=$REM_OCTET"

check_user_id 
validate_ip
assign_ips


exit 0
