#!/bin/bash
#!/usr/bin/expect

##################################################################################
#Added By Ankur
#Description: A composite repository of comman actions used in Automation
##################################################################################
#Action Start
#Stop Service service_string on server1
#Remove file1 on server1
#Copy file2 to file1 on server1
#Start Service service_string on server1
#Action Stop
function get_agent()
{
    egrep ^$1 $NS_WDIR/server/servers.dat | cut -d '|' -f7
}

function get_os()
{
    egrep ^$1 $NS_WDIR/server/servers.dat | cut -d '|' -f8
}
function get_user()
{
    egrep ^$1 $NS_WDIR/server/servers.dat | cut -d '|' -f3
}
function get_password()
{
    egrep ^$1 $NS_WDIR/server/servers.dat | cut -d '|' -f4
}
function copy_file()
{
    agent=`get_agent $1`
    pass=`get_password $1`
    user=`get_user $1`
    os=`get_os $1`
    echo "################################################################"
    echo "Copying $2 to $3 on Server $1"
    if [ $agent == "N" ];then
	nsu_server_admin -s $1 -c "cp -r $2 $3"
	if [ $? != 0 ];then
        	echo "Error in Copying $2 to $3 on Server $1"
		echo "################################################################"
	        exit -1
        fi
    else
	nsu_remote_exec $1 $user $pass "cp -r $2 $3"
	if [ $? != 0 ];then
        	echo "Error in Copying $2 to $3 on Server $1"
		echo "################################################################"
	        exit -1
        fi
    fi
    echo "################################################################"
}
function remove_file()
{
    agent=`get_agent $1`
    pass=`get_password $1`
    user=`get_user $1`
    os=`get_os $1`
    echo "################################################################"
    echo "Removing File $2 on Server $1"
    if [ $agent == "N" ];then
	nsu_server_admin -s $1 -c "rm $2"
	if [ $? != 0 ];then
		echo "Error in Removing $2 on Server $1"
		echo "################################################################"
	        exit -1
        fi
    else
	nsu_remote_exec $1 $user $pass "rm $2"
	if [ $? != 0 ];then
		echo "Error in Removing $2 on Server $1"
		echo "################################################################"
	        exit -1
        fi
    fi
    echo "################################################################"
}
function start_service()
{
    agent=`get_agent $1`
    pass=`get_password $1`
    user=`get_user $1`
    os=`get_os $1`
    echo "################################################################"
    echo "Starting Service with String $2 on Server $1"
    if [ $agent == "N" ];then
	nsu_server_admin -s $1 -c "$2 start"
	if [ $? != 0 ];then
        	echo "Error in Starting Service with String $2 on Server $1"
		echo "################################################################"
		exit -1
	fi
    else
	nsu_remote_exec $1 $user $pass "$2 start"
	if [ $? != 0 ];then
	        echo "Error in Starting Service with String $2 on Server $1"
		echo "################################################################"
	        exit -1
        fi
    fi
    echo "################################################################"
}
function sudo_start_service()
{
    agent=`get_agent $1`
    pass=`get_password $1`
    user=`get_user $1`
    os=`get_os $1`
    service=$3

    if [ -z $pass -o "$pass" == "xxx" ]; then
      pass="cavisson"
    fi

    echo "################################################################"
    echo "Starting Service using sudo with String $service on Server $1"
    #nsu_remote_exec $1 $user $pass "$2 $3 start"

    expect -c "
      spawn sudo $service start
      expect {
          \"password for $user:\" {
            send \"$pass\r\"
        }
      }
      send \"exit\r\"
    expect eof"

    if [ $? != 0 ];then
        echo "Error in Starting Service with String $service on Server $1"
	echo "################################################################"
        exit -1
    fi
    echo "################################################################"
}
function stop_service()
{
    agent=`get_agent $1`
    pass=`get_password $1`
    user=`get_user $1`
    os=`get_os $1`
    echo "################################################################"
    echo "Stoping Service with String $2 on Server $1"
    if [ $agent == "N" ];then
	nsu_server_admin -s $1 -c "$2 stop"
	if [ $? != 0 ];then
		echo "Error in Stoping Service with String $2 on Server $1"
		echo "################################################################"
		exit -1
	fi
    else
	nsu_remote_exec $1 $user $pass "$2 stop"
	if [ $? != 0 ];then
		echo "Error in Stoping Service with String $2 on Server $1"
		echo "################################################################"
	        exit -1
        fi
    fi
    echo "################################################################"
}

function sudo_stop_service()
{
    agent=`get_agent $1`
    pass=`get_password $1`
    user=`get_user $1`
    os=`get_os $1`
    service=$3

    if [ -z $pass -o "$pass" == "xxx" ]; then
      pass="cavisson"
    fi

    echo "################################################################"
    echo "Stoping Service using sudo with String $service on Server $1"
    #nsu_remote_exec $1 $user $pass "$2 $3 stop"

    expect -c "
      spawn sudo $service stop
      expect {
          \"password for $user:\" {
            send \"$pass\r\"
        }
      }
      send \"exit\r\"
    expect eof"

    if [ $? != 0 ];then
        echo "Error in Stoping Service with String $service on Server $1"
	echo "################################################################"
        exit -1
    fi
    echo "################################################################"
}
function upload_file()
{
    agent=`get_agent $1`
    pass=`get_password $1`
    user=`get_user $1`
    os=`get_os $1`
    echo "################################################################"
    echo "Uploading file $3 to Server $1"
    if [ $agent == "N" ];then
	nsu_server_admin -s $1 -D $2 -F $3
	if [ $? != 0 ];then
		echo "Error in uploading file $3 to Server $1"
		echo "################################################################"
		exit -1
	fi
   else
	nsu_export_file -t sftp -h $1 -l $2 -u $user -x $pass -o $3 
	if [ $? != 0 ];then
		echo "Error in uploading file $3 to Server $1"
		echo "################################################################"
		exit -1
	fi
   fi
    echo "################################################################"
}
function download_file()
{
    agent=`get_agent $1`
    pass=`get_password $1`
    user=`get_user $1`
    os=`get_os $1`
    echo "################################################################"
    echo "Downloading file $2 from Server $1"
    #nsu_import_file -t scp -h $1 -l $2 -u $user -x $pass -o $3
    #Bug-58187: scp protocol is no more supported by libcurl 
    nsu_server_admin -s $1 -G $2 -f $3 
    if [ $? != 0 ];then
	echo "Error in downloading file $2 from Server $1"
	echo "################################################################"
	exit -1
    fi
    echo "################################################################"
}
function remote_exec()
{
    agent=`get_agent $1`
    pass=`get_password $1`
    user=`get_user $1`
    os=`get_os $1`
    echo "################################################################"
    echo "Executing $2 on Server $1"
    if [ $agent == "N" ];then
	nsu_server_admin -s $1 -c "$2"
    else
	nsu_remote_exec $1 $user $pass "$2"
	if [ $? != 0 ];then
		echo "Error in Executing $2 on Server $1"
		echo "################################################################"
	        exit -1
        fi
    fi
    echo "################################################################"
}
