#!/bin/sh
#*****************************************************************
# * Name    : ts_rm_tsr 
# * Author  : Anuj Sharma
# * Usage   : To See the Usage check the display_help_and_exit function below
# * Purpose : To remove the Logs form the tsr and $NS_WDIR/logs directory
#
# * Initial Version :
# * Last Modification date : 09/03/09 
#*****************************************************************

TEMP_FILE="/tmp/file.$$"
TEMP_TCL_FILE="/tmp/tcl_file.$$"
LOGS_DIR=$NS_WDIR/logs
TSR_DIR=$LOGS_DIR/tsr
TESTSUITE_RUN_ID_FILE=/etc/test_suite_run_id
TESTRUN_ID_FILE=/etc/test_run_id
CLEAR_ALL_LOGS=0
RUN_FORCEFULLY=0
TR_TSR_RESET_NUM=""

display_help_and_exit()
{
  echo "Usage: ts_rm_tsr {{-n <ALL>} | {-n <TEST_CYCLE_NUMBER>} | {-A <No Argument>} } {-r} {-f} "
  echo "Where:"
  echo "  -n <ALL>		  -> Delete All The Test Cycles And Related Test Runs"
  echo "  -n <TEST CYCLE NUMBER>  -> Delete The Given Test Cycle And Related Test Runs"
  echo "  -A <No Argument> 	  -> Delete All The Test Cycles And All The Test Runs"
  echo "  -f <No Argument>	  -> Delete Forcefully [If not Used then It will Ask For Confirmation]"
  echo "  -r <Reset Number>	  -> Reset User Given Values In File [test_suite_run_id, test_run_id]"
  echo "			     With -A Reset Both The File, With -n <ALL> Reset Only test_suite_run_id File"
  exit 1
}

get_field()
{
 BUF="$1"
 FIELD="$2"
 echo $BUF | awk -v field=$FIELD '{print $field}'
}

#This will remove all the TSR TR# for the given Test Cycle Number 
#Also remove the test cycle at the end
remove_all_run_related_to_cycle()
{
 TEST_CYCLE_NUM=$1
 SUMMARY_REPORT=$TSR_DIR/$TEST_CYCLE_NUM/cycle_summary.report
 if [ -f $SUMMARY_REPORT ];then
   cat $SUMMARY_REPORT | tail -n +7 >$TEMP_FILE
 else 
   continue
 fi
 if [ -f $TEMP_FILE ];then
   while read line
   do
     TEST_RUN_NUM=`get_field "$line" 3`
     if [ "XX$TEST_RUN_NUM" != "XX" ];then
       nsu_rm_trun -n $TEST_RUN_NUM -f   #Removing the test run numbers related to the testsuite
     fi
   done < $TEMP_FILE
 fi
 rm -rf $TSR_DIR/$TEST_CYCLE_NUM #Removing the test suite
 rm -rf $TEMP_FILE 
}

#This is common function used by remove_all_testcycles() 
common_func_all_testcycles()
{
  #Create a file for the list of all test cycles
  ls -1 $TSR_DIR > $TEMP_TCL_FILE

  while read line
  do
    remove_all_run_related_to_cycle $line  
  done < $TEMP_TCL_FILE
  rm -rf $TEMP_TCL_FILE

  if [ "XX$TR_TSR_RESET_NUM" != "XX" ];then
   echo $TR_TSR_RESET_NUM > $TESTSUITE_RUN_ID_FILE
 fi
}

#This is to remove all the testcycle and related TSR and TR# either forcefully or not
remove_all_testcycles()
{
 #This is a -n <TCL> loop used by the gui to delete the test cycle number
 if [ "XX$RUN_FORCEFULLY" == "XX0" ];then
   echo -n "All DB, logs & report Records for ALL the test cycles and related RUNS and TSR would be removed, are you sure? (y/n)"
   read var_to_confirm
   if [ "$var_to_confirm" == "y" -o "$var_to_confirm" == "Y" ];then
     common_func_all_testcycles
   else
     echo "Cancelling Action. Exiting without removing anything"
   fi
 else
   common_func_all_testcycles
 fi
}

#This function is to remove all the logs tsr and test cycle and reset the /etc/test_suite_id and 
#/etc/test_run_id file to a number if given by the user
remove_all_testrun_testsuite()
{
 nsu_rm_trun >/dev/null 2>&1 <<+
y
+
#Let this + be right here otherwise the code will not work
 if [ $? != 0 ];then 
   "Errro in removing test runs"
 fi
 rm -rf $TSR_DIR/*

 if [ "XX$TR_TSR_RESET_NUM" != "XX" ];then
   echo $TR_TSR_RESET_NUM > $TESTSUITE_RUN_ID_FILE
   echo $TR_TSR_RESET_NUM > $TESTRUN_ID_FILE      
 fi 
}

#This function is to check if all the logs are to be cleared forcefully or not
clear_all_logs()
{
 #check for if executed forcefully or not
 if [ "XX$RUN_FORCEFULLY" == "XX0" ];then
  echo -n "All DB, logs & report Records for All RUNS and ALL the test cycles and TSR would be removed, are you sure? (y/n)"
  read var_to_confirm
  if [ "$var_to_confirm" == "y" -o "$var_to_confirm" == "Y" ];then
    remove_all_testrun_testsuite
  else
   echo "Cancelling Action. Exiting without removing anything"
  fi 
 else 
   remove_all_testrun_testsuite 
 fi    
}

if [ "$#" -eq "0" ];then
  display_help_and_exit
fi

while getopts n:r:Af c
do
  case $c in
    n) TCL_NUM="$OPTARG";;
    A) CLEAR_ALL_LOGS=1;;
    r) TR_TSR_RESET_NUM="$OPTARG";;
    f) RUN_FORCEFULLY=1;;
    ?) 
      display_help_and_exit;;
  esac
done

#This function is to check as what action to be performed based on the user input 
check_action()
{
 if [ "XX$TCL_NUM" != "XX" ];then
   #If other options are given (all, junc value) with -n option then also this loop will work - Need to fix later
   #This option is also used by GUI
   if [ "XX$TCL_NUM" != "XXALL" ];then
     remove_all_run_related_to_cycle $TCL_NUM     
   else
     remove_all_testcycles		#This will delete all the test cycles and related tsr	
   fi
 fi 
  
 #If only -f option is given display help and exit 
 if [ "$#" -eq "1" -a "$RUN_FORCEFULLY" == "1" ];then
   display_help_and_exit 
 fi

 #If -A option is given, this will delete all the TR# TSR TCL
 if [ "XX$CLEAR_ALL_LOGS" == "XX1" ];then
   clear_all_logs
 fi
}

check_action
exit 0
