#!/bin/sh
# Name: ts_stop
# Author: Narendra 
# Purpose: To stop test suite.
#
# Usage:  See Usage method below in the code

#First we save child Process(nsu_start_test) PID. then we kill Parent process(ts_run).
#Then we kill child process of child process (netstorm.debug).
#And at last child process(nsu_start_test).

#Currently we are not supporting gracefully. because ts_run is unable to trap the signal in between 
#process. It will trap when it will complete it's process and there is no mean.

Usage_and_exit()
{
  echo "Usages:"
  echo "ts_stop -c CYCLE-NO [-f]"
  echo "-c - cycle number"
  echo "-f - forcefully stop"
  exit -1
}
STOP_FORCE=0
CYCLE_NO=""
while getopts fc: c
do
  case $c in
    f) STOP_FORCE=1 ;;
    c) CYCLE_NO=$OPTARG ;;
    ?) Usage_and_exit ;;
  esac
done

CYCLE_DIR="$NS_WDIR/logs/tsr/$CYCLE_NO"
TS_RUN_PID=""

if [[ -d $CYCLE_DIR ]];then
# get process id of test suite running
  if [[ -s "$CYCLE_DIR/.ts_pid" ]];then 
    TS_RUN_PID=`cat $CYCLE_DIR/.ts_pid`
  fi
else
  echo "Test cycle number $CYCLE_NO not found."
  exit -1;
fi

if [ "X$TS_RUN_PID" == "X" ];then
  echo "Test cycle number $CYCLE_NO is not running"
  exit -1;
fi

  #There will be only one child process so no need to save in array.
  NS_START_TEST_PID=`pgrep -P $TS_RUN_PID 2>/dev/null`

  #First we will kill parent then child.
  if [ $STOP_FORCE -eq 1 ];then
    # Kill ts_run first
    kill -9 $TS_RUN_PID 2>/dev/null

    #To kill all child process of nsu_start_test.
    pkill -9 -P $NS_START_TEST_PID 2>/dev/null


    #To kill nsu_start_test.
    kill -9 $NS_START_TEST_PID 2>/dev/null

    #In case of forcefully stop we have too set End date from here.
    grep "End Date/Time:" "$CYCLE_DIR/cycle_summary.report" >/dev/null
    if [ $? -ne 0 ];then 
      echo "End Date/Time: `date '+%m/%d/%y %H:%M:%S'`(Stopped)" >>"$CYCLE_DIR/cycle_summary.report"
    fi
  else
    kill -2 $TS_RUN_PID 2>/dev/null
    pkill -9 -P $NS_START_TEST_PID 2>/dev/null
    kill -9 $NS_START_TEST_PID 2>/dev/null
  fi
exit 0
