#!/bin/bash
#
# Output   : Set Permisson of TestSuite as read only or read-write
# Arguments: TestCycleNumber  and TestMode('R' for read only and 'W' for read-write)
#
# Exit Values: 0 for success, 1 for input error and -1 for existence error  

display_help_and_exit()
{
  echo "$1"
  echo "Usage: tsi_set_ts_mode -t <TestCycleNumber>  -m <Mode>"
  echo "Where:"
  echo "  -t is test_cycle_no and may be ',' seperated multiple values"
  echo "  -m is mode and should be 'R' or 'W'"
  exit 1;
}

#Check for correct input from user
check_mandatory_options()
{
  # Input file name is  mandatory
  if [ "XX$TRCycleNum" = "XX" -o "XX$TestCycleMode" = "XX" ];then
    display_help_and_exit "tsi_set_ts_mode: mandatory options are missing"
  fi

 if [ $TestCycleMode != "R" ] &&  [ $TestCycleMode != "W" ];then
     display_help_and_exit "tsi_set_ts_mode: mode should be 'W' or 'R' only"
fi

}

set_ts_mode()
{
ALL_TCN=`echo "$TRCycleNum" | tr ',' ' '`

for tmp_tcn in $ALL_TCN
do
#This will set path to log directory
TestCyclePath=$NS_WDIR/logs/tsr/$tmp_tcn

#This will check existence of directory
if [ ! -d $TestCyclePath ];then
   echo "TestCycle does not exist for $TestCyclePath"
   continue
else
  cd $TestCyclePath
fi  

if [ -f $TestCyclePath/cycle_summary.report ]
 then

   #grep "TestCycleMode:" $TestCyclePath/cycle_summary.report
   #if [ "X$?" != "X0" ];then
   #  echo "TestCycleMode: W">>$CYCLE_SUMMARY_REPORT
   #fi

 val=`grep "TestCycleMode:" $TestCyclePath/cycle_summary.report |awk -F' ' '{print $2}'`
 val_new=`echo "TestCycleMode: $val"`
 mode_new=`echo "TestCycleMode: $TestCycleMode"`
 sed -i "s/$val_new/$mode_new/g" $TestCyclePath/cycle_summary.report
else
   echo "File does't exist, TestMode can't be change"
   continue
fi
done
}
TRCycleNum=""
TestCycleMode=""
while getopts t:m:? opt
do
  case $opt in
    t) TRCycleNum="$OPTARG" ;;
    m) TestCycleMode="$OPTARG" ;;
    ?) display_help_and_exit ;;
    *) display_help_and_exit ;;
  esac
done

export $TestCycleMode
check_mandatory_options
set_ts_mode

exit 0


