#!/bin/sh

mv nsDocShell.cpp docshell/base/nsDocShell.cpp 
mv nsHttpChannel.cpp netwerk/protocol/http/src/nsHttpChannel.cpp 
mv nsHttpChannel.h netwerk/protocol/http/src/nsHttpChannel.h 
mv nsHttpTransaction.cpp netwerk/protocol/http/src/nsHttpTransaction.cpp 
mv nsHttpTransaction.h netwerk/protocol/http/src/nsHttpTransaction.h 
mv TestGtkEmbed.cpp embedding/browser/gtk/tests/TestGtkEmbed.cpp 
mv nsHttpRequestHead.cpp netwerk/protocol/http/src/nsHttpRequestHead.cpp 
mv nsHttpRequestHead.h netwerk/protocol/http/src/nsHttpRequestHead.h 
mv nsHttpHeaderArray.cpp netwerk/protocol/http/src/nsHttpHeaderArray.cpp 
mv nsHttpHeaderArray.h netwerk/protocol/http/src/nsHttpHeaderArray.h 
mv nsProfileAccess.cpp profile/src/nsProfileAccess.cpp
