#!/bin/sh

echo "diffing nsDocShell.cpp"
diff nsDocShell.cpp /home/anil/CurMozilla/docshell/base/nsDocShell.cpp 
echo nsHttpChannel.cpp
diff nsHttpChannel.cpp /home/anil/CurMozilla/netwerk/protocol/http/src/nsHttpChannel.cpp 
echo nsHttpChannel.h
diff nsHttpChannel.h /home/anil/CurMozilla/netwerk/protocol/http/src/nsHttpChannel.h 
echo nsHttpTransaction.cpp
diff nsHttpTransaction.cpp /home/anil/CurMozilla/netwerk/protocol/http/src/nsHttpTransaction.cpp 
echo nsHttpTransaction.h
diff nsHttpTransaction.h /home/anil/CurMozilla/netwerk/protocol/http/src/nsHttpTransaction.h 
echo TestGtkEmbed.cpp
diff TestGtkEmbed.cpp /home/anil/CurMozilla/embedding/browser/gtk/tests/TestGtkEmbed.cpp 
echo nsHttpRequestHead.cpp
diff nsHttpRequestHead.cpp /home/anil/CurMozilla/netwerk/protocol/http/src/nsHttpRequestHead.cpp 
echo nsHttpRequestHead.h
diff nsHttpRequestHead.h /home/anil/CurMozilla/netwerk/protocol/http/src/nsHttpRequestHead.h 
echo nsHttpHeaderArray.cpp
diff nsHttpHeaderArray.cpp /home/anil/CurMozilla/netwerk/protocol/http/src/nsHttpHeaderArray.cpp 
echo nsHttpHeaderArray.h
diff nsHttpHeaderArray.h /home/anil/CurMozilla/netwerk/protocol/http/src/nsHttpHeaderArray.h 
echo nsProfileAccess.cpp
diff nsProfileAccess.cpp /home/anil/CurMozilla/profile/src/nsProfileAccess.cpp
echo capture_urls.c
diff capture_urls.c /home/anil/CurMozilla/capture_urls.c
