#!/bin/sh

#----------------------------------------------------------------------
# Name    :    nsu_check_user
# Author  :    Archana
# Purpose :    This file has method to check that user is a registered 'Active' netstorm user or not.
# Modification History:
#   01/27/09:  Archana - Initial Version
#----------------------------------------------------------------------

. $NS_WDIR/bin/ns_user_admin_lib

USER_NAME=$1
CMD=$2

#This will exit if not Active user
check_user_is_active_cavisson_user $USER_NAME $CMD

exit 0
