#!/bin/sh

#----------------------------------------------------------------------
# Name    :    nsu_show_user_type
# Author  :    Archana
# Purpose :    This commands to show type of group of specified user.
# Usage   :
#  nsu_show_user_type -n <user name>
# Where   :
#  -n <user name> : User Name 
# Format of Output:
#  Group Type
# Modification History:
#   01/27/09:  Archana - Initial Version
#----------------------------------------------------------------------



. $NS_WDIR/bin/ns_user_admin_lib

display_help_and_exit()
{
  err_msgout "$1"
  err_msgout "Usage: nsu_show_user_type -n <User Name>"
  err_msgout "Where:"
  err_msgout "  -n is used to specify User Name"
  exit 1
}

NFLAG=0
check_mandatory_options()
{
   if [ $NFLAG -eq 0 ];then
     err_msgout "nsu_show_user_type: -n option is mandatory"
     display_help_and_exit
   fi
}

check_option()
{
  OPTION_FLAG=$1
  if [ $OPTION_FLAG -gt 0 ] ;then
    err_msgout "nsu_show_user_type: $2 option cannot be specified more than once."
    display_help_and_exit
  fi
}

show_user_group_type()
{
  GROUP_NAME=`egrep -w ^$USER_NAME $USER_PROFILE | cut -d '|' -f2`
  egrep -w ^$GROUP_NAME $GROUP_PROFILE | cut -d"|" -f2
}


while getopts n:? c
do
  case $c in
    n) check_option $NFLAG "-n"
       NFLAG=`expr $NFLAG + 1`
       USER_NAME="$OPTARG" ;;
    ?) display_help_and_exit ;;
    *) display_help_and_exit ;;
  esac
done
check_mandatory_options

check_user_is_cavisson_user $USER_NAME
show_user_group_type
#msgout "----------------------------------------------------------------------"
exit 0

