#!/bin/sh

#----------------------------------------------------------------------
# Name    :    nsu_del_group
# Author  :    Archana
# Purpose :    This will delete all information of specified group from Linux system. 
# Usage   :     nsu_del_group -n <group name>
# Where   :
#  -n <group name>: Group Name 
# Modification History:
#   01/27/09:  Archana - Initial Version
#----------------------------------------------------------------------


# This command only can run by root/admin user only.

. $NS_WDIR/bin/ns_user_admin_lib

#To check uid call check_root_uid
check_root_uid "nsu_del_group"

display_help_and_exit()
{
  err_msgout "$1"
  err_msgout "Usage: nsu_del_group -n <Group Name>"
  err_msgout "Where:"
  err_msgout "  -n is used to specify Group Name"
  exit 1
}

NFLAG=0
check_mandatory_options()
{
   if [ $NFLAG -eq 0 ];then
     err_msgout "nsu_del_group: -n option is mandatory"
     display_help_and_exit
   fi
}

check_option()
{
  OPTION_FLAG=$1
  if [ $OPTION_FLAG -gt 0 ] ;then
    err_msgout "nsu_del_group: $2 option cannot be specified more than once."
    display_help_and_exit
  fi
}

# Need to check netstorm group, since 'netstorm' group can not be delete.
# These are reserved internal group. It should always in group profiles.
check_if_cavisson_group()
{
  if [ "XX$GROUP_NAME" == "XXcavisson" ];then
    err_msgout "Error: '$GROUP_NAME' group cannot be deleted"
    exit -1
  fi
}

#This will delete group details from Linux system using groupdel Linux command
delete_cavisson_group()
{
  CMD_OUT_FILE=/tmp/cmd.out.$$
  CMD_ERR_FILE=/tmp/cmd.err.$$

  grep "|$GROUP_NAME|" $USER_PROFILE >/dev/null
  if [ $? == 0 ]; then
    err_msgout "Error: Group '$GROUP_NAME' can't be deleted, must remove the user before deleting this group"
    exit -1
  fi
 
  groupdel $GROUP_NAME 1>$CMD_OUT_FILE 2>$CMD_ERR_FILE
  cmd_ret_value=$?
  if [ $cmd_ret_value == 0 ]; then
    rm -f $CMD_OUT_FILE $CMD_ERR_FILE
    return 0
  fi

  #Handle errors
  if [ $cmd_ret_value == 6 ]; then
    err_msgout "Error: Group '$GROUP_NAME' doesn't exist"
  else
    err_msgout "Error in deleting group '$GROUP_NAME'."
    cat $CMD_OUT_FILE $CMD_ERR_FILE
  fi
  rm -f $CMD_OUT_FILE $CMD_ERR_FILE
  exit -1
}

while getopts n:? c
do
  case $c in
    n) check_option $NFLAG "-n"
       NFLAG=`expr $NFLAG + 1`
       GROUP_NAME="$OPTARG" ;;
    ?) display_help_and_exit ;;
    *) display_help_and_exit ;;
  esac
done
check_mandatory_options
check_group_is_cavisson_group $GROUP_NAME

check_if_cavisson_group

delete_cavisson_group

#To delete group details from group profile.
delete_group_from_group_profile $GROUP_NAME

echo "Group '$GROUP_NAME' has been successfully deleted from cavisson group."
#msgout "----------------------------------------------------------------------"
exit 0
